// Code generated by MockGen. DO NOT EDIT.
// Source: keycloak_types.go
//
// Generated by this command:
//
//	mockgen -source=keycloak_types.go -destination=mocks/mock_keycloak_types.go -package=mock_domain GroupRepository,RoleRepository
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	domain "github.com/pilab-dev/shadow-sso/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleRepository is a mock of RoleRepository interface.
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleRepositoryMockRecorder is the mock recorder for MockRoleRepository.
type MockRoleRepositoryMockRecorder struct {
	mock *MockRoleRepository
}

// NewMockRoleRepository creates a new mock instance.
func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepository) EXPECT() *MockRoleRepositoryMockRecorder {
	return m.recorder
}

// AddChildRole mocks base method.
func (m *MockRoleRepository) AddChildRole(ctx context.Context, parentID, childID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChildRole", ctx, parentID, childID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChildRole indicates an expected call of AddChildRole.
func (mr *MockRoleRepositoryMockRecorder) AddChildRole(ctx, parentID, childID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChildRole", reflect.TypeOf((*MockRoleRepository)(nil).AddChildRole), ctx, parentID, childID)
}

// CreateRole mocks base method.
func (m *MockRoleRepository) CreateRole(ctx context.Context, role *domain.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", ctx, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockRoleRepositoryMockRecorder) CreateRole(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockRoleRepository)(nil).CreateRole), ctx, role)
}

// DeleteRole mocks base method.
func (m *MockRoleRepository) DeleteRole(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockRoleRepositoryMockRecorder) DeleteRole(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockRoleRepository)(nil).DeleteRole), ctx, id)
}

// GetRoleByID mocks base method.
func (m *MockRoleRepository) GetRoleByID(ctx context.Context, id string) (*domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByID", ctx, id)
	ret0, _ := ret[0].(*domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByID indicates an expected call of GetRoleByID.
func (mr *MockRoleRepositoryMockRecorder) GetRoleByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByID", reflect.TypeOf((*MockRoleRepository)(nil).GetRoleByID), ctx, id)
}

// GetRoleByName mocks base method.
func (m *MockRoleRepository) GetRoleByName(ctx context.Context, name string) (*domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByName", ctx, name)
	ret0, _ := ret[0].(*domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByName indicates an expected call of GetRoleByName.
func (mr *MockRoleRepositoryMockRecorder) GetRoleByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByName", reflect.TypeOf((*MockRoleRepository)(nil).GetRoleByName), ctx, name)
}

// ListClientRoles mocks base method.
func (m *MockRoleRepository) ListClientRoles(ctx context.Context, clientID string) ([]*domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClientRoles", ctx, clientID)
	ret0, _ := ret[0].([]*domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClientRoles indicates an expected call of ListClientRoles.
func (mr *MockRoleRepositoryMockRecorder) ListClientRoles(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClientRoles", reflect.TypeOf((*MockRoleRepository)(nil).ListClientRoles), ctx, clientID)
}

// ListRealmRoles mocks base method.
func (m *MockRoleRepository) ListRealmRoles(ctx context.Context) ([]*domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRealmRoles", ctx)
	ret0, _ := ret[0].([]*domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRealmRoles indicates an expected call of ListRealmRoles.
func (mr *MockRoleRepositoryMockRecorder) ListRealmRoles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRealmRoles", reflect.TypeOf((*MockRoleRepository)(nil).ListRealmRoles), ctx)
}

// ListRoles mocks base method.
func (m *MockRoleRepository) ListRoles(ctx context.Context) ([]*domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", ctx)
	ret0, _ := ret[0].([]*domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockRoleRepositoryMockRecorder) ListRoles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockRoleRepository)(nil).ListRoles), ctx)
}

// RemoveChildRole mocks base method.
func (m *MockRoleRepository) RemoveChildRole(ctx context.Context, parentID, childID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveChildRole", ctx, parentID, childID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveChildRole indicates an expected call of RemoveChildRole.
func (mr *MockRoleRepositoryMockRecorder) RemoveChildRole(ctx, parentID, childID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveChildRole", reflect.TypeOf((*MockRoleRepository)(nil).RemoveChildRole), ctx, parentID, childID)
}

// UpdateRole mocks base method.
func (m *MockRoleRepository) UpdateRole(ctx context.Context, role *domain.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockRoleRepositoryMockRecorder) UpdateRole(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockRoleRepository)(nil).UpdateRole), ctx, role)
}

// MockGroupRepository is a mock of GroupRepository interface.
type MockGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGroupRepositoryMockRecorder
	isgomock struct{}
}

// MockGroupRepositoryMockRecorder is the mock recorder for MockGroupRepository.
type MockGroupRepositoryMockRecorder struct {
	mock *MockGroupRepository
}

// NewMockGroupRepository creates a new mock instance.
func NewMockGroupRepository(ctrl *gomock.Controller) *MockGroupRepository {
	mock := &MockGroupRepository{ctrl: ctrl}
	mock.recorder = &MockGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupRepository) EXPECT() *MockGroupRepositoryMockRecorder {
	return m.recorder
}

// AddClientRole mocks base method.
func (m *MockGroupRepository) AddClientRole(ctx context.Context, groupID, clientID, roleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddClientRole", ctx, groupID, clientID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddClientRole indicates an expected call of AddClientRole.
func (mr *MockGroupRepositoryMockRecorder) AddClientRole(ctx, groupID, clientID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddClientRole", reflect.TypeOf((*MockGroupRepository)(nil).AddClientRole), ctx, groupID, clientID, roleID)
}

// AddMember mocks base method.
func (m *MockGroupRepository) AddMember(ctx context.Context, groupID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, groupID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockGroupRepositoryMockRecorder) AddMember(ctx, groupID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockGroupRepository)(nil).AddMember), ctx, groupID, userID)
}

// AddRealmRole mocks base method.
func (m *MockGroupRepository) AddRealmRole(ctx context.Context, groupID, roleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRealmRole", ctx, groupID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRealmRole indicates an expected call of AddRealmRole.
func (mr *MockGroupRepositoryMockRecorder) AddRealmRole(ctx, groupID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRealmRole", reflect.TypeOf((*MockGroupRepository)(nil).AddRealmRole), ctx, groupID, roleID)
}

// CreateGroup mocks base method.
func (m *MockGroupRepository) CreateGroup(ctx context.Context, group *domain.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockGroupRepositoryMockRecorder) CreateGroup(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockGroupRepository)(nil).CreateGroup), ctx, group)
}

// DeleteGroup mocks base method.
func (m *MockGroupRepository) DeleteGroup(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockGroupRepositoryMockRecorder) DeleteGroup(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockGroupRepository)(nil).DeleteGroup), ctx, id)
}

// GetGroupByID mocks base method.
func (m *MockGroupRepository) GetGroupByID(ctx context.Context, id string) (*domain.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByID", ctx, id)
	ret0, _ := ret[0].(*domain.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByID indicates an expected call of GetGroupByID.
func (mr *MockGroupRepositoryMockRecorder) GetGroupByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByID", reflect.TypeOf((*MockGroupRepository)(nil).GetGroupByID), ctx, id)
}

// GetGroupByPath mocks base method.
func (m *MockGroupRepository) GetGroupByPath(ctx context.Context, path string) (*domain.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByPath", ctx, path)
	ret0, _ := ret[0].(*domain.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByPath indicates an expected call of GetGroupByPath.
func (mr *MockGroupRepositoryMockRecorder) GetGroupByPath(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByPath", reflect.TypeOf((*MockGroupRepository)(nil).GetGroupByPath), ctx, path)
}

// GetGroupsByUserID mocks base method.
func (m *MockGroupRepository) GetGroupsByUserID(ctx context.Context, userID string) ([]*domain.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupsByUserID indicates an expected call of GetGroupsByUserID.
func (mr *MockGroupRepositoryMockRecorder) GetGroupsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupsByUserID", reflect.TypeOf((*MockGroupRepository)(nil).GetGroupsByUserID), ctx, userID)
}

// GetMemberCount mocks base method.
func (m *MockGroupRepository) GetMemberCount(ctx context.Context, groupID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberCount", ctx, groupID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberCount indicates an expected call of GetMemberCount.
func (mr *MockGroupRepositoryMockRecorder) GetMemberCount(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberCount", reflect.TypeOf((*MockGroupRepository)(nil).GetMemberCount), ctx, groupID)
}

// ListGroups mocks base method.
func (m *MockGroupRepository) ListGroups(ctx context.Context) ([]*domain.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroups", ctx)
	ret0, _ := ret[0].([]*domain.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroups indicates an expected call of ListGroups.
func (mr *MockGroupRepositoryMockRecorder) ListGroups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroups", reflect.TypeOf((*MockGroupRepository)(nil).ListGroups), ctx)
}

// RemoveClientRole mocks base method.
func (m *MockGroupRepository) RemoveClientRole(ctx context.Context, groupID, clientID, roleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveClientRole", ctx, groupID, clientID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveClientRole indicates an expected call of RemoveClientRole.
func (mr *MockGroupRepositoryMockRecorder) RemoveClientRole(ctx, groupID, clientID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveClientRole", reflect.TypeOf((*MockGroupRepository)(nil).RemoveClientRole), ctx, groupID, clientID, roleID)
}

// RemoveMember mocks base method.
func (m *MockGroupRepository) RemoveMember(ctx context.Context, groupID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, groupID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockGroupRepositoryMockRecorder) RemoveMember(ctx, groupID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockGroupRepository)(nil).RemoveMember), ctx, groupID, userID)
}

// RemoveRealmRole mocks base method.
func (m *MockGroupRepository) RemoveRealmRole(ctx context.Context, groupID, roleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRealmRole", ctx, groupID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRealmRole indicates an expected call of RemoveRealmRole.
func (mr *MockGroupRepositoryMockRecorder) RemoveRealmRole(ctx, groupID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRealmRole", reflect.TypeOf((*MockGroupRepository)(nil).RemoveRealmRole), ctx, groupID, roleID)
}

// UpdateGroup mocks base method.
func (m *MockGroupRepository) UpdateGroup(ctx context.Context, group *domain.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroup", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGroup indicates an expected call of UpdateGroup.
func (mr *MockGroupRepositoryMockRecorder) UpdateGroup(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroup", reflect.TypeOf((*MockGroupRepository)(nil).UpdateGroup), ctx, group)
}

// MockProtocolMapperRepository is a mock of ProtocolMapperRepository interface.
type MockProtocolMapperRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProtocolMapperRepositoryMockRecorder
	isgomock struct{}
}

// MockProtocolMapperRepositoryMockRecorder is the mock recorder for MockProtocolMapperRepository.
type MockProtocolMapperRepositoryMockRecorder struct {
	mock *MockProtocolMapperRepository
}

// NewMockProtocolMapperRepository creates a new mock instance.
func NewMockProtocolMapperRepository(ctrl *gomock.Controller) *MockProtocolMapperRepository {
	mock := &MockProtocolMapperRepository{ctrl: ctrl}
	mock.recorder = &MockProtocolMapperRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtocolMapperRepository) EXPECT() *MockProtocolMapperRepositoryMockRecorder {
	return m.recorder
}

// CreateProtocolMapper mocks base method.
func (m *MockProtocolMapperRepository) CreateProtocolMapper(ctx context.Context, mapper *domain.ProtocolMapper) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProtocolMapper", ctx, mapper)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProtocolMapper indicates an expected call of CreateProtocolMapper.
func (mr *MockProtocolMapperRepositoryMockRecorder) CreateProtocolMapper(ctx, mapper any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProtocolMapper", reflect.TypeOf((*MockProtocolMapperRepository)(nil).CreateProtocolMapper), ctx, mapper)
}

// DeleteProtocolMapper mocks base method.
func (m *MockProtocolMapperRepository) DeleteProtocolMapper(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProtocolMapper", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProtocolMapper indicates an expected call of DeleteProtocolMapper.
func (mr *MockProtocolMapperRepositoryMockRecorder) DeleteProtocolMapper(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProtocolMapper", reflect.TypeOf((*MockProtocolMapperRepository)(nil).DeleteProtocolMapper), ctx, id)
}

// GetProtocolMapperByID mocks base method.
func (m *MockProtocolMapperRepository) GetProtocolMapperByID(ctx context.Context, id string) (*domain.ProtocolMapper, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProtocolMapperByID", ctx, id)
	ret0, _ := ret[0].(*domain.ProtocolMapper)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProtocolMapperByID indicates an expected call of GetProtocolMapperByID.
func (mr *MockProtocolMapperRepositoryMockRecorder) GetProtocolMapperByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProtocolMapperByID", reflect.TypeOf((*MockProtocolMapperRepository)(nil).GetProtocolMapperByID), ctx, id)
}

// ListClientProtocolMappers mocks base method.
func (m *MockProtocolMapperRepository) ListClientProtocolMappers(ctx context.Context, clientID string) ([]*domain.ProtocolMapper, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClientProtocolMappers", ctx, clientID)
	ret0, _ := ret[0].([]*domain.ProtocolMapper)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClientProtocolMappers indicates an expected call of ListClientProtocolMappers.
func (mr *MockProtocolMapperRepositoryMockRecorder) ListClientProtocolMappers(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClientProtocolMappers", reflect.TypeOf((*MockProtocolMapperRepository)(nil).ListClientProtocolMappers), ctx, clientID)
}

// ListProtocolMappers mocks base method.
func (m *MockProtocolMapperRepository) ListProtocolMappers(ctx context.Context) ([]*domain.ProtocolMapper, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProtocolMappers", ctx)
	ret0, _ := ret[0].([]*domain.ProtocolMapper)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProtocolMappers indicates an expected call of ListProtocolMappers.
func (mr *MockProtocolMapperRepositoryMockRecorder) ListProtocolMappers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProtocolMappers", reflect.TypeOf((*MockProtocolMapperRepository)(nil).ListProtocolMappers), ctx)
}

// UpdateProtocolMapper mocks base method.
func (m *MockProtocolMapperRepository) UpdateProtocolMapper(ctx context.Context, mapper *domain.ProtocolMapper) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProtocolMapper", ctx, mapper)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProtocolMapper indicates an expected call of UpdateProtocolMapper.
func (mr *MockProtocolMapperRepositoryMockRecorder) UpdateProtocolMapper(ctx, mapper any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProtocolMapper", reflect.TypeOf((*MockProtocolMapperRepository)(nil).UpdateProtocolMapper), ctx, mapper)
}

// MockAuthenticationFlowRepository is a mock of AuthenticationFlowRepository interface.
type MockAuthenticationFlowRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticationFlowRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthenticationFlowRepositoryMockRecorder is the mock recorder for MockAuthenticationFlowRepository.
type MockAuthenticationFlowRepositoryMockRecorder struct {
	mock *MockAuthenticationFlowRepository
}

// NewMockAuthenticationFlowRepository creates a new mock instance.
func NewMockAuthenticationFlowRepository(ctrl *gomock.Controller) *MockAuthenticationFlowRepository {
	mock := &MockAuthenticationFlowRepository{ctrl: ctrl}
	mock.recorder = &MockAuthenticationFlowRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticationFlowRepository) EXPECT() *MockAuthenticationFlowRepositoryMockRecorder {
	return m.recorder
}

// CreateFlow mocks base method.
func (m *MockAuthenticationFlowRepository) CreateFlow(ctx context.Context, flow *domain.AuthenticationFlow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFlow", ctx, flow)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFlow indicates an expected call of CreateFlow.
func (mr *MockAuthenticationFlowRepositoryMockRecorder) CreateFlow(ctx, flow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFlow", reflect.TypeOf((*MockAuthenticationFlowRepository)(nil).CreateFlow), ctx, flow)
}

// DeleteExecution mocks base method.
func (m *MockAuthenticationFlowRepository) DeleteExecution(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExecution", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExecution indicates an expected call of DeleteExecution.
func (mr *MockAuthenticationFlowRepositoryMockRecorder) DeleteExecution(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExecution", reflect.TypeOf((*MockAuthenticationFlowRepository)(nil).DeleteExecution), ctx, id)
}

// DeleteFlow mocks base method.
func (m *MockAuthenticationFlowRepository) DeleteFlow(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFlow", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFlow indicates an expected call of DeleteFlow.
func (mr *MockAuthenticationFlowRepositoryMockRecorder) DeleteFlow(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFlow", reflect.TypeOf((*MockAuthenticationFlowRepository)(nil).DeleteFlow), ctx, id)
}

// GetExecutions mocks base method.
func (m *MockAuthenticationFlowRepository) GetExecutions(ctx context.Context, flowID string) ([]*domain.AuthenticationExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutions", ctx, flowID)
	ret0, _ := ret[0].([]*domain.AuthenticationExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecutions indicates an expected call of GetExecutions.
func (mr *MockAuthenticationFlowRepositoryMockRecorder) GetExecutions(ctx, flowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutions", reflect.TypeOf((*MockAuthenticationFlowRepository)(nil).GetExecutions), ctx, flowID)
}

// GetFlowByAlias mocks base method.
func (m *MockAuthenticationFlowRepository) GetFlowByAlias(ctx context.Context, alias string) (*domain.AuthenticationFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlowByAlias", ctx, alias)
	ret0, _ := ret[0].(*domain.AuthenticationFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlowByAlias indicates an expected call of GetFlowByAlias.
func (mr *MockAuthenticationFlowRepositoryMockRecorder) GetFlowByAlias(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlowByAlias", reflect.TypeOf((*MockAuthenticationFlowRepository)(nil).GetFlowByAlias), ctx, alias)
}

// GetFlowByID mocks base method.
func (m *MockAuthenticationFlowRepository) GetFlowByID(ctx context.Context, id string) (*domain.AuthenticationFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlowByID", ctx, id)
	ret0, _ := ret[0].(*domain.AuthenticationFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlowByID indicates an expected call of GetFlowByID.
func (mr *MockAuthenticationFlowRepositoryMockRecorder) GetFlowByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlowByID", reflect.TypeOf((*MockAuthenticationFlowRepository)(nil).GetFlowByID), ctx, id)
}

// ListFlows mocks base method.
func (m *MockAuthenticationFlowRepository) ListFlows(ctx context.Context) ([]*domain.AuthenticationFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFlows", ctx)
	ret0, _ := ret[0].([]*domain.AuthenticationFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFlows indicates an expected call of ListFlows.
func (mr *MockAuthenticationFlowRepositoryMockRecorder) ListFlows(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFlows", reflect.TypeOf((*MockAuthenticationFlowRepository)(nil).ListFlows), ctx)
}

// UpdateFlow mocks base method.
func (m *MockAuthenticationFlowRepository) UpdateFlow(ctx context.Context, flow *domain.AuthenticationFlow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFlow", ctx, flow)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFlow indicates an expected call of UpdateFlow.
func (mr *MockAuthenticationFlowRepositoryMockRecorder) UpdateFlow(ctx, flow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFlow", reflect.TypeOf((*MockAuthenticationFlowRepository)(nil).UpdateFlow), ctx, flow)
}

// UpsertExecution mocks base method.
func (m *MockAuthenticationFlowRepository) UpsertExecution(ctx context.Context, exec *domain.AuthenticationExecution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertExecution", ctx, exec)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertExecution indicates an expected call of UpsertExecution.
func (mr *MockAuthenticationFlowRepositoryMockRecorder) UpsertExecution(ctx, exec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertExecution", reflect.TypeOf((*MockAuthenticationFlowRepository)(nil).UpsertExecution), ctx, exec)
}

// MockClientScopeRepository is a mock of ClientScopeRepository interface.
type MockClientScopeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClientScopeRepositoryMockRecorder
	isgomock struct{}
}

// MockClientScopeRepositoryMockRecorder is the mock recorder for MockClientScopeRepository.
type MockClientScopeRepositoryMockRecorder struct {
	mock *MockClientScopeRepository
}

// NewMockClientScopeRepository creates a new mock instance.
func NewMockClientScopeRepository(ctrl *gomock.Controller) *MockClientScopeRepository {
	mock := &MockClientScopeRepository{ctrl: ctrl}
	mock.recorder = &MockClientScopeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientScopeRepository) EXPECT() *MockClientScopeRepositoryMockRecorder {
	return m.recorder
}

// CreateClientScope mocks base method.
func (m *MockClientScopeRepository) CreateClientScope(ctx context.Context, scope *domain.ClientScope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClientScope", ctx, scope)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateClientScope indicates an expected call of CreateClientScope.
func (mr *MockClientScopeRepositoryMockRecorder) CreateClientScope(ctx, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClientScope", reflect.TypeOf((*MockClientScopeRepository)(nil).CreateClientScope), ctx, scope)
}

// DeleteClientScope mocks base method.
func (m *MockClientScopeRepository) DeleteClientScope(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClientScope", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClientScope indicates an expected call of DeleteClientScope.
func (mr *MockClientScopeRepositoryMockRecorder) DeleteClientScope(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClientScope", reflect.TypeOf((*MockClientScopeRepository)(nil).DeleteClientScope), ctx, id)
}

// GetClientScopeByID mocks base method.
func (m *MockClientScopeRepository) GetClientScopeByID(ctx context.Context, id string) (*domain.ClientScope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientScopeByID", ctx, id)
	ret0, _ := ret[0].(*domain.ClientScope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientScopeByID indicates an expected call of GetClientScopeByID.
func (mr *MockClientScopeRepositoryMockRecorder) GetClientScopeByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientScopeByID", reflect.TypeOf((*MockClientScopeRepository)(nil).GetClientScopeByID), ctx, id)
}

// UpdateClientScope mocks base method.
func (m *MockClientScopeRepository) UpdateClientScope(ctx context.Context, scope *domain.ClientScope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClientScope", ctx, scope)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClientScope indicates an expected call of UpdateClientScope.
func (mr *MockClientScopeRepositoryMockRecorder) UpdateClientScope(ctx, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClientScope", reflect.TypeOf((*MockClientScopeRepository)(nil).UpdateClientScope), ctx, scope)
}

// MockRealmSettingsRepository is a mock of RealmSettingsRepository interface.
type MockRealmSettingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRealmSettingsRepositoryMockRecorder
	isgomock struct{}
}

// MockRealmSettingsRepositoryMockRecorder is the mock recorder for MockRealmSettingsRepository.
type MockRealmSettingsRepositoryMockRecorder struct {
	mock *MockRealmSettingsRepository
}

// NewMockRealmSettingsRepository creates a new mock instance.
func NewMockRealmSettingsRepository(ctrl *gomock.Controller) *MockRealmSettingsRepository {
	mock := &MockRealmSettingsRepository{ctrl: ctrl}
	mock.recorder = &MockRealmSettingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRealmSettingsRepository) EXPECT() *MockRealmSettingsRepositoryMockRecorder {
	return m.recorder
}

// GetRealmSettings mocks base method.
func (m *MockRealmSettingsRepository) GetRealmSettings(ctx context.Context) (*domain.RealmSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRealmSettings", ctx)
	ret0, _ := ret[0].(*domain.RealmSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRealmSettings indicates an expected call of GetRealmSettings.
func (mr *MockRealmSettingsRepositoryMockRecorder) GetRealmSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRealmSettings", reflect.TypeOf((*MockRealmSettingsRepository)(nil).GetRealmSettings), ctx)
}

// UpdateRealmSettings mocks base method.
func (m *MockRealmSettingsRepository) UpdateRealmSettings(ctx context.Context, settings *domain.RealmSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRealmSettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRealmSettings indicates an expected call of UpdateRealmSettings.
func (mr *MockRealmSettingsRepositoryMockRecorder) UpdateRealmSettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRealmSettings", reflect.TypeOf((*MockRealmSettingsRepository)(nil).UpdateRealmSettings), ctx, settings)
}

// MockRealmKeysRepository is a mock of RealmKeysRepository interface.
type MockRealmKeysRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRealmKeysRepositoryMockRecorder
	isgomock struct{}
}

// MockRealmKeysRepositoryMockRecorder is the mock recorder for MockRealmKeysRepository.
type MockRealmKeysRepositoryMockRecorder struct {
	mock *MockRealmKeysRepository
}

// NewMockRealmKeysRepository creates a new mock instance.
func NewMockRealmKeysRepository(ctrl *gomock.Controller) *MockRealmKeysRepository {
	mock := &MockRealmKeysRepository{ctrl: ctrl}
	mock.recorder = &MockRealmKeysRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRealmKeysRepository) EXPECT() *MockRealmKeysRepositoryMockRecorder {
	return m.recorder
}

// ListAllKeys mocks base method.
func (m *MockRealmKeysRepository) ListAllKeys(ctx context.Context) ([]*domain.RealmKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllKeys", ctx)
	ret0, _ := ret[0].([]*domain.RealmKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllKeys indicates an expected call of ListAllKeys.
func (mr *MockRealmKeysRepositoryMockRecorder) ListAllKeys(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllKeys", reflect.TypeOf((*MockRealmKeysRepository)(nil).ListAllKeys), ctx)
}

// ListClientKeys mocks base method.
func (m *MockRealmKeysRepository) ListClientKeys(ctx context.Context, clientID string) ([]*domain.RealmKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClientKeys", ctx, clientID)
	ret0, _ := ret[0].([]*domain.RealmKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClientKeys indicates an expected call of ListClientKeys.
func (mr *MockRealmKeysRepositoryMockRecorder) ListClientKeys(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClientKeys", reflect.TypeOf((*MockRealmKeysRepository)(nil).ListClientKeys), ctx, clientID)
}

// ListRealmKeys mocks base method.
func (m *MockRealmKeysRepository) ListRealmKeys(ctx context.Context) ([]*domain.RealmKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRealmKeys", ctx)
	ret0, _ := ret[0].([]*domain.RealmKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRealmKeys indicates an expected call of ListRealmKeys.
func (mr *MockRealmKeysRepositoryMockRecorder) ListRealmKeys(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRealmKeys", reflect.TypeOf((*MockRealmKeysRepository)(nil).ListRealmKeys), ctx)
}

// SaveRealmKey mocks base method.
func (m *MockRealmKeysRepository) SaveRealmKey(ctx context.Context, key *domain.RealmKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRealmKey", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRealmKey indicates an expected call of SaveRealmKey.
func (mr *MockRealmKeysRepositoryMockRecorder) SaveRealmKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRealmKey", reflect.TypeOf((*MockRealmKeysRepository)(nil).SaveRealmKey), ctx, key)
}

// UpdateRealmKeyStatus mocks base method.
func (m *MockRealmKeysRepository) UpdateRealmKeyStatus(ctx context.Context, keyID string, status domain.RealmKeyStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRealmKeyStatus", ctx, keyID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRealmKeyStatus indicates an expected call of UpdateRealmKeyStatus.
func (mr *MockRealmKeysRepositoryMockRecorder) UpdateRealmKeyStatus(ctx, keyID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRealmKeyStatus", reflect.TypeOf((*MockRealmKeysRepository)(nil).UpdateRealmKeyStatus), ctx, keyID, status)
}

// UpdateRealmKeys mocks base method.
func (m *MockRealmKeysRepository) UpdateRealmKeys(ctx context.Context, keys []*domain.RealmKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRealmKeys", ctx, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRealmKeys indicates an expected call of UpdateRealmKeys.
func (mr *MockRealmKeysRepositoryMockRecorder) UpdateRealmKeys(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRealmKeys", reflect.TypeOf((*MockRealmKeysRepository)(nil).UpdateRealmKeys), ctx, keys)
}
