// Code generated by MockGen. DO NOT EDIT.
// Source: token_service.go
//
// Generated by this command:
//
//	mockgen -source=token_service.go -destination=mocks/mock_token_service.go -package=mock_domain TokenServiceInterface
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"
	time "time"

	jwt "github.com/golang-jwt/jwt/v5"
	api "github.com/pilab-dev/shadow-sso/api"
	domain "github.com/pilab-dev/shadow-sso/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenServiceInterface is a mock of TokenServiceInterface interface.
type MockTokenServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockTokenServiceInterfaceMockRecorder is the mock recorder for MockTokenServiceInterface.
type MockTokenServiceInterfaceMockRecorder struct {
	mock *MockTokenServiceInterface
}

// NewMockTokenServiceInterface creates a new mock instance.
func NewMockTokenServiceInterface(ctrl *gomock.Controller) *MockTokenServiceInterface {
	mock := &MockTokenServiceInterface{ctrl: ctrl}
	mock.recorder = &MockTokenServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenServiceInterface) EXPECT() *MockTokenServiceInterfaceMockRecorder {
	return m.recorder
}

// BuildToken mocks base method.
func (m *MockTokenServiceInterface) BuildToken(token *domain.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildToken", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuildToken indicates an expected call of BuildToken.
func (mr *MockTokenServiceInterfaceMockRecorder) BuildToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildToken", reflect.TypeOf((*MockTokenServiceInterface)(nil).BuildToken), token)
}

// CreateToken mocks base method.
func (m *MockTokenServiceInterface) CreateToken(ctx context.Context, opts domain.CreateTokenOptions, claims jwt.Claims) (*domain.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", ctx, opts, claims)
	ret0, _ := ret[0].(*domain.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockTokenServiceInterfaceMockRecorder) CreateToken(ctx, opts, claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockTokenServiceInterface)(nil).CreateToken), ctx, opts, claims)
}

// GenerateIDToken mocks base method.
func (m *MockTokenServiceInterface) GenerateIDToken(ctx context.Context, userID, clientID, nonce string, authTime time.Time, scope string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateIDToken", ctx, userID, clientID, nonce, authTime, scope)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateIDToken indicates an expected call of GenerateIDToken.
func (mr *MockTokenServiceInterfaceMockRecorder) GenerateIDToken(ctx, userID, clientID, nonce, authTime, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateIDToken", reflect.TypeOf((*MockTokenServiceInterface)(nil).GenerateIDToken), ctx, userID, clientID, nonce, authTime, scope)
}

// GenerateTokenPair mocks base method.
func (m *MockTokenServiceInterface) GenerateTokenPair(ctx context.Context, clientID, userID, scope string, tokenTTL time.Duration) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokenPair", ctx, clientID, userID, scope, tokenTTL)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTokenPair indicates an expected call of GenerateTokenPair.
func (mr *MockTokenServiceInterfaceMockRecorder) GenerateTokenPair(ctx, clientID, userID, scope, tokenTTL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokenPair", reflect.TypeOf((*MockTokenServiceInterface)(nil).GenerateTokenPair), ctx, clientID, userID, scope, tokenTTL)
}

// GenerateTokenPairWithFamily mocks base method.
func (m *MockTokenServiceInterface) GenerateTokenPairWithFamily(ctx context.Context, clientID, userID, scope string, tokenTTL time.Duration, family, nonce string, authTime time.Time) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokenPairWithFamily", ctx, clientID, userID, scope, tokenTTL, family, nonce, authTime)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTokenPairWithFamily indicates an expected call of GenerateTokenPairWithFamily.
func (mr *MockTokenServiceInterfaceMockRecorder) GenerateTokenPairWithFamily(ctx, clientID, userID, scope, tokenTTL, family, nonce, authTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokenPairWithFamily", reflect.TypeOf((*MockTokenServiceInterface)(nil).GenerateTokenPairWithFamily), ctx, clientID, userID, scope, tokenTTL, family, nonce, authTime)
}

// GetAccessTokenInfo mocks base method.
func (m *MockTokenServiceInterface) GetAccessTokenInfo(ctx context.Context, tokenValue string) (*domain.TokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessTokenInfo", ctx, tokenValue)
	ret0, _ := ret[0].(*domain.TokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessTokenInfo indicates an expected call of GetAccessTokenInfo.
func (mr *MockTokenServiceInterfaceMockRecorder) GetAccessTokenInfo(ctx, tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessTokenInfo", reflect.TypeOf((*MockTokenServiceInterface)(nil).GetAccessTokenInfo), ctx, tokenValue)
}

// GetRefreshTokenInfo mocks base method.
func (m *MockTokenServiceInterface) GetRefreshTokenInfo(ctx context.Context, tokenValue string) (*domain.TokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenInfo", ctx, tokenValue)
	ret0, _ := ret[0].(*domain.TokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenInfo indicates an expected call of GetRefreshTokenInfo.
func (mr *MockTokenServiceInterfaceMockRecorder) GetRefreshTokenInfo(ctx, tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenInfo", reflect.TypeOf((*MockTokenServiceInterface)(nil).GetRefreshTokenInfo), ctx, tokenValue)
}

// RevokeToken mocks base method.
func (m *MockTokenServiceInterface) RevokeToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockTokenServiceInterfaceMockRecorder) RevokeToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockTokenServiceInterface)(nil).RevokeToken), ctx, token)
}

// ValidateAccessToken mocks base method.
func (m *MockTokenServiceInterface) ValidateAccessToken(ctx context.Context, tokenValue string) (*domain.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", ctx, tokenValue)
	ret0, _ := ret[0].(*domain.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockTokenServiceInterfaceMockRecorder) ValidateAccessToken(ctx, tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockTokenServiceInterface)(nil).ValidateAccessToken), ctx, tokenValue)
}

// ValidateIDToken mocks base method.
func (m *MockTokenServiceInterface) ValidateIDToken(ctx context.Context, tokenValue string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateIDToken", ctx, tokenValue)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateIDToken indicates an expected call of ValidateIDToken.
func (mr *MockTokenServiceInterfaceMockRecorder) ValidateIDToken(ctx, tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateIDToken", reflect.TypeOf((*MockTokenServiceInterface)(nil).ValidateIDToken), ctx, tokenValue)
}
