// Code generated by MockGen. DO NOT EDIT.
// Source: oauth_service.go
//
// Generated by this command:
//
//	mockgen -source=oauth_service.go -destination=mocks/mock_oauth_service.go -package=mock_domain OAuthServiceInterface
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"
	time "time"

	api "github.com/pilab-dev/shadow-sso/api"
	domain "github.com/pilab-dev/shadow-sso/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuthServiceInterface is a mock of OAuthServiceInterface interface.
type MockOAuthServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockOAuthServiceInterfaceMockRecorder is the mock recorder for MockOAuthServiceInterface.
type MockOAuthServiceInterfaceMockRecorder struct {
	mock *MockOAuthServiceInterface
}

// NewMockOAuthServiceInterface creates a new mock instance.
func NewMockOAuthServiceInterface(ctrl *gomock.Controller) *MockOAuthServiceInterface {
	mock := &MockOAuthServiceInterface{ctrl: ctrl}
	mock.recorder = &MockOAuthServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthServiceInterface) EXPECT() *MockOAuthServiceInterfaceMockRecorder {
	return m.recorder
}

// ClientCredentials mocks base method.
func (m *MockOAuthServiceInterface) ClientCredentials(ctx context.Context, clientID, clientSecret, scope string) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientCredentials", ctx, clientID, clientSecret, scope)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClientCredentials indicates an expected call of ClientCredentials.
func (mr *MockOAuthServiceInterfaceMockRecorder) ClientCredentials(ctx, clientID, clientSecret, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientCredentials", reflect.TypeOf((*MockOAuthServiceInterface)(nil).ClientCredentials), ctx, clientID, clientSecret, scope)
}

// DirectGrant mocks base method.
func (m *MockOAuthServiceInterface) DirectGrant(ctx context.Context, clientID, clientSecret, username, password, scope string) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DirectGrant", ctx, clientID, clientSecret, username, password, scope)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DirectGrant indicates an expected call of DirectGrant.
func (mr *MockOAuthServiceInterfaceMockRecorder) DirectGrant(ctx, clientID, clientSecret, username, password, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DirectGrant", reflect.TypeOf((*MockOAuthServiceInterface)(nil).DirectGrant), ctx, clientID, clientSecret, username, password, scope)
}

// ExchangeAuthorizationCode mocks base method.
func (m *MockOAuthServiceInterface) ExchangeAuthorizationCode(ctx context.Context, code, clientID, clientSecret, redirectURI string) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeAuthorizationCode", ctx, code, clientID, clientSecret, redirectURI)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeAuthorizationCode indicates an expected call of ExchangeAuthorizationCode.
func (mr *MockOAuthServiceInterfaceMockRecorder) ExchangeAuthorizationCode(ctx, code, clientID, clientSecret, redirectURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeAuthorizationCode", reflect.TypeOf((*MockOAuthServiceInterface)(nil).ExchangeAuthorizationCode), ctx, code, clientID, clientSecret, redirectURI)
}

// GenerateAuthCode mocks base method.
func (m *MockOAuthServiceInterface) GenerateAuthCode(ctx context.Context, clientID, userID, redirectURI, scope, codeChallenge, codeChallengeMethod, nonce string, authTime time.Time) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAuthCode", ctx, clientID, userID, redirectURI, scope, codeChallenge, codeChallengeMethod, nonce, authTime)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAuthCode indicates an expected call of GenerateAuthCode.
func (mr *MockOAuthServiceInterfaceMockRecorder) GenerateAuthCode(ctx, clientID, userID, redirectURI, scope, codeChallenge, codeChallengeMethod, nonce, authTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAuthCode", reflect.TypeOf((*MockOAuthServiceInterface)(nil).GenerateAuthCode), ctx, clientID, userID, redirectURI, scope, codeChallenge, codeChallengeMethod, nonce, authTime)
}

// GetJWKS mocks base method.
func (m *MockOAuthServiceInterface) GetJWKS() *domain.JWKS {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJWKS")
	ret0, _ := ret[0].(*domain.JWKS)
	return ret0
}

// GetJWKS indicates an expected call of GetJWKS.
func (mr *MockOAuthServiceInterfaceMockRecorder) GetJWKS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJWKS", reflect.TypeOf((*MockOAuthServiceInterface)(nil).GetJWKS))
}

// GetUserSessions mocks base method.
func (m *MockOAuthServiceInterface) GetUserSessions(ctx context.Context, userID string) ([]*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSessions", ctx, userID)
	ret0, _ := ret[0].([]*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSessions indicates an expected call of GetUserSessions.
func (mr *MockOAuthServiceInterfaceMockRecorder) GetUserSessions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSessions", reflect.TypeOf((*MockOAuthServiceInterface)(nil).GetUserSessions), ctx, userID)
}

// InitiateDeviceAuthorization mocks base method.
func (m *MockOAuthServiceInterface) InitiateDeviceAuthorization(ctx context.Context, clientID, scope, verificationBaseURI string) (*api.DeviceAuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateDeviceAuthorization", ctx, clientID, scope, verificationBaseURI)
	ret0, _ := ret[0].(*api.DeviceAuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateDeviceAuthorization indicates an expected call of InitiateDeviceAuthorization.
func (mr *MockOAuthServiceInterfaceMockRecorder) InitiateDeviceAuthorization(ctx, clientID, scope, verificationBaseURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateDeviceAuthorization", reflect.TypeOf((*MockOAuthServiceInterface)(nil).InitiateDeviceAuthorization), ctx, clientID, scope, verificationBaseURI)
}

// IntrospectToken mocks base method.
func (m *MockOAuthServiceInterface) IntrospectToken(ctx context.Context, token, tokenTypeHint, clientID, clientSecret string) (*domain.TokenIntrospection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntrospectToken", ctx, token, tokenTypeHint, clientID, clientSecret)
	ret0, _ := ret[0].(*domain.TokenIntrospection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IntrospectToken indicates an expected call of IntrospectToken.
func (mr *MockOAuthServiceInterfaceMockRecorder) IntrospectToken(ctx, token, tokenTypeHint, clientID, clientSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntrospectToken", reflect.TypeOf((*MockOAuthServiceInterface)(nil).IntrospectToken), ctx, token, tokenTypeHint, clientID, clientSecret)
}

// IssueTokenForDeviceFlow mocks base method.
func (m *MockOAuthServiceInterface) IssueTokenForDeviceFlow(ctx context.Context, deviceCode, clientID string) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueTokenForDeviceFlow", ctx, deviceCode, clientID)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueTokenForDeviceFlow indicates an expected call of IssueTokenForDeviceFlow.
func (mr *MockOAuthServiceInterfaceMockRecorder) IssueTokenForDeviceFlow(ctx, deviceCode, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueTokenForDeviceFlow", reflect.TypeOf((*MockOAuthServiceInterface)(nil).IssueTokenForDeviceFlow), ctx, deviceCode, clientID)
}

// Login mocks base method.
func (m *MockOAuthServiceInterface) Login(ctx context.Context, username, password, deviceInfo string) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, username, password, deviceInfo)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockOAuthServiceInterfaceMockRecorder) Login(ctx, username, password, deviceInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockOAuthServiceInterface)(nil).Login), ctx, username, password, deviceInfo)
}

// PasswordGrant mocks base method.
func (m *MockOAuthServiceInterface) PasswordGrant(ctx context.Context, username, password, scope string, cli *domain.Client) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasswordGrant", ctx, username, password, scope, cli)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PasswordGrant indicates an expected call of PasswordGrant.
func (mr *MockOAuthServiceInterfaceMockRecorder) PasswordGrant(ctx, username, password, scope, cli any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordGrant", reflect.TypeOf((*MockOAuthServiceInterface)(nil).PasswordGrant), ctx, username, password, scope, cli)
}

// RefreshToken mocks base method.
func (m *MockOAuthServiceInterface) RefreshToken(ctx context.Context, refreshTokenValue, clientID string) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, refreshTokenValue, clientID)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockOAuthServiceInterfaceMockRecorder) RefreshToken(ctx, refreshTokenValue, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockOAuthServiceInterface)(nil).RefreshToken), ctx, refreshTokenValue, clientID)
}

// RegisterUser mocks base method.
func (m *MockOAuthServiceInterface) RegisterUser(ctx context.Context, username, password string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, username, password)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockOAuthServiceInterfaceMockRecorder) RegisterUser(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockOAuthServiceInterface)(nil).RegisterUser), ctx, username, password)
}

// RevokeToken mocks base method.
func (m *MockOAuthServiceInterface) RevokeToken(ctx context.Context, tokenToRevoke, tokenTypeHint, clientID, clientSecret string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, tokenToRevoke, tokenTypeHint, clientID, clientSecret)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockOAuthServiceInterfaceMockRecorder) RevokeToken(ctx, tokenToRevoke, tokenTypeHint, clientID, clientSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockOAuthServiceInterface)(nil).RevokeToken), ctx, tokenToRevoke, tokenTypeHint, clientID, clientSecret)
}

// TokenExchange mocks base method.
func (m *MockOAuthServiceInterface) TokenExchange(ctx context.Context, subjectToken, subjectTokenType, requestedTokenType, resource, scope, clientID string) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenExchange", ctx, subjectToken, subjectTokenType, requestedTokenType, resource, scope, clientID)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokenExchange indicates an expected call of TokenExchange.
func (mr *MockOAuthServiceInterfaceMockRecorder) TokenExchange(ctx, subjectToken, subjectTokenType, requestedTokenType, resource, scope, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenExchange", reflect.TypeOf((*MockOAuthServiceInterface)(nil).TokenExchange), ctx, subjectToken, subjectTokenType, requestedTokenType, resource, scope, clientID)
}

// ValidateClient mocks base method.
func (m *MockOAuthServiceInterface) ValidateClient(ctx context.Context, clientID, clientSecret string) (*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateClient", ctx, clientID, clientSecret)
	ret0, _ := ret[0].(*domain.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateClient indicates an expected call of ValidateClient.
func (mr *MockOAuthServiceInterfaceMockRecorder) ValidateClient(ctx, clientID, clientSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateClient", reflect.TypeOf((*MockOAuthServiceInterface)(nil).ValidateClient), ctx, clientID, clientSecret)
}

// VerifyUserCode mocks base method.
func (m *MockOAuthServiceInterface) VerifyUserCode(ctx context.Context, userCode, userID string) (*domain.DeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUserCode", ctx, userCode, userID)
	ret0, _ := ret[0].(*domain.DeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyUserCode indicates an expected call of VerifyUserCode.
func (mr *MockOAuthServiceInterfaceMockRecorder) VerifyUserCode(ctx, userCode, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUserCode", reflect.TypeOf((*MockOAuthServiceInterface)(nil).VerifyUserCode), ctx, userCode, userID)
}
