// Code generated by MockGen. DO NOT EDIT.
// Source: user_attribute.go
//
// Generated by this command:
//
//	mockgen -source=user_attribute.go -destination=mocks/mock_user_attribute_repository.go -package=mock_domain -exclude_interfaces=UserAttributeMapperRepository UserAttributeRepository
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	domain "github.com/pilab-dev/shadow-sso/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserAttributeRepository is a mock of UserAttributeRepository interface.
type MockUserAttributeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserAttributeRepositoryMockRecorder
	isgomock struct{}
}

// MockUserAttributeRepositoryMockRecorder is the mock recorder for MockUserAttributeRepository.
type MockUserAttributeRepositoryMockRecorder struct {
	mock *MockUserAttributeRepository
}

// NewMockUserAttributeRepository creates a new mock instance.
func NewMockUserAttributeRepository(ctrl *gomock.Controller) *MockUserAttributeRepository {
	mock := &MockUserAttributeRepository{ctrl: ctrl}
	mock.recorder = &MockUserAttributeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAttributeRepository) EXPECT() *MockUserAttributeRepositoryMockRecorder {
	return m.recorder
}

// CreateAttribute mocks base method.
func (m *MockUserAttributeRepository) CreateAttribute(ctx context.Context, attr *domain.UserAttribute) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttribute", ctx, attr)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAttribute indicates an expected call of CreateAttribute.
func (mr *MockUserAttributeRepositoryMockRecorder) CreateAttribute(ctx, attr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttribute", reflect.TypeOf((*MockUserAttributeRepository)(nil).CreateAttribute), ctx, attr)
}

// DeleteAttribute mocks base method.
func (m *MockUserAttributeRepository) DeleteAttribute(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttribute", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttribute indicates an expected call of DeleteAttribute.
func (mr *MockUserAttributeRepositoryMockRecorder) DeleteAttribute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttribute", reflect.TypeOf((*MockUserAttributeRepository)(nil).DeleteAttribute), ctx, id)
}

// DeleteAttributesByUserID mocks base method.
func (m *MockUserAttributeRepository) DeleteAttributesByUserID(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttributesByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttributesByUserID indicates an expected call of DeleteAttributesByUserID.
func (mr *MockUserAttributeRepositoryMockRecorder) DeleteAttributesByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttributesByUserID", reflect.TypeOf((*MockUserAttributeRepository)(nil).DeleteAttributesByUserID), ctx, userID)
}

// GetAttributeByID mocks base method.
func (m *MockUserAttributeRepository) GetAttributeByID(ctx context.Context, id string) (*domain.UserAttribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttributeByID", ctx, id)
	ret0, _ := ret[0].(*domain.UserAttribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttributeByID indicates an expected call of GetAttributeByID.
func (mr *MockUserAttributeRepositoryMockRecorder) GetAttributeByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttributeByID", reflect.TypeOf((*MockUserAttributeRepository)(nil).GetAttributeByID), ctx, id)
}

// GetAttributesByUserID mocks base method.
func (m *MockUserAttributeRepository) GetAttributesByUserID(ctx context.Context, userID string) ([]*domain.UserAttribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttributesByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain.UserAttribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttributesByUserID indicates an expected call of GetAttributesByUserID.
func (mr *MockUserAttributeRepositoryMockRecorder) GetAttributesByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttributesByUserID", reflect.TypeOf((*MockUserAttributeRepository)(nil).GetAttributesByUserID), ctx, userID)
}

// ListAllAttributes mocks base method.
func (m *MockUserAttributeRepository) ListAllAttributes(ctx context.Context) ([]*domain.UserAttribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllAttributes", ctx)
	ret0, _ := ret[0].([]*domain.UserAttribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllAttributes indicates an expected call of ListAllAttributes.
func (mr *MockUserAttributeRepositoryMockRecorder) ListAllAttributes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllAttributes", reflect.TypeOf((*MockUserAttributeRepository)(nil).ListAllAttributes), ctx)
}

// UpdateAttribute mocks base method.
func (m *MockUserAttributeRepository) UpdateAttribute(ctx context.Context, attr *domain.UserAttribute) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAttribute", ctx, attr)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAttribute indicates an expected call of UpdateAttribute.
func (mr *MockUserAttributeRepositoryMockRecorder) UpdateAttribute(ctx, attr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAttribute", reflect.TypeOf((*MockUserAttributeRepository)(nil).UpdateAttribute), ctx, attr)
}
