// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=mocks/mock_repositories.go -package=mock_domain PublicKeyRepository,ServiceAccountRepository,UserRepository,SessionRepository,TokenRepository,AuthorizationCodeRepository,PkceRepository,DeviceAuthorizationRepository,ClientRepository,IdPRepository,UserFederatedIdentityRepository,ConfigurationRepository
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/pilab-dev/shadow-sso/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPasswordHasher is a mock of PasswordHasher interface.
type MockPasswordHasher struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordHasherMockRecorder
	isgomock struct{}
}

// MockPasswordHasherMockRecorder is the mock recorder for MockPasswordHasher.
type MockPasswordHasherMockRecorder struct {
	mock *MockPasswordHasher
}

// NewMockPasswordHasher creates a new mock instance.
func NewMockPasswordHasher(ctrl *gomock.Controller) *MockPasswordHasher {
	mock := &MockPasswordHasher{ctrl: ctrl}
	mock.recorder = &MockPasswordHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordHasher) EXPECT() *MockPasswordHasherMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockPasswordHasher) Hash(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockPasswordHasherMockRecorder) Hash(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockPasswordHasher)(nil).Hash), password)
}

// Verify mocks base method.
func (m *MockPasswordHasher) Verify(hashedPassword, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", hashedPassword, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockPasswordHasherMockRecorder) Verify(hashedPassword, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockPasswordHasher)(nil).Verify), hashedPassword, password)
}

// MockFlowStore is a mock of FlowStore interface.
type MockFlowStore struct {
	ctrl     *gomock.Controller
	recorder *MockFlowStoreMockRecorder
	isgomock struct{}
}

// MockFlowStoreMockRecorder is the mock recorder for MockFlowStore.
type MockFlowStoreMockRecorder struct {
	mock *MockFlowStore
}

// NewMockFlowStore creates a new mock instance.
func NewMockFlowStore(ctrl *gomock.Controller) *MockFlowStore {
	mock := &MockFlowStore{ctrl: ctrl}
	mock.recorder = &MockFlowStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowStore) EXPECT() *MockFlowStoreMockRecorder {
	return m.recorder
}

// CleanupExpiredFlows mocks base method.
func (m *MockFlowStore) CleanupExpiredFlows() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CleanupExpiredFlows")
}

// CleanupExpiredFlows indicates an expected call of CleanupExpiredFlows.
func (mr *MockFlowStoreMockRecorder) CleanupExpiredFlows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredFlows", reflect.TypeOf((*MockFlowStore)(nil).CleanupExpiredFlows))
}

// DeleteFlow mocks base method.
func (m *MockFlowStore) DeleteFlow(flowID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFlow", flowID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFlow indicates an expected call of DeleteFlow.
func (mr *MockFlowStoreMockRecorder) DeleteFlow(flowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFlow", reflect.TypeOf((*MockFlowStore)(nil).DeleteFlow), flowID)
}

// GetFlow mocks base method.
func (m *MockFlowStore) GetFlow(flowID string) (*domain.LoginFlowState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlow", flowID)
	ret0, _ := ret[0].(*domain.LoginFlowState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlow indicates an expected call of GetFlow.
func (mr *MockFlowStoreMockRecorder) GetFlow(flowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlow", reflect.TypeOf((*MockFlowStore)(nil).GetFlow), flowID)
}

// StoreFlow mocks base method.
func (m *MockFlowStore) StoreFlow(flowID string, state domain.LoginFlowState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreFlow", flowID, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreFlow indicates an expected call of StoreFlow.
func (mr *MockFlowStoreMockRecorder) StoreFlow(flowID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreFlow", reflect.TypeOf((*MockFlowStore)(nil).StoreFlow), flowID, state)
}

// UpdateFlow mocks base method.
func (m *MockFlowStore) UpdateFlow(flowID string, state *domain.LoginFlowState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFlow", flowID, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFlow indicates an expected call of UpdateFlow.
func (mr *MockFlowStoreMockRecorder) UpdateFlow(flowID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFlow", reflect.TypeOf((*MockFlowStore)(nil).UpdateFlow), flowID, state)
}

// MockUserSessionStore is a mock of UserSessionStore interface.
type MockUserSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserSessionStoreMockRecorder
	isgomock struct{}
}

// MockUserSessionStoreMockRecorder is the mock recorder for MockUserSessionStore.
type MockUserSessionStoreMockRecorder struct {
	mock *MockUserSessionStore
}

// NewMockUserSessionStore creates a new mock instance.
func NewMockUserSessionStore(ctrl *gomock.Controller) *MockUserSessionStore {
	mock := &MockUserSessionStore{ctrl: ctrl}
	mock.recorder = &MockUserSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSessionStore) EXPECT() *MockUserSessionStoreMockRecorder {
	return m.recorder
}

// CleanupExpiredSessions mocks base method.
func (m *MockUserSessionStore) CleanupExpiredSessions() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CleanupExpiredSessions")
}

// CleanupExpiredSessions indicates an expected call of CleanupExpiredSessions.
func (mr *MockUserSessionStoreMockRecorder) CleanupExpiredSessions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredSessions", reflect.TypeOf((*MockUserSessionStore)(nil).CleanupExpiredSessions))
}

// DeleteUserSession mocks base method.
func (m *MockUserSessionStore) DeleteUserSession(sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserSession", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserSession indicates an expected call of DeleteUserSession.
func (mr *MockUserSessionStoreMockRecorder) DeleteUserSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserSession", reflect.TypeOf((*MockUserSessionStore)(nil).DeleteUserSession), sessionID)
}

// GetUserSession mocks base method.
func (m *MockUserSessionStore) GetUserSession(sessionID string) (*domain.UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSession", sessionID)
	ret0, _ := ret[0].(*domain.UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSession indicates an expected call of GetUserSession.
func (mr *MockUserSessionStoreMockRecorder) GetUserSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSession", reflect.TypeOf((*MockUserSessionStore)(nil).GetUserSession), sessionID)
}

// StoreUserSession mocks base method.
func (m *MockUserSessionStore) StoreUserSession(session *domain.UserSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreUserSession", session)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreUserSession indicates an expected call of StoreUserSession.
func (mr *MockUserSessionStoreMockRecorder) StoreUserSession(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreUserSession", reflect.TypeOf((*MockUserSessionStore)(nil).StoreUserSession), session)
}

// MockPublicKeyRepository is a mock of PublicKeyRepository interface.
type MockPublicKeyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPublicKeyRepositoryMockRecorder
	isgomock struct{}
}

// MockPublicKeyRepositoryMockRecorder is the mock recorder for MockPublicKeyRepository.
type MockPublicKeyRepositoryMockRecorder struct {
	mock *MockPublicKeyRepository
}

// NewMockPublicKeyRepository creates a new mock instance.
func NewMockPublicKeyRepository(ctrl *gomock.Controller) *MockPublicKeyRepository {
	mock := &MockPublicKeyRepository{ctrl: ctrl}
	mock.recorder = &MockPublicKeyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublicKeyRepository) EXPECT() *MockPublicKeyRepositoryMockRecorder {
	return m.recorder
}

// CreatePublicKey mocks base method.
func (m *MockPublicKeyRepository) CreatePublicKey(ctx context.Context, pubKeyInfo *domain.PublicKeyInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePublicKey", ctx, pubKeyInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePublicKey indicates an expected call of CreatePublicKey.
func (mr *MockPublicKeyRepositoryMockRecorder) CreatePublicKey(ctx, pubKeyInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePublicKey", reflect.TypeOf((*MockPublicKeyRepository)(nil).CreatePublicKey), ctx, pubKeyInfo)
}

// GetPublicKey mocks base method.
func (m *MockPublicKeyRepository) GetPublicKey(ctx context.Context, keyID string) (*domain.PublicKeyInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicKey", ctx, keyID)
	ret0, _ := ret[0].(*domain.PublicKeyInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicKey indicates an expected call of GetPublicKey.
func (mr *MockPublicKeyRepositoryMockRecorder) GetPublicKey(ctx, keyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKey", reflect.TypeOf((*MockPublicKeyRepository)(nil).GetPublicKey), ctx, keyID)
}

// ListPublicKeysForServiceAccount mocks base method.
func (m *MockPublicKeyRepository) ListPublicKeysForServiceAccount(ctx context.Context, serviceAccountID string, onlyActive bool) ([]*domain.PublicKeyInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublicKeysForServiceAccount", ctx, serviceAccountID, onlyActive)
	ret0, _ := ret[0].([]*domain.PublicKeyInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublicKeysForServiceAccount indicates an expected call of ListPublicKeysForServiceAccount.
func (mr *MockPublicKeyRepositoryMockRecorder) ListPublicKeysForServiceAccount(ctx, serviceAccountID, onlyActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublicKeysForServiceAccount", reflect.TypeOf((*MockPublicKeyRepository)(nil).ListPublicKeysForServiceAccount), ctx, serviceAccountID, onlyActive)
}

// UpdatePublicKeyStatus mocks base method.
func (m *MockPublicKeyRepository) UpdatePublicKeyStatus(ctx context.Context, keyID, newStatus string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePublicKeyStatus", ctx, keyID, newStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePublicKeyStatus indicates an expected call of UpdatePublicKeyStatus.
func (mr *MockPublicKeyRepositoryMockRecorder) UpdatePublicKeyStatus(ctx, keyID, newStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePublicKeyStatus", reflect.TypeOf((*MockPublicKeyRepository)(nil).UpdatePublicKeyStatus), ctx, keyID, newStatus)
}

// MockSMSService is a mock of SMSService interface.
type MockSMSService struct {
	ctrl     *gomock.Controller
	recorder *MockSMSServiceMockRecorder
	isgomock struct{}
}

// MockSMSServiceMockRecorder is the mock recorder for MockSMSService.
type MockSMSServiceMockRecorder struct {
	mock *MockSMSService
}

// NewMockSMSService creates a new mock instance.
func NewMockSMSService(ctrl *gomock.Controller) *MockSMSService {
	mock := &MockSMSService{ctrl: ctrl}
	mock.recorder = &MockSMSServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSMSService) EXPECT() *MockSMSServiceMockRecorder {
	return m.recorder
}

// SendOTP mocks base method.
func (m *MockSMSService) SendOTP(phoneNumber, otp string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendOTP", phoneNumber, otp)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendOTP indicates an expected call of SendOTP.
func (mr *MockSMSServiceMockRecorder) SendOTP(phoneNumber, otp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendOTP", reflect.TypeOf((*MockSMSService)(nil).SendOTP), phoneNumber, otp)
}

// MockEmailService is a mock of EmailService interface.
type MockEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailServiceMockRecorder
	isgomock struct{}
}

// MockEmailServiceMockRecorder is the mock recorder for MockEmailService.
type MockEmailServiceMockRecorder struct {
	mock *MockEmailService
}

// NewMockEmailService creates a new mock instance.
func NewMockEmailService(ctrl *gomock.Controller) *MockEmailService {
	mock := &MockEmailService{ctrl: ctrl}
	mock.recorder = &MockEmailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailService) EXPECT() *MockEmailServiceMockRecorder {
	return m.recorder
}

// SendMFAEmail mocks base method.
func (m *MockEmailService) SendMFAEmail(to, name, otp, method string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMFAEmail", to, name, otp, method)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMFAEmail indicates an expected call of SendMFAEmail.
func (mr *MockEmailServiceMockRecorder) SendMFAEmail(to, name, otp, method any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMFAEmail", reflect.TypeOf((*MockEmailService)(nil).SendMFAEmail), to, name, otp, method)
}

// SendOTPEmail mocks base method.
func (m *MockEmailService) SendOTPEmail(to, otp string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendOTPEmail", to, otp)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendOTPEmail indicates an expected call of SendOTPEmail.
func (mr *MockEmailServiceMockRecorder) SendOTPEmail(to, otp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendOTPEmail", reflect.TypeOf((*MockEmailService)(nil).SendOTPEmail), to, otp)
}

// SendPasswordResetEmail mocks base method.
func (m *MockEmailService) SendPasswordResetEmail(to, name, resetLink string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPasswordResetEmail", to, name, resetLink)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPasswordResetEmail indicates an expected call of SendPasswordResetEmail.
func (mr *MockEmailServiceMockRecorder) SendPasswordResetEmail(to, name, resetLink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordResetEmail", reflect.TypeOf((*MockEmailService)(nil).SendPasswordResetEmail), to, name, resetLink)
}

// SendVerificationEmail mocks base method.
func (m *MockEmailService) SendVerificationEmail(to, name, verificationLink string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationEmail", to, name, verificationLink)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendVerificationEmail indicates an expected call of SendVerificationEmail.
func (mr *MockEmailServiceMockRecorder) SendVerificationEmail(to, name, verificationLink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationEmail", reflect.TypeOf((*MockEmailService)(nil).SendVerificationEmail), to, name, verificationLink)
}

// MockPushNotificationService is a mock of PushNotificationService interface.
type MockPushNotificationService struct {
	ctrl     *gomock.Controller
	recorder *MockPushNotificationServiceMockRecorder
	isgomock struct{}
}

// MockPushNotificationServiceMockRecorder is the mock recorder for MockPushNotificationService.
type MockPushNotificationServiceMockRecorder struct {
	mock *MockPushNotificationService
}

// NewMockPushNotificationService creates a new mock instance.
func NewMockPushNotificationService(ctrl *gomock.Controller) *MockPushNotificationService {
	mock := &MockPushNotificationService{ctrl: ctrl}
	mock.recorder = &MockPushNotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushNotificationService) EXPECT() *MockPushNotificationServiceMockRecorder {
	return m.recorder
}

// SendMFAPushChallenge mocks base method.
func (m *MockPushNotificationService) SendMFAPushChallenge(deviceToken, challengeID, ipAddress, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMFAPushChallenge", deviceToken, challengeID, ipAddress, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMFAPushChallenge indicates an expected call of SendMFAPushChallenge.
func (mr *MockPushNotificationServiceMockRecorder) SendMFAPushChallenge(deviceToken, challengeID, ipAddress, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMFAPushChallenge", reflect.TypeOf((*MockPushNotificationService)(nil).SendMFAPushChallenge), deviceToken, challengeID, ipAddress, userAgent)
}

// SendPushNotification mocks base method.
func (m *MockPushNotificationService) SendPushNotification(deviceToken, title, body string, data map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPushNotification", deviceToken, title, body, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPushNotification indicates an expected call of SendPushNotification.
func (mr *MockPushNotificationServiceMockRecorder) SendPushNotification(deviceToken, title, body, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPushNotification", reflect.TypeOf((*MockPushNotificationService)(nil).SendPushNotification), deviceToken, title, body, data)
}

// SendPushNotificationToUser mocks base method.
func (m *MockPushNotificationService) SendPushNotificationToUser(userID, title, body string, data map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPushNotificationToUser", userID, title, body, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPushNotificationToUser indicates an expected call of SendPushNotificationToUser.
func (mr *MockPushNotificationServiceMockRecorder) SendPushNotificationToUser(userID, title, body, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPushNotificationToUser", reflect.TypeOf((*MockPushNotificationService)(nil).SendPushNotificationToUser), userID, title, body, data)
}

// MockServiceAccountRepository is a mock of ServiceAccountRepository interface.
type MockServiceAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockServiceAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockServiceAccountRepositoryMockRecorder is the mock recorder for MockServiceAccountRepository.
type MockServiceAccountRepositoryMockRecorder struct {
	mock *MockServiceAccountRepository
}

// NewMockServiceAccountRepository creates a new mock instance.
func NewMockServiceAccountRepository(ctrl *gomock.Controller) *MockServiceAccountRepository {
	mock := &MockServiceAccountRepository{ctrl: ctrl}
	mock.recorder = &MockServiceAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceAccountRepository) EXPECT() *MockServiceAccountRepositoryMockRecorder {
	return m.recorder
}

// CreateServiceAccount mocks base method.
func (m *MockServiceAccountRepository) CreateServiceAccount(ctx context.Context, sa *domain.ServiceAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServiceAccount", ctx, sa)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateServiceAccount indicates an expected call of CreateServiceAccount.
func (mr *MockServiceAccountRepositoryMockRecorder) CreateServiceAccount(ctx, sa any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServiceAccount", reflect.TypeOf((*MockServiceAccountRepository)(nil).CreateServiceAccount), ctx, sa)
}

// DeleteServiceAccount mocks base method.
func (m *MockServiceAccountRepository) DeleteServiceAccount(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceAccount", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceAccount indicates an expected call of DeleteServiceAccount.
func (mr *MockServiceAccountRepositoryMockRecorder) DeleteServiceAccount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceAccount", reflect.TypeOf((*MockServiceAccountRepository)(nil).DeleteServiceAccount), ctx, id)
}

// GetServiceAccount mocks base method.
func (m *MockServiceAccountRepository) GetServiceAccount(ctx context.Context, id string) (*domain.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceAccount", ctx, id)
	ret0, _ := ret[0].(*domain.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceAccount indicates an expected call of GetServiceAccount.
func (mr *MockServiceAccountRepositoryMockRecorder) GetServiceAccount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceAccount", reflect.TypeOf((*MockServiceAccountRepository)(nil).GetServiceAccount), ctx, id)
}

// GetServiceAccountByClientEmail mocks base method.
func (m *MockServiceAccountRepository) GetServiceAccountByClientEmail(ctx context.Context, clientEmail string) (*domain.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceAccountByClientEmail", ctx, clientEmail)
	ret0, _ := ret[0].(*domain.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceAccountByClientEmail indicates an expected call of GetServiceAccountByClientEmail.
func (mr *MockServiceAccountRepositoryMockRecorder) GetServiceAccountByClientEmail(ctx, clientEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceAccountByClientEmail", reflect.TypeOf((*MockServiceAccountRepository)(nil).GetServiceAccountByClientEmail), ctx, clientEmail)
}

// UpdateServiceAccount mocks base method.
func (m *MockServiceAccountRepository) UpdateServiceAccount(ctx context.Context, sa *domain.ServiceAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceAccount", ctx, sa)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServiceAccount indicates an expected call of UpdateServiceAccount.
func (mr *MockServiceAccountRepositoryMockRecorder) UpdateServiceAccount(ctx, sa any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceAccount", reflect.TypeOf((*MockServiceAccountRepository)(nil).UpdateServiceAccount), ctx, sa)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// AddMfaMethod mocks base method.
func (m *MockUserRepository) AddMfaMethod(ctx context.Context, userID string, method *domain.MfaMethod) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMfaMethod", ctx, userID, method)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMfaMethod indicates an expected call of AddMfaMethod.
func (mr *MockUserRepositoryMockRecorder) AddMfaMethod(ctx, userID, method any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMfaMethod", reflect.TypeOf((*MockUserRepository)(nil).AddMfaMethod), ctx, userID, method)
}

// AddWebAuthnDevice mocks base method.
func (m *MockUserRepository) AddWebAuthnDevice(ctx context.Context, userID string, device *domain.WebAuthnDevice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWebAuthnDevice", ctx, userID, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddWebAuthnDevice indicates an expected call of AddWebAuthnDevice.
func (mr *MockUserRepositoryMockRecorder) AddWebAuthnDevice(ctx, userID, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWebAuthnDevice", reflect.TypeOf((*MockUserRepository)(nil).AddWebAuthnDevice), ctx, userID, device)
}

// ClearEmailMFAOtp mocks base method.
func (m *MockUserRepository) ClearEmailMFAOtp(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearEmailMFAOtp", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearEmailMFAOtp indicates an expected call of ClearEmailMFAOtp.
func (mr *MockUserRepositoryMockRecorder) ClearEmailMFAOtp(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearEmailMFAOtp", reflect.TypeOf((*MockUserRepository)(nil).ClearEmailMFAOtp), ctx, userID)
}

// ClearEmailVerificationToken mocks base method.
func (m *MockUserRepository) ClearEmailVerificationToken(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearEmailVerificationToken", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearEmailVerificationToken indicates an expected call of ClearEmailVerificationToken.
func (mr *MockUserRepositoryMockRecorder) ClearEmailVerificationToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearEmailVerificationToken", reflect.TypeOf((*MockUserRepository)(nil).ClearEmailVerificationToken), ctx, userID)
}

// ClearLoginOtp mocks base method.
func (m *MockUserRepository) ClearLoginOtp(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearLoginOtp", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearLoginOtp indicates an expected call of ClearLoginOtp.
func (mr *MockUserRepositoryMockRecorder) ClearLoginOtp(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearLoginOtp", reflect.TypeOf((*MockUserRepository)(nil).ClearLoginOtp), ctx, userID)
}

// ClearPasswordResetToken mocks base method.
func (m *MockUserRepository) ClearPasswordResetToken(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearPasswordResetToken", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearPasswordResetToken indicates an expected call of ClearPasswordResetToken.
func (mr *MockUserRepositoryMockRecorder) ClearPasswordResetToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearPasswordResetToken", reflect.TypeOf((*MockUserRepository)(nil).ClearPasswordResetToken), ctx, userID)
}

// ClearPhoneVerificationOtp mocks base method.
func (m *MockUserRepository) ClearPhoneVerificationOtp(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearPhoneVerificationOtp", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearPhoneVerificationOtp indicates an expected call of ClearPhoneVerificationOtp.
func (mr *MockUserRepositoryMockRecorder) ClearPhoneVerificationOtp(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearPhoneVerificationOtp", reflect.TypeOf((*MockUserRepository)(nil).ClearPhoneVerificationOtp), ctx, userID)
}

// CountUsers mocks base method.
func (m *MockUserRepository) CountUsers(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockUserRepositoryMockRecorder) CountUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockUserRepository)(nil).CountUsers), ctx)
}

// CountUsersByRole mocks base method.
func (m *MockUserRepository) CountUsersByRole(ctx context.Context, role string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsersByRole", ctx, role)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsersByRole indicates an expected call of CountUsersByRole.
func (mr *MockUserRepositoryMockRecorder) CountUsersByRole(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsersByRole", reflect.TypeOf((*MockUserRepository)(nil).CountUsersByRole), ctx, role)
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), ctx, user)
}

// DeleteUser mocks base method.
func (m *MockUserRepository) DeleteUser(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserRepositoryMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserRepository)(nil).DeleteUser), ctx, id)
}

// DisableEmailMFA mocks base method.
func (m *MockUserRepository) DisableEmailMFA(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableEmailMFA", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableEmailMFA indicates an expected call of DisableEmailMFA.
func (mr *MockUserRepositoryMockRecorder) DisableEmailMFA(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableEmailMFA", reflect.TypeOf((*MockUserRepository)(nil).DisableEmailMFA), ctx, userID)
}

// DisablePushMFA mocks base method.
func (m *MockUserRepository) DisablePushMFA(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisablePushMFA", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisablePushMFA indicates an expected call of DisablePushMFA.
func (mr *MockUserRepositoryMockRecorder) DisablePushMFA(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisablePushMFA", reflect.TypeOf((*MockUserRepository)(nil).DisablePushMFA), ctx, userID)
}

// EnableEmailMFA mocks base method.
func (m *MockUserRepository) EnableEmailMFA(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableEmailMFA", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableEmailMFA indicates an expected call of EnableEmailMFA.
func (mr *MockUserRepositoryMockRecorder) EnableEmailMFA(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableEmailMFA", reflect.TypeOf((*MockUserRepository)(nil).EnableEmailMFA), ctx, userID)
}

// EnablePushMFA mocks base method.
func (m *MockUserRepository) EnablePushMFA(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnablePushMFA", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnablePushMFA indicates an expected call of EnablePushMFA.
func (mr *MockUserRepositoryMockRecorder) EnablePushMFA(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnablePushMFA", reflect.TypeOf((*MockUserRepository)(nil).EnablePushMFA), ctx, userID)
}

// GetMfaMethod mocks base method.
func (m *MockUserRepository) GetMfaMethod(ctx context.Context, userID, methodID string) (*domain.MfaMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMfaMethod", ctx, userID, methodID)
	ret0, _ := ret[0].(*domain.MfaMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMfaMethod indicates an expected call of GetMfaMethod.
func (mr *MockUserRepositoryMockRecorder) GetMfaMethod(ctx, userID, methodID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMfaMethod", reflect.TypeOf((*MockUserRepository)(nil).GetMfaMethod), ctx, userID, methodID)
}

// GetUserByEmail mocks base method.
func (m *MockUserRepository) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetUserByEmail), ctx, email)
}

// GetUserByEmailVerificationToken mocks base method.
func (m *MockUserRepository) GetUserByEmailVerificationToken(ctx context.Context, token string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmailVerificationToken", ctx, token)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmailVerificationToken indicates an expected call of GetUserByEmailVerificationToken.
func (mr *MockUserRepositoryMockRecorder) GetUserByEmailVerificationToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmailVerificationToken", reflect.TypeOf((*MockUserRepository)(nil).GetUserByEmailVerificationToken), ctx, token)
}

// GetUserByID mocks base method.
func (m *MockUserRepository) GetUserByID(ctx context.Context, id string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByID), ctx, id)
}

// GetUserByPasswordResetToken mocks base method.
func (m *MockUserRepository) GetUserByPasswordResetToken(ctx context.Context, token string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByPasswordResetToken", ctx, token)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByPasswordResetToken indicates an expected call of GetUserByPasswordResetToken.
func (mr *MockUserRepositoryMockRecorder) GetUserByPasswordResetToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByPasswordResetToken", reflect.TypeOf((*MockUserRepository)(nil).GetUserByPasswordResetToken), ctx, token)
}

// GetWebAuthnDevice mocks base method.
func (m *MockUserRepository) GetWebAuthnDevice(ctx context.Context, userID, deviceID string) (*domain.WebAuthnDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebAuthnDevice", ctx, userID, deviceID)
	ret0, _ := ret[0].(*domain.WebAuthnDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebAuthnDevice indicates an expected call of GetWebAuthnDevice.
func (mr *MockUserRepositoryMockRecorder) GetWebAuthnDevice(ctx, userID, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebAuthnDevice", reflect.TypeOf((*MockUserRepository)(nil).GetWebAuthnDevice), ctx, userID, deviceID)
}

// IncrementFailedLoginAttempts mocks base method.
func (m *MockUserRepository) IncrementFailedLoginAttempts(ctx context.Context, userID string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementFailedLoginAttempts", ctx, userID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementFailedLoginAttempts indicates an expected call of IncrementFailedLoginAttempts.
func (mr *MockUserRepositoryMockRecorder) IncrementFailedLoginAttempts(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementFailedLoginAttempts", reflect.TypeOf((*MockUserRepository)(nil).IncrementFailedLoginAttempts), ctx, userID)
}

// ListMfaMethods mocks base method.
func (m *MockUserRepository) ListMfaMethods(ctx context.Context, userID string) ([]domain.MfaMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMfaMethods", ctx, userID)
	ret0, _ := ret[0].([]domain.MfaMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMfaMethods indicates an expected call of ListMfaMethods.
func (mr *MockUserRepositoryMockRecorder) ListMfaMethods(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMfaMethods", reflect.TypeOf((*MockUserRepository)(nil).ListMfaMethods), ctx, userID)
}

// ListUsers mocks base method.
func (m *MockUserRepository) ListUsers(ctx context.Context, pageToken string, pageSize int) ([]*domain.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, pageToken, pageSize)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUserRepositoryMockRecorder) ListUsers(ctx, pageToken, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUserRepository)(nil).ListUsers), ctx, pageToken, pageSize)
}

// ListWebAuthnDevices mocks base method.
func (m *MockUserRepository) ListWebAuthnDevices(ctx context.Context, userID string) ([]domain.WebAuthnDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWebAuthnDevices", ctx, userID)
	ret0, _ := ret[0].([]domain.WebAuthnDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWebAuthnDevices indicates an expected call of ListWebAuthnDevices.
func (mr *MockUserRepositoryMockRecorder) ListWebAuthnDevices(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWebAuthnDevices", reflect.TypeOf((*MockUserRepository)(nil).ListWebAuthnDevices), ctx, userID)
}

// RegisterPushMFADevice mocks base method.
func (m *MockUserRepository) RegisterPushMFADevice(ctx context.Context, userID, deviceToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterPushMFADevice", ctx, userID, deviceToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterPushMFADevice indicates an expected call of RegisterPushMFADevice.
func (mr *MockUserRepositoryMockRecorder) RegisterPushMFADevice(ctx, userID, deviceToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterPushMFADevice", reflect.TypeOf((*MockUserRepository)(nil).RegisterPushMFADevice), ctx, userID, deviceToken)
}

// RemoveMfaMethod mocks base method.
func (m *MockUserRepository) RemoveMfaMethod(ctx context.Context, userID, methodID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMfaMethod", ctx, userID, methodID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMfaMethod indicates an expected call of RemoveMfaMethod.
func (mr *MockUserRepositoryMockRecorder) RemoveMfaMethod(ctx, userID, methodID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMfaMethod", reflect.TypeOf((*MockUserRepository)(nil).RemoveMfaMethod), ctx, userID, methodID)
}

// RemoveWebAuthnDevice mocks base method.
func (m *MockUserRepository) RemoveWebAuthnDevice(ctx context.Context, userID, deviceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWebAuthnDevice", ctx, userID, deviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveWebAuthnDevice indicates an expected call of RemoveWebAuthnDevice.
func (mr *MockUserRepositoryMockRecorder) RemoveWebAuthnDevice(ctx, userID, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWebAuthnDevice", reflect.TypeOf((*MockUserRepository)(nil).RemoveWebAuthnDevice), ctx, userID, deviceID)
}

// ResetFailedLoginAttempts mocks base method.
func (m *MockUserRepository) ResetFailedLoginAttempts(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetFailedLoginAttempts", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetFailedLoginAttempts indicates an expected call of ResetFailedLoginAttempts.
func (mr *MockUserRepositoryMockRecorder) ResetFailedLoginAttempts(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetFailedLoginAttempts", reflect.TypeOf((*MockUserRepository)(nil).ResetFailedLoginAttempts), ctx, userID)
}

// SetPhoneNumber mocks base method.
func (m *MockUserRepository) SetPhoneNumber(ctx context.Context, userID, phoneNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPhoneNumber", ctx, userID, phoneNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPhoneNumber indicates an expected call of SetPhoneNumber.
func (mr *MockUserRepositoryMockRecorder) SetPhoneNumber(ctx, userID, phoneNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPhoneNumber", reflect.TypeOf((*MockUserRepository)(nil).SetPhoneNumber), ctx, userID, phoneNumber)
}

// StoreEmailMFAOtp mocks base method.
func (m *MockUserRepository) StoreEmailMFAOtp(ctx context.Context, userID, otp string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreEmailMFAOtp", ctx, userID, otp, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreEmailMFAOtp indicates an expected call of StoreEmailMFAOtp.
func (mr *MockUserRepositoryMockRecorder) StoreEmailMFAOtp(ctx, userID, otp, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreEmailMFAOtp", reflect.TypeOf((*MockUserRepository)(nil).StoreEmailMFAOtp), ctx, userID, otp, expiresAt)
}

// StoreEmailVerificationToken mocks base method.
func (m *MockUserRepository) StoreEmailVerificationToken(ctx context.Context, userID, token string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreEmailVerificationToken", ctx, userID, token, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreEmailVerificationToken indicates an expected call of StoreEmailVerificationToken.
func (mr *MockUserRepositoryMockRecorder) StoreEmailVerificationToken(ctx, userID, token, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreEmailVerificationToken", reflect.TypeOf((*MockUserRepository)(nil).StoreEmailVerificationToken), ctx, userID, token, expiresAt)
}

// StoreLoginOtp mocks base method.
func (m *MockUserRepository) StoreLoginOtp(ctx context.Context, userID, otp, methodType string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreLoginOtp", ctx, userID, otp, methodType, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreLoginOtp indicates an expected call of StoreLoginOtp.
func (mr *MockUserRepositoryMockRecorder) StoreLoginOtp(ctx, userID, otp, methodType, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreLoginOtp", reflect.TypeOf((*MockUserRepository)(nil).StoreLoginOtp), ctx, userID, otp, methodType, expiresAt)
}

// StorePasswordResetToken mocks base method.
func (m *MockUserRepository) StorePasswordResetToken(ctx context.Context, userID, token string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorePasswordResetToken", ctx, userID, token, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorePasswordResetToken indicates an expected call of StorePasswordResetToken.
func (mr *MockUserRepositoryMockRecorder) StorePasswordResetToken(ctx, userID, token, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorePasswordResetToken", reflect.TypeOf((*MockUserRepository)(nil).StorePasswordResetToken), ctx, userID, token, expiresAt)
}

// StorePhoneVerificationOtp mocks base method.
func (m *MockUserRepository) StorePhoneVerificationOtp(ctx context.Context, userID, otp string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorePhoneVerificationOtp", ctx, userID, otp, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorePhoneVerificationOtp indicates an expected call of StorePhoneVerificationOtp.
func (mr *MockUserRepositoryMockRecorder) StorePhoneVerificationOtp(ctx, userID, otp, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorePhoneVerificationOtp", reflect.TypeOf((*MockUserRepository)(nil).StorePhoneVerificationOtp), ctx, userID, otp, expiresAt)
}

// UnregisterPushMFADevice mocks base method.
func (m *MockUserRepository) UnregisterPushMFADevice(ctx context.Context, userID, deviceToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterPushMFADevice", ctx, userID, deviceToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterPushMFADevice indicates an expected call of UnregisterPushMFADevice.
func (mr *MockUserRepositoryMockRecorder) UnregisterPushMFADevice(ctx, userID, deviceToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterPushMFADevice", reflect.TypeOf((*MockUserRepository)(nil).UnregisterPushMFADevice), ctx, userID, deviceToken)
}

// UpdateEmailMFACounter mocks base method.
func (m *MockUserRepository) UpdateEmailMFACounter(ctx context.Context, userID string, counter uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmailMFACounter", ctx, userID, counter)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmailMFACounter indicates an expected call of UpdateEmailMFACounter.
func (mr *MockUserRepositoryMockRecorder) UpdateEmailMFACounter(ctx, userID, counter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmailMFACounter", reflect.TypeOf((*MockUserRepository)(nil).UpdateEmailMFACounter), ctx, userID, counter)
}

// UpdatePushMFAChallenges mocks base method.
func (m *MockUserRepository) UpdatePushMFAChallenges(ctx context.Context, userID string, challenges []domain.PushMFAChallenge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePushMFAChallenges", ctx, userID, challenges)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePushMFAChallenges indicates an expected call of UpdatePushMFAChallenges.
func (mr *MockUserRepositoryMockRecorder) UpdatePushMFAChallenges(ctx, userID, challenges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePushMFAChallenges", reflect.TypeOf((*MockUserRepository)(nil).UpdatePushMFAChallenges), ctx, userID, challenges)
}

// UpdateUser mocks base method.
func (m *MockUserRepository) UpdateUser(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserRepositoryMockRecorder) UpdateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserRepository)(nil).UpdateUser), ctx, user)
}

// UpdateWebAuthnDeviceCounter mocks base method.
func (m *MockUserRepository) UpdateWebAuthnDeviceCounter(ctx context.Context, userID, deviceID string, newCounter int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWebAuthnDeviceCounter", ctx, userID, deviceID, newCounter)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWebAuthnDeviceCounter indicates an expected call of UpdateWebAuthnDeviceCounter.
func (mr *MockUserRepositoryMockRecorder) UpdateWebAuthnDeviceCounter(ctx, userID, deviceID, newCounter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWebAuthnDeviceCounter", reflect.TypeOf((*MockUserRepository)(nil).UpdateWebAuthnDeviceCounter), ctx, userID, deviceID, newCounter)
}

// VerifyMfaMethod mocks base method.
func (m *MockUserRepository) VerifyMfaMethod(ctx context.Context, userID, methodID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyMfaMethod", ctx, userID, methodID)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyMfaMethod indicates an expected call of VerifyMfaMethod.
func (mr *MockUserRepositoryMockRecorder) VerifyMfaMethod(ctx, userID, methodID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyMfaMethod", reflect.TypeOf((*MockUserRepository)(nil).VerifyMfaMethod), ctx, userID, methodID)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// DeleteSession mocks base method.
func (m *MockSessionRepository) DeleteSession(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionRepositoryMockRecorder) DeleteSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionRepository)(nil).DeleteSession), ctx, id)
}

// DeleteSessionsByUserID mocks base method.
func (m *MockSessionRepository) DeleteSessionsByUserID(ctx context.Context, userID string, exceptSessionID ...string) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userID}
	for _, a := range exceptSessionID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteSessionsByUserID", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSessionsByUserID indicates an expected call of DeleteSessionsByUserID.
func (mr *MockSessionRepositoryMockRecorder) DeleteSessionsByUserID(ctx, userID any, exceptSessionID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userID}, exceptSessionID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSessionsByUserID", reflect.TypeOf((*MockSessionRepository)(nil).DeleteSessionsByUserID), varargs...)
}

// GetSessionByID mocks base method.
func (m *MockSessionRepository) GetSessionByID(ctx context.Context, id string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByID", ctx, id)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByID indicates an expected call of GetSessionByID.
func (mr *MockSessionRepositoryMockRecorder) GetSessionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByID", reflect.TypeOf((*MockSessionRepository)(nil).GetSessionByID), ctx, id)
}

// GetSessionByTokenID mocks base method.
func (m *MockSessionRepository) GetSessionByTokenID(ctx context.Context, tokenID string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByTokenID", ctx, tokenID)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByTokenID indicates an expected call of GetSessionByTokenID.
func (mr *MockSessionRepositoryMockRecorder) GetSessionByTokenID(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByTokenID", reflect.TypeOf((*MockSessionRepository)(nil).GetSessionByTokenID), ctx, tokenID)
}

// ListSessionsByUserID mocks base method.
func (m *MockSessionRepository) ListSessionsByUserID(ctx context.Context, userID string, filter domain.SessionFilter) ([]*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessionsByUserID", ctx, userID, filter)
	ret0, _ := ret[0].([]*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessionsByUserID indicates an expected call of ListSessionsByUserID.
func (mr *MockSessionRepositoryMockRecorder) ListSessionsByUserID(ctx, userID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessionsByUserID", reflect.TypeOf((*MockSessionRepository)(nil).ListSessionsByUserID), ctx, userID, filter)
}

// StoreSession mocks base method.
func (m *MockSessionRepository) StoreSession(ctx context.Context, session *domain.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreSession indicates an expected call of StoreSession.
func (mr *MockSessionRepositoryMockRecorder) StoreSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreSession", reflect.TypeOf((*MockSessionRepository)(nil).StoreSession), ctx, session)
}

// UpdateSession mocks base method.
func (m *MockSessionRepository) UpdateSession(ctx context.Context, session *domain.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockSessionRepositoryMockRecorder) UpdateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockSessionRepository)(nil).UpdateSession), ctx, session)
}

// MockTokenRepository is a mock of TokenRepository interface.
type MockTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockTokenRepositoryMockRecorder is the mock recorder for MockTokenRepository.
type MockTokenRepositoryMockRecorder struct {
	mock *MockTokenRepository
}

// NewMockTokenRepository creates a new mock instance.
func NewMockTokenRepository(ctrl *gomock.Controller) *MockTokenRepository {
	mock := &MockTokenRepository{ctrl: ctrl}
	mock.recorder = &MockTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepository) EXPECT() *MockTokenRepositoryMockRecorder {
	return m.recorder
}

// DeleteExpiredTokens mocks base method.
func (m *MockTokenRepository) DeleteExpiredTokens(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredTokens", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredTokens indicates an expected call of DeleteExpiredTokens.
func (mr *MockTokenRepositoryMockRecorder) DeleteExpiredTokens(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredTokens", reflect.TypeOf((*MockTokenRepository)(nil).DeleteExpiredTokens), ctx)
}

// GetAccessToken mocks base method.
func (m *MockTokenRepository) GetAccessToken(ctx context.Context, tokenValue string) (*domain.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessToken", ctx, tokenValue)
	ret0, _ := ret[0].(*domain.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessToken indicates an expected call of GetAccessToken.
func (mr *MockTokenRepositoryMockRecorder) GetAccessToken(ctx, tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessToken", reflect.TypeOf((*MockTokenRepository)(nil).GetAccessToken), ctx, tokenValue)
}

// GetAccessTokenInfo mocks base method.
func (m *MockTokenRepository) GetAccessTokenInfo(ctx context.Context, tokenValue string) (*domain.TokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessTokenInfo", ctx, tokenValue)
	ret0, _ := ret[0].(*domain.TokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessTokenInfo indicates an expected call of GetAccessTokenInfo.
func (mr *MockTokenRepositoryMockRecorder) GetAccessTokenInfo(ctx, tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessTokenInfo", reflect.TypeOf((*MockTokenRepository)(nil).GetAccessTokenInfo), ctx, tokenValue)
}

// GetRefreshToken mocks base method.
func (m *MockTokenRepository) GetRefreshToken(ctx context.Context, tokenValue string) (*domain.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", ctx, tokenValue)
	ret0, _ := ret[0].(*domain.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockTokenRepositoryMockRecorder) GetRefreshToken(ctx, tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockTokenRepository)(nil).GetRefreshToken), ctx, tokenValue)
}

// GetRefreshTokenInfo mocks base method.
func (m *MockTokenRepository) GetRefreshTokenInfo(ctx context.Context, tokenValue string) (*domain.TokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenInfo", ctx, tokenValue)
	ret0, _ := ret[0].(*domain.TokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenInfo indicates an expected call of GetRefreshTokenInfo.
func (mr *MockTokenRepositoryMockRecorder) GetRefreshTokenInfo(ctx, tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenInfo", reflect.TypeOf((*MockTokenRepository)(nil).GetRefreshTokenInfo), ctx, tokenValue)
}

// GetTokenInfo mocks base method.
func (m *MockTokenRepository) GetTokenInfo(ctx context.Context, tokenValue string) (*domain.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenInfo", ctx, tokenValue)
	ret0, _ := ret[0].(*domain.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenInfo indicates an expected call of GetTokenInfo.
func (mr *MockTokenRepositoryMockRecorder) GetTokenInfo(ctx, tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenInfo", reflect.TypeOf((*MockTokenRepository)(nil).GetTokenInfo), ctx, tokenValue)
}

// RevokeRefreshToken mocks base method.
func (m *MockTokenRepository) RevokeRefreshToken(ctx context.Context, tokenValue string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshToken", ctx, tokenValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRefreshToken indicates an expected call of RevokeRefreshToken.
func (mr *MockTokenRepositoryMockRecorder) RevokeRefreshToken(ctx, tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshToken", reflect.TypeOf((*MockTokenRepository)(nil).RevokeRefreshToken), ctx, tokenValue)
}

// RevokeToken mocks base method.
func (m *MockTokenRepository) RevokeToken(ctx context.Context, tokenValue string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, tokenValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockTokenRepositoryMockRecorder) RevokeToken(ctx, tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockTokenRepository)(nil).RevokeToken), ctx, tokenValue)
}

// StoreToken mocks base method.
func (m *MockTokenRepository) StoreToken(ctx context.Context, token *domain.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreToken indicates an expected call of StoreToken.
func (mr *MockTokenRepositoryMockRecorder) StoreToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreToken", reflect.TypeOf((*MockTokenRepository)(nil).StoreToken), ctx, token)
}

// MockAuthorizationCodeRepository is a mock of AuthorizationCodeRepository interface.
type MockAuthorizationCodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationCodeRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthorizationCodeRepositoryMockRecorder is the mock recorder for MockAuthorizationCodeRepository.
type MockAuthorizationCodeRepositoryMockRecorder struct {
	mock *MockAuthorizationCodeRepository
}

// NewMockAuthorizationCodeRepository creates a new mock instance.
func NewMockAuthorizationCodeRepository(ctrl *gomock.Controller) *MockAuthorizationCodeRepository {
	mock := &MockAuthorizationCodeRepository{ctrl: ctrl}
	mock.recorder = &MockAuthorizationCodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizationCodeRepository) EXPECT() *MockAuthorizationCodeRepositoryMockRecorder {
	return m.recorder
}

// DeleteExpiredAuthCodes mocks base method.
func (m *MockAuthorizationCodeRepository) DeleteExpiredAuthCodes(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredAuthCodes", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredAuthCodes indicates an expected call of DeleteExpiredAuthCodes.
func (mr *MockAuthorizationCodeRepositoryMockRecorder) DeleteExpiredAuthCodes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredAuthCodes", reflect.TypeOf((*MockAuthorizationCodeRepository)(nil).DeleteExpiredAuthCodes), ctx)
}

// GetAuthCode mocks base method.
func (m *MockAuthorizationCodeRepository) GetAuthCode(ctx context.Context, code string) (*domain.AuthCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthCode", ctx, code)
	ret0, _ := ret[0].(*domain.AuthCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthCode indicates an expected call of GetAuthCode.
func (mr *MockAuthorizationCodeRepositoryMockRecorder) GetAuthCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthCode", reflect.TypeOf((*MockAuthorizationCodeRepository)(nil).GetAuthCode), ctx, code)
}

// MarkAuthCodeAsUsed mocks base method.
func (m *MockAuthorizationCodeRepository) MarkAuthCodeAsUsed(ctx context.Context, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAuthCodeAsUsed", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAuthCodeAsUsed indicates an expected call of MarkAuthCodeAsUsed.
func (mr *MockAuthorizationCodeRepositoryMockRecorder) MarkAuthCodeAsUsed(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAuthCodeAsUsed", reflect.TypeOf((*MockAuthorizationCodeRepository)(nil).MarkAuthCodeAsUsed), ctx, code)
}

// SaveAuthCode mocks base method.
func (m *MockAuthorizationCodeRepository) SaveAuthCode(ctx context.Context, code *domain.AuthCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAuthCode", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAuthCode indicates an expected call of SaveAuthCode.
func (mr *MockAuthorizationCodeRepositoryMockRecorder) SaveAuthCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAuthCode", reflect.TypeOf((*MockAuthorizationCodeRepository)(nil).SaveAuthCode), ctx, code)
}

// MockPkceRepository is a mock of PkceRepository interface.
type MockPkceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPkceRepositoryMockRecorder
	isgomock struct{}
}

// MockPkceRepositoryMockRecorder is the mock recorder for MockPkceRepository.
type MockPkceRepositoryMockRecorder struct {
	mock *MockPkceRepository
}

// NewMockPkceRepository creates a new mock instance.
func NewMockPkceRepository(ctrl *gomock.Controller) *MockPkceRepository {
	mock := &MockPkceRepository{ctrl: ctrl}
	mock.recorder = &MockPkceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPkceRepository) EXPECT() *MockPkceRepositoryMockRecorder {
	return m.recorder
}

// DeleteCodeChallenge mocks base method.
func (m *MockPkceRepository) DeleteCodeChallenge(ctx context.Context, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCodeChallenge", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCodeChallenge indicates an expected call of DeleteCodeChallenge.
func (mr *MockPkceRepositoryMockRecorder) DeleteCodeChallenge(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCodeChallenge", reflect.TypeOf((*MockPkceRepository)(nil).DeleteCodeChallenge), ctx, code)
}

// GetCodeChallenge mocks base method.
func (m *MockPkceRepository) GetCodeChallenge(ctx context.Context, code string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCodeChallenge", ctx, code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCodeChallenge indicates an expected call of GetCodeChallenge.
func (mr *MockPkceRepositoryMockRecorder) GetCodeChallenge(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCodeChallenge", reflect.TypeOf((*MockPkceRepository)(nil).GetCodeChallenge), ctx, code)
}

// SaveCodeChallenge mocks base method.
func (m *MockPkceRepository) SaveCodeChallenge(ctx context.Context, code, challenge string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCodeChallenge", ctx, code, challenge)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCodeChallenge indicates an expected call of SaveCodeChallenge.
func (mr *MockPkceRepositoryMockRecorder) SaveCodeChallenge(ctx, code, challenge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCodeChallenge", reflect.TypeOf((*MockPkceRepository)(nil).SaveCodeChallenge), ctx, code, challenge)
}

// MockDeviceAuthorizationRepository is a mock of DeviceAuthorizationRepository interface.
type MockDeviceAuthorizationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceAuthorizationRepositoryMockRecorder
	isgomock struct{}
}

// MockDeviceAuthorizationRepositoryMockRecorder is the mock recorder for MockDeviceAuthorizationRepository.
type MockDeviceAuthorizationRepositoryMockRecorder struct {
	mock *MockDeviceAuthorizationRepository
}

// NewMockDeviceAuthorizationRepository creates a new mock instance.
func NewMockDeviceAuthorizationRepository(ctrl *gomock.Controller) *MockDeviceAuthorizationRepository {
	mock := &MockDeviceAuthorizationRepository{ctrl: ctrl}
	mock.recorder = &MockDeviceAuthorizationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceAuthorizationRepository) EXPECT() *MockDeviceAuthorizationRepositoryMockRecorder {
	return m.recorder
}

// ApproveDeviceAuth mocks base method.
func (m *MockDeviceAuthorizationRepository) ApproveDeviceAuth(ctx context.Context, userCode, userID string) (*domain.DeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveDeviceAuth", ctx, userCode, userID)
	ret0, _ := ret[0].(*domain.DeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApproveDeviceAuth indicates an expected call of ApproveDeviceAuth.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) ApproveDeviceAuth(ctx, userCode, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveDeviceAuth", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).ApproveDeviceAuth), ctx, userCode, userID)
}

// DeleteExpiredDeviceAuths mocks base method.
func (m *MockDeviceAuthorizationRepository) DeleteExpiredDeviceAuths(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredDeviceAuths", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredDeviceAuths indicates an expected call of DeleteExpiredDeviceAuths.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) DeleteExpiredDeviceAuths(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredDeviceAuths", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).DeleteExpiredDeviceAuths), ctx)
}

// GetDeviceAuthByDeviceCode mocks base method.
func (m *MockDeviceAuthorizationRepository) GetDeviceAuthByDeviceCode(ctx context.Context, deviceCode string) (*domain.DeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceAuthByDeviceCode", ctx, deviceCode)
	ret0, _ := ret[0].(*domain.DeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceAuthByDeviceCode indicates an expected call of GetDeviceAuthByDeviceCode.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) GetDeviceAuthByDeviceCode(ctx, deviceCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceAuthByDeviceCode", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).GetDeviceAuthByDeviceCode), ctx, deviceCode)
}

// GetDeviceAuthByUserCode mocks base method.
func (m *MockDeviceAuthorizationRepository) GetDeviceAuthByUserCode(ctx context.Context, userCode string) (*domain.DeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceAuthByUserCode", ctx, userCode)
	ret0, _ := ret[0].(*domain.DeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceAuthByUserCode indicates an expected call of GetDeviceAuthByUserCode.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) GetDeviceAuthByUserCode(ctx, userCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceAuthByUserCode", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).GetDeviceAuthByUserCode), ctx, userCode)
}

// SaveDeviceAuth mocks base method.
func (m *MockDeviceAuthorizationRepository) SaveDeviceAuth(ctx context.Context, auth *domain.DeviceCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDeviceAuth", ctx, auth)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDeviceAuth indicates an expected call of SaveDeviceAuth.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) SaveDeviceAuth(ctx, auth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDeviceAuth", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).SaveDeviceAuth), ctx, auth)
}

// UpdateDeviceAuthLastPolledAt mocks base method.
func (m *MockDeviceAuthorizationRepository) UpdateDeviceAuthLastPolledAt(ctx context.Context, deviceCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceAuthLastPolledAt", ctx, deviceCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeviceAuthLastPolledAt indicates an expected call of UpdateDeviceAuthLastPolledAt.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) UpdateDeviceAuthLastPolledAt(ctx, deviceCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceAuthLastPolledAt", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).UpdateDeviceAuthLastPolledAt), ctx, deviceCode)
}

// UpdateDeviceAuthStatus mocks base method.
func (m *MockDeviceAuthorizationRepository) UpdateDeviceAuthStatus(ctx context.Context, deviceCode string, status domain.DeviceCodeStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceAuthStatus", ctx, deviceCode, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeviceAuthStatus indicates an expected call of UpdateDeviceAuthStatus.
func (mr *MockDeviceAuthorizationRepositoryMockRecorder) UpdateDeviceAuthStatus(ctx, deviceCode, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceAuthStatus", reflect.TypeOf((*MockDeviceAuthorizationRepository)(nil).UpdateDeviceAuthStatus), ctx, deviceCode, status)
}

// MockIdPRepository is a mock of IdPRepository interface.
type MockIdPRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIdPRepositoryMockRecorder
	isgomock struct{}
}

// MockIdPRepositoryMockRecorder is the mock recorder for MockIdPRepository.
type MockIdPRepositoryMockRecorder struct {
	mock *MockIdPRepository
}

// NewMockIdPRepository creates a new mock instance.
func NewMockIdPRepository(ctrl *gomock.Controller) *MockIdPRepository {
	mock := &MockIdPRepository{ctrl: ctrl}
	mock.recorder = &MockIdPRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdPRepository) EXPECT() *MockIdPRepositoryMockRecorder {
	return m.recorder
}

// AddIdP mocks base method.
func (m *MockIdPRepository) AddIdP(ctx context.Context, idp *domain.IdentityProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddIdP", ctx, idp)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddIdP indicates an expected call of AddIdP.
func (mr *MockIdPRepositoryMockRecorder) AddIdP(ctx, idp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIdP", reflect.TypeOf((*MockIdPRepository)(nil).AddIdP), ctx, idp)
}

// DeleteIdP mocks base method.
func (m *MockIdPRepository) DeleteIdP(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIdP", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIdP indicates an expected call of DeleteIdP.
func (mr *MockIdPRepositoryMockRecorder) DeleteIdP(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIdP", reflect.TypeOf((*MockIdPRepository)(nil).DeleteIdP), ctx, id)
}

// GetIdPByID mocks base method.
func (m *MockIdPRepository) GetIdPByID(ctx context.Context, id string) (*domain.IdentityProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdPByID", ctx, id)
	ret0, _ := ret[0].(*domain.IdentityProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdPByID indicates an expected call of GetIdPByID.
func (mr *MockIdPRepositoryMockRecorder) GetIdPByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdPByID", reflect.TypeOf((*MockIdPRepository)(nil).GetIdPByID), ctx, id)
}

// GetIdPByName mocks base method.
func (m *MockIdPRepository) GetIdPByName(ctx context.Context, name string) (*domain.IdentityProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdPByName", ctx, name)
	ret0, _ := ret[0].(*domain.IdentityProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdPByName indicates an expected call of GetIdPByName.
func (mr *MockIdPRepositoryMockRecorder) GetIdPByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdPByName", reflect.TypeOf((*MockIdPRepository)(nil).GetIdPByName), ctx, name)
}

// ListIdPs mocks base method.
func (m *MockIdPRepository) ListIdPs(ctx context.Context, onlyEnabled bool) ([]*domain.IdentityProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIdPs", ctx, onlyEnabled)
	ret0, _ := ret[0].([]*domain.IdentityProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIdPs indicates an expected call of ListIdPs.
func (mr *MockIdPRepositoryMockRecorder) ListIdPs(ctx, onlyEnabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIdPs", reflect.TypeOf((*MockIdPRepository)(nil).ListIdPs), ctx, onlyEnabled)
}

// UpdateIdP mocks base method.
func (m *MockIdPRepository) UpdateIdP(ctx context.Context, idp *domain.IdentityProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIdP", ctx, idp)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIdP indicates an expected call of UpdateIdP.
func (mr *MockIdPRepositoryMockRecorder) UpdateIdP(ctx, idp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIdP", reflect.TypeOf((*MockIdPRepository)(nil).UpdateIdP), ctx, idp)
}

// MockUserFederatedIdentityRepository is a mock of UserFederatedIdentityRepository interface.
type MockUserFederatedIdentityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserFederatedIdentityRepositoryMockRecorder
	isgomock struct{}
}

// MockUserFederatedIdentityRepositoryMockRecorder is the mock recorder for MockUserFederatedIdentityRepository.
type MockUserFederatedIdentityRepositoryMockRecorder struct {
	mock *MockUserFederatedIdentityRepository
}

// NewMockUserFederatedIdentityRepository creates a new mock instance.
func NewMockUserFederatedIdentityRepository(ctrl *gomock.Controller) *MockUserFederatedIdentityRepository {
	mock := &MockUserFederatedIdentityRepository{ctrl: ctrl}
	mock.recorder = &MockUserFederatedIdentityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserFederatedIdentityRepository) EXPECT() *MockUserFederatedIdentityRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserFederatedIdentityRepository) Create(ctx context.Context, identity *domain.UserFederatedIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserFederatedIdentityRepositoryMockRecorder) Create(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserFederatedIdentityRepository)(nil).Create), ctx, identity)
}

// Delete mocks base method.
func (m *MockUserFederatedIdentityRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserFederatedIdentityRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserFederatedIdentityRepository)(nil).Delete), ctx, id)
}

// DeleteByUserIDAndProvider mocks base method.
func (m *MockUserFederatedIdentityRepository) DeleteByUserIDAndProvider(ctx context.Context, userID, providerName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserIDAndProvider", ctx, userID, providerName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserIDAndProvider indicates an expected call of DeleteByUserIDAndProvider.
func (mr *MockUserFederatedIdentityRepositoryMockRecorder) DeleteByUserIDAndProvider(ctx, userID, providerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserIDAndProvider", reflect.TypeOf((*MockUserFederatedIdentityRepository)(nil).DeleteByUserIDAndProvider), ctx, userID, providerName)
}

// GetByProviderUserID mocks base method.
func (m *MockUserFederatedIdentityRepository) GetByProviderUserID(ctx context.Context, providerName, providerUserID string) (*domain.UserFederatedIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProviderUserID", ctx, providerName, providerUserID)
	ret0, _ := ret[0].(*domain.UserFederatedIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProviderUserID indicates an expected call of GetByProviderUserID.
func (mr *MockUserFederatedIdentityRepositoryMockRecorder) GetByProviderUserID(ctx, providerName, providerUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProviderUserID", reflect.TypeOf((*MockUserFederatedIdentityRepository)(nil).GetByProviderUserID), ctx, providerName, providerUserID)
}

// GetByUserIDAndProvider mocks base method.
func (m *MockUserFederatedIdentityRepository) GetByUserIDAndProvider(ctx context.Context, userID, providerName string) (*domain.UserFederatedIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserIDAndProvider", ctx, userID, providerName)
	ret0, _ := ret[0].(*domain.UserFederatedIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserIDAndProvider indicates an expected call of GetByUserIDAndProvider.
func (mr *MockUserFederatedIdentityRepositoryMockRecorder) GetByUserIDAndProvider(ctx, userID, providerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserIDAndProvider", reflect.TypeOf((*MockUserFederatedIdentityRepository)(nil).GetByUserIDAndProvider), ctx, userID, providerName)
}

// ListByUserID mocks base method.
func (m *MockUserFederatedIdentityRepository) ListByUserID(ctx context.Context, userID string) ([]*domain.UserFederatedIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain.UserFederatedIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockUserFederatedIdentityRepositoryMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockUserFederatedIdentityRepository)(nil).ListByUserID), ctx, userID)
}

// MockConfigurationRepository is a mock of ConfigurationRepository interface.
type MockConfigurationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConfigurationRepositoryMockRecorder
	isgomock struct{}
}

// MockConfigurationRepositoryMockRecorder is the mock recorder for MockConfigurationRepository.
type MockConfigurationRepositoryMockRecorder struct {
	mock *MockConfigurationRepository
}

// NewMockConfigurationRepository creates a new mock instance.
func NewMockConfigurationRepository(ctrl *gomock.Controller) *MockConfigurationRepository {
	mock := &MockConfigurationRepository{ctrl: ctrl}
	mock.recorder = &MockConfigurationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigurationRepository) EXPECT() *MockConfigurationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockConfigurationRepository) Create(ctx context.Context, config *domain.Configuration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockConfigurationRepositoryMockRecorder) Create(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConfigurationRepository)(nil).Create), ctx, config)
}

// CreateDefaultConfigs mocks base method.
func (m *MockConfigurationRepository) CreateDefaultConfigs(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDefaultConfigs", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDefaultConfigs indicates an expected call of CreateDefaultConfigs.
func (mr *MockConfigurationRepositoryMockRecorder) CreateDefaultConfigs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDefaultConfigs", reflect.TypeOf((*MockConfigurationRepository)(nil).CreateDefaultConfigs), ctx)
}

// Delete mocks base method.
func (m *MockConfigurationRepository) Delete(ctx context.Context, configType domain.ConfigurationType, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, configType, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockConfigurationRepositoryMockRecorder) Delete(ctx, configType, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConfigurationRepository)(nil).Delete), ctx, configType, key)
}

// GetAllActive mocks base method.
func (m *MockConfigurationRepository) GetAllActive(ctx context.Context) ([]*domain.Configuration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllActive", ctx)
	ret0, _ := ret[0].([]*domain.Configuration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllActive indicates an expected call of GetAllActive.
func (mr *MockConfigurationRepositoryMockRecorder) GetAllActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllActive", reflect.TypeOf((*MockConfigurationRepository)(nil).GetAllActive), ctx)
}

// GetByKey mocks base method.
func (m *MockConfigurationRepository) GetByKey(ctx context.Context, configType domain.ConfigurationType, key string) (*domain.Configuration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKey", ctx, configType, key)
	ret0, _ := ret[0].(*domain.Configuration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKey indicates an expected call of GetByKey.
func (mr *MockConfigurationRepositoryMockRecorder) GetByKey(ctx, configType, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKey", reflect.TypeOf((*MockConfigurationRepository)(nil).GetByKey), ctx, configType, key)
}

// GetByType mocks base method.
func (m *MockConfigurationRepository) GetByType(ctx context.Context, configType domain.ConfigurationType) ([]*domain.Configuration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByType", ctx, configType)
	ret0, _ := ret[0].([]*domain.Configuration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByType indicates an expected call of GetByType.
func (mr *MockConfigurationRepositoryMockRecorder) GetByType(ctx, configType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByType", reflect.TypeOf((*MockConfigurationRepository)(nil).GetByType), ctx, configType)
}

// GetByTypeActive mocks base method.
func (m *MockConfigurationRepository) GetByTypeActive(ctx context.Context, configType domain.ConfigurationType) ([]*domain.Configuration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTypeActive", ctx, configType)
	ret0, _ := ret[0].([]*domain.Configuration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTypeActive indicates an expected call of GetByTypeActive.
func (mr *MockConfigurationRepositoryMockRecorder) GetByTypeActive(ctx, configType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTypeActive", reflect.TypeOf((*MockConfigurationRepository)(nil).GetByTypeActive), ctx, configType)
}

// Update mocks base method.
func (m *MockConfigurationRepository) Update(ctx context.Context, config *domain.Configuration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockConfigurationRepositoryMockRecorder) Update(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockConfigurationRepository)(nil).Update), ctx, config)
}
