// Code generated by MockGen. DO NOT EDIT.
// Source: user_attribute.go
//
// Generated by this command:
//
//	mockgen -source=user_attribute.go -destination=mocks/mock_user_attribute_mapper_repository.go -package=mock_domain -exclude_interfaces=UserAttributeRepository UserAttributeMapperRepository
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	domain "github.com/pilab-dev/shadow-sso/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserAttributeMapperRepository is a mock of UserAttributeMapperRepository interface.
type MockUserAttributeMapperRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserAttributeMapperRepositoryMockRecorder
	isgomock struct{}
}

// MockUserAttributeMapperRepositoryMockRecorder is the mock recorder for MockUserAttributeMapperRepository.
type MockUserAttributeMapperRepositoryMockRecorder struct {
	mock *MockUserAttributeMapperRepository
}

// NewMockUserAttributeMapperRepository creates a new mock instance.
func NewMockUserAttributeMapperRepository(ctrl *gomock.Controller) *MockUserAttributeMapperRepository {
	mock := &MockUserAttributeMapperRepository{ctrl: ctrl}
	mock.recorder = &MockUserAttributeMapperRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAttributeMapperRepository) EXPECT() *MockUserAttributeMapperRepositoryMockRecorder {
	return m.recorder
}

// CreateMapper mocks base method.
func (m *MockUserAttributeMapperRepository) CreateMapper(ctx context.Context, mapper *domain.UserAttributeMapper) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMapper", ctx, mapper)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMapper indicates an expected call of CreateMapper.
func (mr *MockUserAttributeMapperRepositoryMockRecorder) CreateMapper(ctx, mapper any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMapper", reflect.TypeOf((*MockUserAttributeMapperRepository)(nil).CreateMapper), ctx, mapper)
}

// DeleteMapper mocks base method.
func (m *MockUserAttributeMapperRepository) DeleteMapper(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMapper", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMapper indicates an expected call of DeleteMapper.
func (mr *MockUserAttributeMapperRepositoryMockRecorder) DeleteMapper(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMapper", reflect.TypeOf((*MockUserAttributeMapperRepository)(nil).DeleteMapper), ctx, id)
}

// GetClientMappers mocks base method.
func (m *MockUserAttributeMapperRepository) GetClientMappers(ctx context.Context, clientID string) ([]*domain.UserAttributeMapper, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientMappers", ctx, clientID)
	ret0, _ := ret[0].([]*domain.UserAttributeMapper)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientMappers indicates an expected call of GetClientMappers.
func (mr *MockUserAttributeMapperRepositoryMockRecorder) GetClientMappers(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientMappers", reflect.TypeOf((*MockUserAttributeMapperRepository)(nil).GetClientMappers), ctx, clientID)
}

// GetMapperByID mocks base method.
func (m *MockUserAttributeMapperRepository) GetMapperByID(ctx context.Context, id string) (*domain.UserAttributeMapper, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMapperByID", ctx, id)
	ret0, _ := ret[0].(*domain.UserAttributeMapper)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMapperByID indicates an expected call of GetMapperByID.
func (mr *MockUserAttributeMapperRepositoryMockRecorder) GetMapperByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMapperByID", reflect.TypeOf((*MockUserAttributeMapperRepository)(nil).GetMapperByID), ctx, id)
}

// GetMappersByTokenType mocks base method.
func (m *MockUserAttributeMapperRepository) GetMappersByTokenType(ctx context.Context, tokenType string) ([]*domain.UserAttributeMapper, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMappersByTokenType", ctx, tokenType)
	ret0, _ := ret[0].([]*domain.UserAttributeMapper)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMappersByTokenType indicates an expected call of GetMappersByTokenType.
func (mr *MockUserAttributeMapperRepositoryMockRecorder) GetMappersByTokenType(ctx, tokenType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMappersByTokenType", reflect.TypeOf((*MockUserAttributeMapperRepository)(nil).GetMappersByTokenType), ctx, tokenType)
}

// GetMappersForClient mocks base method.
func (m *MockUserAttributeMapperRepository) GetMappersForClient(ctx context.Context, clientID, tokenType string) ([]*domain.UserAttributeMapper, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMappersForClient", ctx, clientID, tokenType)
	ret0, _ := ret[0].([]*domain.UserAttributeMapper)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMappersForClient indicates an expected call of GetMappersForClient.
func (mr *MockUserAttributeMapperRepositoryMockRecorder) GetMappersForClient(ctx, clientID, tokenType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMappersForClient", reflect.TypeOf((*MockUserAttributeMapperRepository)(nil).GetMappersForClient), ctx, clientID, tokenType)
}

// ListAllMappers mocks base method.
func (m *MockUserAttributeMapperRepository) ListAllMappers(ctx context.Context) ([]*domain.UserAttributeMapper, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllMappers", ctx)
	ret0, _ := ret[0].([]*domain.UserAttributeMapper)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllMappers indicates an expected call of ListAllMappers.
func (mr *MockUserAttributeMapperRepositoryMockRecorder) ListAllMappers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllMappers", reflect.TypeOf((*MockUserAttributeMapperRepository)(nil).ListAllMappers), ctx)
}

// UpdateMapper mocks base method.
func (m *MockUserAttributeMapperRepository) UpdateMapper(ctx context.Context, mapper *domain.UserAttributeMapper) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMapper", ctx, mapper)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMapper indicates an expected call of UpdateMapper.
func (mr *MockUserAttributeMapperRepositoryMockRecorder) UpdateMapper(ctx, mapper any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMapper", reflect.TypeOf((*MockUserAttributeMapperRepository)(nil).UpdateMapper), ctx, mapper)
}
