// Code generated by MockGen. DO NOT EDIT.
// Source: client_service.go
//
// Generated by this command:
//
//	mockgen -source=client_service.go -destination=mocks/mock_client_service.go -package=mock_client ClientServiceInterface
//

// Package mock_client is a generated GoMock package.
package mock_client

import (
	context "context"
	reflect "reflect"

	domain "github.com/pilab-dev/shadow-sso/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockClientServiceInterface is a mock of ClientServiceInterface interface.
type MockClientServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockClientServiceInterfaceMockRecorder is the mock recorder for MockClientServiceInterface.
type MockClientServiceInterfaceMockRecorder struct {
	mock *MockClientServiceInterface
}

// NewMockClientServiceInterface creates a new mock instance.
func NewMockClientServiceInterface(ctrl *gomock.Controller) *MockClientServiceInterface {
	mock := &MockClientServiceInterface{ctrl: ctrl}
	mock.recorder = &MockClientServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientServiceInterface) EXPECT() *MockClientServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateClient mocks base method.
func (m *MockClientServiceInterface) CreateClient(ctx context.Context, client *domain.Client) (*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClient", ctx, client)
	ret0, _ := ret[0].(*domain.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClient indicates an expected call of CreateClient.
func (mr *MockClientServiceInterfaceMockRecorder) CreateClient(ctx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClient", reflect.TypeOf((*MockClientServiceInterface)(nil).CreateClient), ctx, client)
}

// CreateConfidentialClient mocks base method.
func (m *MockClientServiceInterface) CreateConfidentialClient(ctx context.Context, name string, redirectURIs, allowedScopes []string) (*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConfidentialClient", ctx, name, redirectURIs, allowedScopes)
	ret0, _ := ret[0].(*domain.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConfidentialClient indicates an expected call of CreateConfidentialClient.
func (mr *MockClientServiceInterfaceMockRecorder) CreateConfidentialClient(ctx, name, redirectURIs, allowedScopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConfidentialClient", reflect.TypeOf((*MockClientServiceInterface)(nil).CreateConfidentialClient), ctx, name, redirectURIs, allowedScopes)
}

// CreatePublicClient mocks base method.
func (m *MockClientServiceInterface) CreatePublicClient(ctx context.Context, name string, redirectURIs, allowedScopes []string) (*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePublicClient", ctx, name, redirectURIs, allowedScopes)
	ret0, _ := ret[0].(*domain.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePublicClient indicates an expected call of CreatePublicClient.
func (mr *MockClientServiceInterfaceMockRecorder) CreatePublicClient(ctx, name, redirectURIs, allowedScopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePublicClient", reflect.TypeOf((*MockClientServiceInterface)(nil).CreatePublicClient), ctx, name, redirectURIs, allowedScopes)
}

// GetClient mocks base method.
func (m *MockClientServiceInterface) GetClient(ctx context.Context, clientID string) (*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", ctx, clientID)
	ret0, _ := ret[0].(*domain.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockClientServiceInterfaceMockRecorder) GetClient(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockClientServiceInterface)(nil).GetClient), ctx, clientID)
}

// RequiresPKCE mocks base method.
func (m *MockClientServiceInterface) RequiresPKCE(ctx context.Context, clientID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequiresPKCE", ctx, clientID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequiresPKCE indicates an expected call of RequiresPKCE.
func (mr *MockClientServiceInterfaceMockRecorder) RequiresPKCE(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequiresPKCE", reflect.TypeOf((*MockClientServiceInterface)(nil).RequiresPKCE), ctx, clientID)
}

// ValidateClient mocks base method.
func (m *MockClientServiceInterface) ValidateClient(ctx context.Context, clientID, clientSecret string) (*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateClient", ctx, clientID, clientSecret)
	ret0, _ := ret[0].(*domain.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateClient indicates an expected call of ValidateClient.
func (mr *MockClientServiceInterfaceMockRecorder) ValidateClient(ctx, clientID, clientSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateClient", reflect.TypeOf((*MockClientServiceInterface)(nil).ValidateClient), ctx, clientID, clientSecret)
}

// ValidateGrantType mocks base method.
func (m *MockClientServiceInterface) ValidateGrantType(ctx context.Context, clientID, grantType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateGrantType", ctx, clientID, grantType)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateGrantType indicates an expected call of ValidateGrantType.
func (mr *MockClientServiceInterfaceMockRecorder) ValidateGrantType(ctx, clientID, grantType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateGrantType", reflect.TypeOf((*MockClientServiceInterface)(nil).ValidateGrantType), ctx, clientID, grantType)
}

// ValidateRedirectURI mocks base method.
func (m *MockClientServiceInterface) ValidateRedirectURI(ctx context.Context, clientID, redirectURI string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRedirectURI", ctx, clientID, redirectURI)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateRedirectURI indicates an expected call of ValidateRedirectURI.
func (mr *MockClientServiceInterfaceMockRecorder) ValidateRedirectURI(ctx, clientID, redirectURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRedirectURI", reflect.TypeOf((*MockClientServiceInterface)(nil).ValidateRedirectURI), ctx, clientID, redirectURI)
}

// ValidateScope mocks base method.
func (m *MockClientServiceInterface) ValidateScope(ctx context.Context, clientID string, requestedScopes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateScope", ctx, clientID, requestedScopes)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateScope indicates an expected call of ValidateScope.
func (mr *MockClientServiceInterfaceMockRecorder) ValidateScope(ctx, clientID, requestedScopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateScope", reflect.TypeOf((*MockClientServiceInterface)(nil).ValidateScope), ctx, clientID, requestedScopes)
}
