services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  ssso:
    build: .
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "5001:5000"
    env_file:
      - .env
    environment:
      - SSSO_MGMT_HTTP_ADDR=:5000
      - SSSO_HTTP_ADDR=0.0.0.0:8080
      - SSSO_MONGO_URI=mongodb://mongo:27017
      - SSSO_MONGO_DB_NAME=shadow_sso_dev
      - SSSO_SIGNING_KEY_PATH=/etc/sso/keys/private.pem
    volumes:
      - ./docker/entrypoint.sh:/docker/entrypoint.sh:ro
      - ./docker/keys:/etc/sso/keys
    restart: unless-stopped

volumes:
  mongo_data:
