// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"time"

	"github.com/pilab-dev/shadow-sso/domain"
)

type AuditLogConnection struct {
	Edges      []AuditLogEdge `json:"edges"`
	TotalCount int            `json:"totalCount"`
	PageInfo   *PageInfo      `json:"pageInfo"`
}

type AuditLogEdge struct {
	Node   *domain.AuditLog `json:"node"`
	Cursor string           `json:"cursor"`
}

type AuthenticationExecutionInput struct {
	ID          *string `json:"id,omitempty"`
	Execution   string  `json:"execution"`
	Requirement string  `json:"requirement"`
}

type ClaimMapping struct {
	Name                 string `json:"name"`
	AlwaysIncludeInToken bool   `json:"alwaysIncludeInToken"`
}

type ClaimMappingInput struct {
	Name                 string `json:"name"`
	AlwaysIncludeInToken *bool  `json:"alwaysIncludeInToken,omitempty"`
}

type ClientConnection struct {
	Edges      []ClientEdge `json:"edges"`
	TotalCount int          `json:"totalCount"`
	PageInfo   *PageInfo    `json:"pageInfo"`
}

type ClientEdge struct {
	Node   *domain.Client `json:"node"`
	Cursor string         `json:"cursor"`
}

type ClientRoleMappingInput struct {
	ClientID string `json:"clientId"`
	RoleID   string `json:"roleId"`
}

type CreateAuthenticationFlowInput struct {
	Alias       string  `json:"alias"`
	DisplayName string  `json:"displayName"`
	Description *string `json:"description,omitempty"`
	BuiltIn     *bool   `json:"builtIn,omitempty"`
	TopLevel    *bool   `json:"topLevel,omitempty"`
}

type CreateClientInput struct {
	ClientID                  string              `json:"clientId"`
	ClientName                string              `json:"clientName"`
	Description               *string             `json:"description,omitempty"`
	Enabled                   *bool               `json:"enabled,omitempty"`
	RedirectUris              []string            `json:"redirectUris,omitempty"`
	PostLogoutRedirectUris    []string            `json:"postLogoutRedirectUris,omitempty"`
	WebOrigins                []string            `json:"webOrigins,omitempty"`
	AllowedGrantTypes         []string            `json:"allowedGrantTypes,omitempty"`
	StandardFlowEnabled       *bool               `json:"standardFlowEnabled,omitempty"`
	ImplicitFlowEnabled       *bool               `json:"implicitFlowEnabled,omitempty"`
	DirectAccessGrantsEnabled *bool               `json:"directAccessGrantsEnabled,omitempty"`
	ServiceAccountsEnabled    *bool               `json:"serviceAccountsEnabled,omitempty"`
	PublicClient              *bool               `json:"publicClient,omitempty"`
	FrontchannelLogout        *bool               `json:"frontchannelLogout,omitempty"`
	FullScopeAllowed          *bool               `json:"fullScopeAllowed,omitempty"`
	DefaultRoles              []string            `json:"defaultRoles,omitempty"`
	OptionalClaims            []ClaimMappingInput `json:"optionalClaims,omitempty"`
	Scope                     []string            `json:"scope,omitempty"`
	ClientSecret              *string             `json:"clientSecret,omitempty"`
	ClientType                *string             `json:"clientType,omitempty"`
	Jwks                      *string             `json:"jwks,omitempty"`
	JwksURI                   *string             `json:"jwksUri,omitempty"`
}

type CreateClientScopeInput struct {
	Name              string  `json:"name"`
	Description       *string `json:"description,omitempty"`
	Protocol          *string `json:"protocol,omitempty"`
	ConsentScreenText *string `json:"consentScreenText,omitempty"`
	DisplayOrder      *int    `json:"displayOrder,omitempty"`
}

type CreateCompositeRoleInput struct {
	Name        string                   `json:"name"`
	Description *string                  `json:"description,omitempty"`
	RealmRoles  []string                 `json:"realmRoles,omitempty"`
	ClientRoles []ClientRoleMappingInput `json:"clientRoles,omitempty"`
}

type CreateGroupInput struct {
	Name       string   `json:"name"`
	Path       *string  `json:"path,omitempty"`
	RealmRoles []string `json:"realmRoles,omitempty"`
}

type CreateIdentityProviderInput struct {
	Alias                     string         `json:"alias"`
	DisplayName               string         `json:"displayName"`
	ProviderID                string         `json:"providerId"`
	Config                    map[string]any `json:"config,omitempty"`
	Enabled                   *bool          `json:"enabled,omitempty"`
	TrustEmail                *bool          `json:"trustEmail,omitempty"`
	StoreToken                *bool          `json:"storeToken,omitempty"`
	AddReadTokenRoleOnCreate  *bool          `json:"addReadTokenRoleOnCreate,omitempty"`
	AuthenticateDefaultAction *bool          `json:"authenticateDefaultAction,omitempty"`
}

type CreateProtocolMapperInput struct {
	Name           string         `json:"name"`
	Protocol       string         `json:"protocol"`
	ProtocolMapper string         `json:"protocolMapper"`
	Config         map[string]any `json:"config,omitempty"`
}

type CreateRoleInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Composite   *bool   `json:"composite,omitempty"`
	ClientRole  *bool   `json:"clientRole,omitempty"`
	ClientID    *string `json:"clientId,omitempty"`
}

type CreateUserAttributeInput struct {
	Name   string `json:"name"`
	Value  string `json:"value"`
	UserID string `json:"userId"`
}

type CreateUserAttributeMapperInput struct {
	Name           string  `json:"name"`
	UserAttribute  string  `json:"userAttribute"`
	TokenClaimName string  `json:"tokenClaimName"`
	TokenType      string  `json:"tokenType"`
	MultiValued    *bool   `json:"multiValued,omitempty"`
	Protocol       *string `json:"protocol,omitempty"`
	ClientID       *string `json:"clientId,omitempty"`
}

type CreateUserInput struct {
	Username      string                `json:"username"`
	Email         string                `json:"email"`
	FirstName     *string               `json:"firstName,omitempty"`
	LastName      *string               `json:"lastName,omitempty"`
	Enabled       *bool                 `json:"enabled,omitempty"`
	EmailVerified *bool                 `json:"emailVerified,omitempty"`
	Credentials   []UserCredentialInput `json:"credentials,omitempty"`
	Groups        []string              `json:"groups,omitempty"`
	Roles         []string              `json:"roles,omitempty"`
}

type FederatedIdentity struct {
	IdentityProvider string `json:"identityProvider"`
	UserID           string `json:"userId"`
	Username         string `json:"username"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type PasswordPolicy struct {
	MinLength             *int  `json:"minLength,omitempty"`
	MaxLength             *int  `json:"maxLength,omitempty"`
	LowerCase             *int  `json:"lowerCase,omitempty"`
	UpperCase             *int  `json:"upperCase,omitempty"`
	Digits                *int  `json:"digits,omitempty"`
	SpecialChars          *int  `json:"specialChars,omitempty"`
	ForceExpiredPasswords *bool `json:"forceExpiredPasswords,omitempty"`
	NotUsername           *bool `json:"notUsername,omitempty"`
}

type PasswordPolicyConfigInput struct {
	DigitRegex            *string `json:"digitRegex,omitempty"`
	Length                *int    `json:"length,omitempty"`
	LowerCase             *int    `json:"lowerCase,omitempty"`
	SpecialChars          *int    `json:"specialChars,omitempty"`
	UpperCase             *int    `json:"upperCase,omitempty"`
	ForceExpiredPasswords *bool   `json:"forceExpiredPasswords,omitempty"`
	NotUsername           *bool   `json:"notUsername,omitempty"`
}

type Query struct {
}

type RealmKeyInput struct {
	Name        string  `json:"name"`
	Type        string  `json:"type"`
	ProviderID  string  `json:"providerId"`
	Active      *bool   `json:"active,omitempty"`
	Priority    *int    `json:"priority,omitempty"`
	PublicKey   *string `json:"publicKey,omitempty"`
	PrivateKey  *string `json:"privateKey,omitempty"`
	Certificate *string `json:"certificate,omitempty"`
}

type RoleMapping struct {
	ClientMappings []domain.Role `json:"clientMappings,omitempty"`
	RealmMappings  []domain.Role `json:"realmMappings,omitempty"`
}

type SessionConnection struct {
	Edges      []SessionEdge `json:"edges"`
	TotalCount int           `json:"totalCount"`
	PageInfo   *PageInfo     `json:"pageInfo"`
}

type SessionEdge struct {
	Node   *domain.Session `json:"node"`
	Cursor string          `json:"cursor"`
}

type UpdateAuthenticationFlowInput struct {
	Alias       *string `json:"alias,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UpdateClientInput struct {
	ClientName                *string             `json:"clientName,omitempty"`
	Description               *string             `json:"description,omitempty"`
	Enabled                   *bool               `json:"enabled,omitempty"`
	RedirectUris              []string            `json:"redirectUris,omitempty"`
	PostLogoutRedirectUris    []string            `json:"postLogoutRedirectUris,omitempty"`
	WebOrigins                []string            `json:"webOrigins,omitempty"`
	AllowedGrantTypes         []string            `json:"allowedGrantTypes,omitempty"`
	StandardFlowEnabled       *bool               `json:"standardFlowEnabled,omitempty"`
	ImplicitFlowEnabled       *bool               `json:"implicitFlowEnabled,omitempty"`
	DirectAccessGrantsEnabled *bool               `json:"directAccessGrantsEnabled,omitempty"`
	ServiceAccountsEnabled    *bool               `json:"serviceAccountsEnabled,omitempty"`
	PublicClient              *bool               `json:"publicClient,omitempty"`
	FrontchannelLogout        *bool               `json:"frontchannelLogout,omitempty"`
	FullScopeAllowed          *bool               `json:"fullScopeAllowed,omitempty"`
	DefaultRoles              []string            `json:"defaultRoles,omitempty"`
	OptionalClaims            []ClaimMappingInput `json:"optionalClaims,omitempty"`
	Scope                     []string            `json:"scope,omitempty"`
	ClientSecret              *string             `json:"clientSecret,omitempty"`
	ClientType                *string             `json:"clientType,omitempty"`
	Jwks                      *string             `json:"jwks,omitempty"`
	JwksURI                   *string             `json:"jwksUri,omitempty"`
}

type UpdateGroupInput struct {
	Name       *string  `json:"name,omitempty"`
	Path       *string  `json:"path,omitempty"`
	RealmRoles []string `json:"realmRoles,omitempty"`
}

type UpdateIdentityProviderInput struct {
	DisplayName               *string        `json:"displayName,omitempty"`
	Enabled                   *bool          `json:"enabled,omitempty"`
	Config                    map[string]any `json:"config,omitempty"`
	TrustEmail                *bool          `json:"trustEmail,omitempty"`
	StoreToken                *bool          `json:"storeToken,omitempty"`
	AddReadTokenRoleOnCreate  *bool          `json:"addReadTokenRoleOnCreate,omitempty"`
	AuthenticateDefaultAction *bool          `json:"authenticateDefaultAction,omitempty"`
}

type UpdateProtocolMapperInput struct {
	Name           *string        `json:"name,omitempty"`
	Protocol       *string        `json:"protocol,omitempty"`
	ProtocolMapper *string        `json:"protocolMapper,omitempty"`
	Config         map[string]any `json:"config,omitempty"`
}

type UpdateRealmInput struct {
	DisplayName                  *string                    `json:"displayName,omitempty"`
	RegistrationAllowed          *bool                      `json:"registrationAllowed,omitempty"`
	LoginWithEmailAllowed        *bool                      `json:"loginWithEmailAllowed,omitempty"`
	DuplicateEmailsAllowed       *bool                      `json:"duplicateEmailsAllowed,omitempty"`
	ResetPasswordAllowed         *bool                      `json:"resetPasswordAllowed,omitempty"`
	EditUsernameAllowed          *bool                      `json:"editUsernameAllowed,omitempty"`
	BruteForceProtected          *bool                      `json:"bruteForceProtected,omitempty"`
	PermanentLockout             *int                       `json:"permanentLockout,omitempty"`
	WaitIncrementSeconds         *int                       `json:"waitIncrementSeconds,omitempty"`
	MinimumQuickLoginWaitSeconds *int                       `json:"minimumQuickLoginWaitSeconds,omitempty"`
	QuickLoginCheckSMTPPort      *int                       `json:"quickLoginCheckSMTPPort,omitempty"`
	QuickLoginCheckSMTPHost      *string                    `json:"quickLoginCheckSMTPHost,omitempty"`
	MaxTemporaryLockouts         *int                       `json:"maxTemporaryLockouts,omitempty"`
	Enabled                      *bool                      `json:"enabled,omitempty"`
	SslRequired                  *string                    `json:"sslRequired,omitempty"`
	PasswordCredentialConfig     *PasswordPolicyConfigInput `json:"passwordCredentialConfig,omitempty"`
}

type UpdateRealmKeysInput struct {
	Keys []RealmKeyInput `json:"keys,omitempty"`
}

type UpdateRoleInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Composite   *bool   `json:"composite,omitempty"`
}

type UpdateUserAttributeInput struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

type UpdateUserAttributeMapperInput struct {
	Name           *string `json:"name,omitempty"`
	UserAttribute  *string `json:"userAttribute,omitempty"`
	TokenClaimName *string `json:"tokenClaimName,omitempty"`
	TokenType      *string `json:"tokenType,omitempty"`
	MultiValued    *bool   `json:"multiValued,omitempty"`
	Protocol       *string `json:"protocol,omitempty"`
	ClientID       *string `json:"clientId,omitempty"`
}

type UpdateUserInput struct {
	Username      *string  `json:"username,omitempty"`
	Email         *string  `json:"email,omitempty"`
	FirstName     *string  `json:"firstName,omitempty"`
	LastName      *string  `json:"lastName,omitempty"`
	Enabled       *bool    `json:"enabled,omitempty"`
	EmailVerified *bool    `json:"emailVerified,omitempty"`
	Groups        []string `json:"groups,omitempty"`
	Roles         []string `json:"roles,omitempty"`
}

type UserConnection struct {
	Edges      []UserEdge `json:"edges"`
	TotalCount int        `json:"totalCount"`
	PageInfo   *PageInfo  `json:"pageInfo"`
}

type UserCredential struct {
	ID             string     `json:"id"`
	Type           *string    `json:"type,omitempty"`
	CreatedDate    *time.Time `json:"createdDate,omitempty"`
	CredentialData *string    `json:"credentialData,omitempty"`
	Priority       *int       `json:"priority,omitempty"`
	Value          *string    `json:"value,omitempty"`
	Temporary      *bool      `json:"temporary,omitempty"`
	UserLabel      *string    `json:"userLabel,omitempty"`
}

type UserCredentialInput struct {
	Type      string `json:"type"`
	Value     string `json:"value"`
	Temporary *bool  `json:"temporary,omitempty"`
}

type UserEdge struct {
	Node   *domain.User `json:"node"`
	Cursor string       `json:"cursor"`
}

type UserFilter struct {
	Email         *string `json:"email,omitempty"`
	Username      *string `json:"username,omitempty"`
	FirstName     *string `json:"firstName,omitempty"`
	LastName      *string `json:"lastName,omitempty"`
	Enabled       *bool   `json:"enabled,omitempty"`
	EmailVerified *bool   `json:"emailVerified,omitempty"`
	Search        *string `json:"search,omitempty"`
}
