{{- if and .Values.frontend.enabled .Values.frontend.secrets.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.frontend.secrets.secretName }}
  labels:
    {{- include "ssso-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
type: Opaque
data:
  cookie-secret: {{ .Values.frontend.secrets.cookieSecret | b64enc | quote }}
  client-id: {{ .Values.frontend.secrets.clientId | b64enc | quote }}
  client-secret: {{ .Values.frontend.secrets.clientSecret | b64enc | quote }}
{{- end }}
