// Code generated by MockGen. DO NOT EDIT.
// Source: models.go
//
// Generated by this command:
//
//	mockgen -source=models.go -destination=mocks/mock_models.go -package=mock_oidcflow
//

// Package mock_oidcflow is a generated GoMock package.
package mock_oidcflow
