// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_interfaces.go -package=mock_services OAuthService,TokenService,PKCEService,JWKSService,UserService,TwoFactorService,FederationService,ConfigurationService,ClientService,PhoneVerificationService,MFAService,PushMFAService,IDPManagementService,ClientManagementService,ServiceAccountService
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"
	time "time"

	jwt "github.com/golang-jwt/jwt/v5"
	api "github.com/pilab-dev/shadow-sso/api"
	domain "github.com/pilab-dev/shadow-sso/domain"
	services "github.com/pilab-dev/shadow-sso/services"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuthService is a mock of OAuthService interface.
type MockOAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthServiceMockRecorder
	isgomock struct{}
}

// MockOAuthServiceMockRecorder is the mock recorder for MockOAuthService.
type MockOAuthServiceMockRecorder struct {
	mock *MockOAuthService
}

// NewMockOAuthService creates a new mock instance.
func NewMockOAuthService(ctrl *gomock.Controller) *MockOAuthService {
	mock := &MockOAuthService{ctrl: ctrl}
	mock.recorder = &MockOAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthService) EXPECT() *MockOAuthServiceMockRecorder {
	return m.recorder
}

// ClientCredentials mocks base method.
func (m *MockOAuthService) ClientCredentials(ctx context.Context, clientID, clientSecret, scope string) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientCredentials", ctx, clientID, clientSecret, scope)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClientCredentials indicates an expected call of ClientCredentials.
func (mr *MockOAuthServiceMockRecorder) ClientCredentials(ctx, clientID, clientSecret, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientCredentials", reflect.TypeOf((*MockOAuthService)(nil).ClientCredentials), ctx, clientID, clientSecret, scope)
}

// DirectGrant mocks base method.
func (m *MockOAuthService) DirectGrant(ctx context.Context, clientID, clientSecret, username, password, scope string) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DirectGrant", ctx, clientID, clientSecret, username, password, scope)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DirectGrant indicates an expected call of DirectGrant.
func (mr *MockOAuthServiceMockRecorder) DirectGrant(ctx, clientID, clientSecret, username, password, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DirectGrant", reflect.TypeOf((*MockOAuthService)(nil).DirectGrant), ctx, clientID, clientSecret, username, password, scope)
}

// ExchangeAuthorizationCode mocks base method.
func (m *MockOAuthService) ExchangeAuthorizationCode(ctx context.Context, code, clientID, clientSecret, redirectURI string) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeAuthorizationCode", ctx, code, clientID, clientSecret, redirectURI)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeAuthorizationCode indicates an expected call of ExchangeAuthorizationCode.
func (mr *MockOAuthServiceMockRecorder) ExchangeAuthorizationCode(ctx, code, clientID, clientSecret, redirectURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeAuthorizationCode", reflect.TypeOf((*MockOAuthService)(nil).ExchangeAuthorizationCode), ctx, code, clientID, clientSecret, redirectURI)
}

// GenerateAuthCode mocks base method.
func (m *MockOAuthService) GenerateAuthCode(ctx context.Context, clientID, userID, redirectURI, scope, codeChallenge, codeChallengeMethod, nonce string, authTime time.Time) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAuthCode", ctx, clientID, userID, redirectURI, scope, codeChallenge, codeChallengeMethod, nonce, authTime)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAuthCode indicates an expected call of GenerateAuthCode.
func (mr *MockOAuthServiceMockRecorder) GenerateAuthCode(ctx, clientID, userID, redirectURI, scope, codeChallenge, codeChallengeMethod, nonce, authTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAuthCode", reflect.TypeOf((*MockOAuthService)(nil).GenerateAuthCode), ctx, clientID, userID, redirectURI, scope, codeChallenge, codeChallengeMethod, nonce, authTime)
}

// GetJWKS mocks base method.
func (m *MockOAuthService) GetJWKS() *domain.JWKS {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJWKS")
	ret0, _ := ret[0].(*domain.JWKS)
	return ret0
}

// GetJWKS indicates an expected call of GetJWKS.
func (mr *MockOAuthServiceMockRecorder) GetJWKS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJWKS", reflect.TypeOf((*MockOAuthService)(nil).GetJWKS))
}

// GetUserSessions mocks base method.
func (m *MockOAuthService) GetUserSessions(ctx context.Context, userID string) ([]*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSessions", ctx, userID)
	ret0, _ := ret[0].([]*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSessions indicates an expected call of GetUserSessions.
func (mr *MockOAuthServiceMockRecorder) GetUserSessions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSessions", reflect.TypeOf((*MockOAuthService)(nil).GetUserSessions), ctx, userID)
}

// InitiateDeviceAuthorization mocks base method.
func (m *MockOAuthService) InitiateDeviceAuthorization(ctx context.Context, clientID, scope, verificationBaseURI string) (*api.DeviceAuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateDeviceAuthorization", ctx, clientID, scope, verificationBaseURI)
	ret0, _ := ret[0].(*api.DeviceAuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateDeviceAuthorization indicates an expected call of InitiateDeviceAuthorization.
func (mr *MockOAuthServiceMockRecorder) InitiateDeviceAuthorization(ctx, clientID, scope, verificationBaseURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateDeviceAuthorization", reflect.TypeOf((*MockOAuthService)(nil).InitiateDeviceAuthorization), ctx, clientID, scope, verificationBaseURI)
}

// IntrospectToken mocks base method.
func (m *MockOAuthService) IntrospectToken(ctx context.Context, token, tokenTypeHint, clientID, clientSecret string) (*domain.TokenIntrospection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntrospectToken", ctx, token, tokenTypeHint, clientID, clientSecret)
	ret0, _ := ret[0].(*domain.TokenIntrospection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IntrospectToken indicates an expected call of IntrospectToken.
func (mr *MockOAuthServiceMockRecorder) IntrospectToken(ctx, token, tokenTypeHint, clientID, clientSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntrospectToken", reflect.TypeOf((*MockOAuthService)(nil).IntrospectToken), ctx, token, tokenTypeHint, clientID, clientSecret)
}

// IssueTokenForDeviceFlow mocks base method.
func (m *MockOAuthService) IssueTokenForDeviceFlow(ctx context.Context, deviceCode, clientID string) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueTokenForDeviceFlow", ctx, deviceCode, clientID)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueTokenForDeviceFlow indicates an expected call of IssueTokenForDeviceFlow.
func (mr *MockOAuthServiceMockRecorder) IssueTokenForDeviceFlow(ctx, deviceCode, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueTokenForDeviceFlow", reflect.TypeOf((*MockOAuthService)(nil).IssueTokenForDeviceFlow), ctx, deviceCode, clientID)
}

// Login mocks base method.
func (m *MockOAuthService) Login(ctx context.Context, username, password, deviceInfo string) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, username, password, deviceInfo)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockOAuthServiceMockRecorder) Login(ctx, username, password, deviceInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockOAuthService)(nil).Login), ctx, username, password, deviceInfo)
}

// PasswordGrant mocks base method.
func (m *MockOAuthService) PasswordGrant(ctx context.Context, username, password, scope string, cli *domain.Client) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasswordGrant", ctx, username, password, scope, cli)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PasswordGrant indicates an expected call of PasswordGrant.
func (mr *MockOAuthServiceMockRecorder) PasswordGrant(ctx, username, password, scope, cli any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordGrant", reflect.TypeOf((*MockOAuthService)(nil).PasswordGrant), ctx, username, password, scope, cli)
}

// RefreshToken mocks base method.
func (m *MockOAuthService) RefreshToken(ctx context.Context, refreshTokenValue, clientID string) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, refreshTokenValue, clientID)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockOAuthServiceMockRecorder) RefreshToken(ctx, refreshTokenValue, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockOAuthService)(nil).RefreshToken), ctx, refreshTokenValue, clientID)
}

// RegisterUser mocks base method.
func (m *MockOAuthService) RegisterUser(ctx context.Context, username, password string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, username, password)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockOAuthServiceMockRecorder) RegisterUser(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockOAuthService)(nil).RegisterUser), ctx, username, password)
}

// RevokeToken mocks base method.
func (m *MockOAuthService) RevokeToken(ctx context.Context, tokenToRevoke, tokenTypeHint, clientID, clientSecret string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, tokenToRevoke, tokenTypeHint, clientID, clientSecret)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockOAuthServiceMockRecorder) RevokeToken(ctx, tokenToRevoke, tokenTypeHint, clientID, clientSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockOAuthService)(nil).RevokeToken), ctx, tokenToRevoke, tokenTypeHint, clientID, clientSecret)
}

// TokenExchange mocks base method.
func (m *MockOAuthService) TokenExchange(ctx context.Context, subjectToken, subjectTokenType, requestedTokenType, resource, scope, clientID string) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenExchange", ctx, subjectToken, subjectTokenType, requestedTokenType, resource, scope, clientID)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokenExchange indicates an expected call of TokenExchange.
func (mr *MockOAuthServiceMockRecorder) TokenExchange(ctx, subjectToken, subjectTokenType, requestedTokenType, resource, scope, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenExchange", reflect.TypeOf((*MockOAuthService)(nil).TokenExchange), ctx, subjectToken, subjectTokenType, requestedTokenType, resource, scope, clientID)
}

// ValidateClient mocks base method.
func (m *MockOAuthService) ValidateClient(ctx context.Context, clientID, clientSecret string) (*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateClient", ctx, clientID, clientSecret)
	ret0, _ := ret[0].(*domain.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateClient indicates an expected call of ValidateClient.
func (mr *MockOAuthServiceMockRecorder) ValidateClient(ctx, clientID, clientSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateClient", reflect.TypeOf((*MockOAuthService)(nil).ValidateClient), ctx, clientID, clientSecret)
}

// VerifyUserCode mocks base method.
func (m *MockOAuthService) VerifyUserCode(ctx context.Context, userCode, userID string) (*domain.DeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUserCode", ctx, userCode, userID)
	ret0, _ := ret[0].(*domain.DeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyUserCode indicates an expected call of VerifyUserCode.
func (mr *MockOAuthServiceMockRecorder) VerifyUserCode(ctx, userCode, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUserCode", reflect.TypeOf((*MockOAuthService)(nil).VerifyUserCode), ctx, userCode, userID)
}

// MockTokenService is a mock of TokenService interface.
type MockTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceMockRecorder
	isgomock struct{}
}

// MockTokenServiceMockRecorder is the mock recorder for MockTokenService.
type MockTokenServiceMockRecorder struct {
	mock *MockTokenService
}

// NewMockTokenService creates a new mock instance.
func NewMockTokenService(ctrl *gomock.Controller) *MockTokenService {
	mock := &MockTokenService{ctrl: ctrl}
	mock.recorder = &MockTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenService) EXPECT() *MockTokenServiceMockRecorder {
	return m.recorder
}

// ApplyTokenMappers mocks base method.
func (m *MockTokenService) ApplyTokenMappers(ctx context.Context, claims map[string]any, clientID, userID, tokenType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyTokenMappers", ctx, claims, clientID, userID, tokenType)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyTokenMappers indicates an expected call of ApplyTokenMappers.
func (mr *MockTokenServiceMockRecorder) ApplyTokenMappers(ctx, claims, clientID, userID, tokenType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyTokenMappers", reflect.TypeOf((*MockTokenService)(nil).ApplyTokenMappers), ctx, claims, clientID, userID, tokenType)
}

// BuildToken mocks base method.
func (m *MockTokenService) BuildToken(token *domain.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildToken", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuildToken indicates an expected call of BuildToken.
func (mr *MockTokenServiceMockRecorder) BuildToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildToken", reflect.TypeOf((*MockTokenService)(nil).BuildToken), token)
}

// CreateToken mocks base method.
func (m *MockTokenService) CreateToken(ctx context.Context, opts domain.CreateTokenOptions, claims jwt.Claims) (*domain.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", ctx, opts, claims)
	ret0, _ := ret[0].(*domain.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockTokenServiceMockRecorder) CreateToken(ctx, opts, claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockTokenService)(nil).CreateToken), ctx, opts, claims)
}

// GenerateIDToken mocks base method.
func (m *MockTokenService) GenerateIDToken(ctx context.Context, userID, clientID, nonce string, authTime time.Time, scope string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateIDToken", ctx, userID, clientID, nonce, authTime, scope)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateIDToken indicates an expected call of GenerateIDToken.
func (mr *MockTokenServiceMockRecorder) GenerateIDToken(ctx, userID, clientID, nonce, authTime, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateIDToken", reflect.TypeOf((*MockTokenService)(nil).GenerateIDToken), ctx, userID, clientID, nonce, authTime, scope)
}

// GenerateTokenPair mocks base method.
func (m *MockTokenService) GenerateTokenPair(ctx context.Context, clientID, userID, scope string, tokenTTL time.Duration) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokenPair", ctx, clientID, userID, scope, tokenTTL)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTokenPair indicates an expected call of GenerateTokenPair.
func (mr *MockTokenServiceMockRecorder) GenerateTokenPair(ctx, clientID, userID, scope, tokenTTL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokenPair", reflect.TypeOf((*MockTokenService)(nil).GenerateTokenPair), ctx, clientID, userID, scope, tokenTTL)
}

// GenerateTokenPairWithFamily mocks base method.
func (m *MockTokenService) GenerateTokenPairWithFamily(ctx context.Context, clientID, userID, scope string, tokenTTL time.Duration, family, nonce string, authTime time.Time) (*api.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokenPairWithFamily", ctx, clientID, userID, scope, tokenTTL, family, nonce, authTime)
	ret0, _ := ret[0].(*api.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTokenPairWithFamily indicates an expected call of GenerateTokenPairWithFamily.
func (mr *MockTokenServiceMockRecorder) GenerateTokenPairWithFamily(ctx, clientID, userID, scope, tokenTTL, family, nonce, authTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokenPairWithFamily", reflect.TypeOf((*MockTokenService)(nil).GenerateTokenPairWithFamily), ctx, clientID, userID, scope, tokenTTL, family, nonce, authTime)
}

// GetAccessTokenInfo mocks base method.
func (m *MockTokenService) GetAccessTokenInfo(ctx context.Context, tokenValue string) (*domain.TokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessTokenInfo", ctx, tokenValue)
	ret0, _ := ret[0].(*domain.TokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessTokenInfo indicates an expected call of GetAccessTokenInfo.
func (mr *MockTokenServiceMockRecorder) GetAccessTokenInfo(ctx, tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessTokenInfo", reflect.TypeOf((*MockTokenService)(nil).GetAccessTokenInfo), ctx, tokenValue)
}

// GetRefreshTokenInfo mocks base method.
func (m *MockTokenService) GetRefreshTokenInfo(ctx context.Context, tokenValue string) (*domain.TokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenInfo", ctx, tokenValue)
	ret0, _ := ret[0].(*domain.TokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenInfo indicates an expected call of GetRefreshTokenInfo.
func (mr *MockTokenServiceMockRecorder) GetRefreshTokenInfo(ctx, tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenInfo", reflect.TypeOf((*MockTokenService)(nil).GetRefreshTokenInfo), ctx, tokenValue)
}

// RevokeToken mocks base method.
func (m *MockTokenService) RevokeToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockTokenServiceMockRecorder) RevokeToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockTokenService)(nil).RevokeToken), ctx, token)
}

// ValidateAccessToken mocks base method.
func (m *MockTokenService) ValidateAccessToken(ctx context.Context, tokenValue string) (*domain.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", ctx, tokenValue)
	ret0, _ := ret[0].(*domain.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockTokenServiceMockRecorder) ValidateAccessToken(ctx, tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockTokenService)(nil).ValidateAccessToken), ctx, tokenValue)
}

// ValidateIDToken mocks base method.
func (m *MockTokenService) ValidateIDToken(ctx context.Context, tokenValue string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateIDToken", ctx, tokenValue)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateIDToken indicates an expected call of ValidateIDToken.
func (mr *MockTokenServiceMockRecorder) ValidateIDToken(ctx, tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateIDToken", reflect.TypeOf((*MockTokenService)(nil).ValidateIDToken), ctx, tokenValue)
}

// MockPKCEService is a mock of PKCEService interface.
type MockPKCEService struct {
	ctrl     *gomock.Controller
	recorder *MockPKCEServiceMockRecorder
	isgomock struct{}
}

// MockPKCEServiceMockRecorder is the mock recorder for MockPKCEService.
type MockPKCEServiceMockRecorder struct {
	mock *MockPKCEService
}

// NewMockPKCEService creates a new mock instance.
func NewMockPKCEService(ctrl *gomock.Controller) *MockPKCEService {
	mock := &MockPKCEService{ctrl: ctrl}
	mock.recorder = &MockPKCEServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPKCEService) EXPECT() *MockPKCEServiceMockRecorder {
	return m.recorder
}

// SavePKCEChallenge mocks base method.
func (m *MockPKCEService) SavePKCEChallenge(ctx context.Context, code, challenge string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePKCEChallenge", ctx, code, challenge)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePKCEChallenge indicates an expected call of SavePKCEChallenge.
func (mr *MockPKCEServiceMockRecorder) SavePKCEChallenge(ctx, code, challenge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePKCEChallenge", reflect.TypeOf((*MockPKCEService)(nil).SavePKCEChallenge), ctx, code, challenge)
}

// ValidateCodeVerifier mocks base method.
func (m *MockPKCEService) ValidateCodeVerifier(ctx context.Context, code, verifier string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCodeVerifier", ctx, code, verifier)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateCodeVerifier indicates an expected call of ValidateCodeVerifier.
func (mr *MockPKCEServiceMockRecorder) ValidateCodeVerifier(ctx, code, verifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCodeVerifier", reflect.TypeOf((*MockPKCEService)(nil).ValidateCodeVerifier), ctx, code, verifier)
}

// MockJWKSService is a mock of JWKSService interface.
type MockJWKSService struct {
	ctrl     *gomock.Controller
	recorder *MockJWKSServiceMockRecorder
	isgomock struct{}
}

// MockJWKSServiceMockRecorder is the mock recorder for MockJWKSService.
type MockJWKSServiceMockRecorder struct {
	mock *MockJWKSService
}

// NewMockJWKSService creates a new mock instance.
func NewMockJWKSService(ctrl *gomock.Controller) *MockJWKSService {
	mock := &MockJWKSService{ctrl: ctrl}
	mock.recorder = &MockJWKSServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWKSService) EXPECT() *MockJWKSServiceMockRecorder {
	return m.recorder
}

// GetJWKS mocks base method.
func (m *MockJWKSService) GetJWKS() services.JSONWebKeySet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJWKS")
	ret0, _ := ret[0].(services.JSONWebKeySet)
	return ret0
}

// GetJWKS indicates an expected call of GetJWKS.
func (mr *MockJWKSServiceMockRecorder) GetJWKS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJWKS", reflect.TypeOf((*MockJWKSService)(nil).GetJWKS))
}

// GetPublicJWKS mocks base method.
func (m *MockJWKSService) GetPublicJWKS(ctx context.Context) (*services.JSONWebKeySet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicJWKS", ctx)
	ret0, _ := ret[0].(*services.JSONWebKeySet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicJWKS indicates an expected call of GetPublicJWKS.
func (mr *MockJWKSServiceMockRecorder) GetPublicJWKS(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicJWKS", reflect.TypeOf((*MockJWKSService)(nil).GetPublicJWKS), ctx)
}

// GetSigningKey mocks base method.
func (m *MockJWKSService) GetSigningKey() (string, any) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSigningKey")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(any)
	return ret0, ret1
}

// GetSigningKey indicates an expected call of GetSigningKey.
func (mr *MockJWKSServiceMockRecorder) GetSigningKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSigningKey", reflect.TypeOf((*MockJWKSService)(nil).GetSigningKey))
}

// MockClientService is a mock of ClientService interface.
type MockClientService struct {
	ctrl     *gomock.Controller
	recorder *MockClientServiceMockRecorder
	isgomock struct{}
}

// MockClientServiceMockRecorder is the mock recorder for MockClientService.
type MockClientServiceMockRecorder struct {
	mock *MockClientService
}

// NewMockClientService creates a new mock instance.
func NewMockClientService(ctrl *gomock.Controller) *MockClientService {
	mock := &MockClientService{ctrl: ctrl}
	mock.recorder = &MockClientServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientService) EXPECT() *MockClientServiceMockRecorder {
	return m.recorder
}

// CreateClient mocks base method.
func (m *MockClientService) CreateClient(ctx context.Context, client *domain.Client) (*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClient", ctx, client)
	ret0, _ := ret[0].(*domain.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClient indicates an expected call of CreateClient.
func (mr *MockClientServiceMockRecorder) CreateClient(ctx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClient", reflect.TypeOf((*MockClientService)(nil).CreateClient), ctx, client)
}

// CreateConfidentialClient mocks base method.
func (m *MockClientService) CreateConfidentialClient(ctx context.Context, name string, redirectURIs, allowedScopes []string) (*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConfidentialClient", ctx, name, redirectURIs, allowedScopes)
	ret0, _ := ret[0].(*domain.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConfidentialClient indicates an expected call of CreateConfidentialClient.
func (mr *MockClientServiceMockRecorder) CreateConfidentialClient(ctx, name, redirectURIs, allowedScopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConfidentialClient", reflect.TypeOf((*MockClientService)(nil).CreateConfidentialClient), ctx, name, redirectURIs, allowedScopes)
}

// CreatePublicClient mocks base method.
func (m *MockClientService) CreatePublicClient(ctx context.Context, name string, redirectURIs, allowedScopes []string) (*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePublicClient", ctx, name, redirectURIs, allowedScopes)
	ret0, _ := ret[0].(*domain.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePublicClient indicates an expected call of CreatePublicClient.
func (mr *MockClientServiceMockRecorder) CreatePublicClient(ctx, name, redirectURIs, allowedScopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePublicClient", reflect.TypeOf((*MockClientService)(nil).CreatePublicClient), ctx, name, redirectURIs, allowedScopes)
}

// GetClient mocks base method.
func (m *MockClientService) GetClient(ctx context.Context, clientID string) (*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", ctx, clientID)
	ret0, _ := ret[0].(*domain.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockClientServiceMockRecorder) GetClient(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockClientService)(nil).GetClient), ctx, clientID)
}

// RequiresPKCE mocks base method.
func (m *MockClientService) RequiresPKCE(ctx context.Context, clientID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequiresPKCE", ctx, clientID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequiresPKCE indicates an expected call of RequiresPKCE.
func (mr *MockClientServiceMockRecorder) RequiresPKCE(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequiresPKCE", reflect.TypeOf((*MockClientService)(nil).RequiresPKCE), ctx, clientID)
}

// ValidateClient mocks base method.
func (m *MockClientService) ValidateClient(ctx context.Context, clientID, clientSecret string) (*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateClient", ctx, clientID, clientSecret)
	ret0, _ := ret[0].(*domain.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateClient indicates an expected call of ValidateClient.
func (mr *MockClientServiceMockRecorder) ValidateClient(ctx, clientID, clientSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateClient", reflect.TypeOf((*MockClientService)(nil).ValidateClient), ctx, clientID, clientSecret)
}

// ValidateGrantType mocks base method.
func (m *MockClientService) ValidateGrantType(ctx context.Context, clientID, grantType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateGrantType", ctx, clientID, grantType)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateGrantType indicates an expected call of ValidateGrantType.
func (mr *MockClientServiceMockRecorder) ValidateGrantType(ctx, clientID, grantType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateGrantType", reflect.TypeOf((*MockClientService)(nil).ValidateGrantType), ctx, clientID, grantType)
}

// ValidateRedirectURI mocks base method.
func (m *MockClientService) ValidateRedirectURI(ctx context.Context, clientID, redirectURI string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRedirectURI", ctx, clientID, redirectURI)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateRedirectURI indicates an expected call of ValidateRedirectURI.
func (mr *MockClientServiceMockRecorder) ValidateRedirectURI(ctx, clientID, redirectURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRedirectURI", reflect.TypeOf((*MockClientService)(nil).ValidateRedirectURI), ctx, clientID, redirectURI)
}

// ValidateScope mocks base method.
func (m *MockClientService) ValidateScope(ctx context.Context, clientID string, requestedScopes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateScope", ctx, clientID, requestedScopes)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateScope indicates an expected call of ValidateScope.
func (mr *MockClientServiceMockRecorder) ValidateScope(ctx, clientID, requestedScopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateScope", reflect.TypeOf((*MockClientService)(nil).ValidateScope), ctx, clientID, requestedScopes)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// ActivateUser mocks base method.
func (m *MockUserService) ActivateUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateUser indicates an expected call of ActivateUser.
func (mr *MockUserServiceMockRecorder) ActivateUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateUser", reflect.TypeOf((*MockUserService)(nil).ActivateUser), ctx, userID)
}

// ChangePassword mocks base method.
func (m *MockUserService) ChangePassword(ctx context.Context, userID, oldPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, userID, oldPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockUserServiceMockRecorder) ChangePassword(ctx, userID, oldPassword, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockUserService)(nil).ChangePassword), ctx, userID, oldPassword, newPassword)
}

// GetUser mocks base method.
func (m *MockUserService) GetUser(ctx context.Context, userID string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserServiceMockRecorder) GetUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserService)(nil).GetUser), ctx, userID)
}

// ListUsers mocks base method.
func (m *MockUserService) ListUsers(ctx context.Context, pageToken string, pageSize int) ([]*domain.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, pageToken, pageSize)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUserServiceMockRecorder) ListUsers(ctx, pageToken, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUserService)(nil).ListUsers), ctx, pageToken, pageSize)
}

// LockUser mocks base method.
func (m *MockUserService) LockUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockUser indicates an expected call of LockUser.
func (mr *MockUserServiceMockRecorder) LockUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockUser", reflect.TypeOf((*MockUserService)(nil).LockUser), ctx, userID)
}

// RegisterUser mocks base method.
func (m *MockUserService) RegisterUser(ctx context.Context, email, password, firstName, lastName string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, email, password, firstName, lastName)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockUserServiceMockRecorder) RegisterUser(ctx, email, password, firstName, lastName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockUserService)(nil).RegisterUser), ctx, email, password, firstName, lastName)
}

// SendPhoneVerificationOtp mocks base method.
func (m *MockUserService) SendPhoneVerificationOtp(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPhoneVerificationOtp", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPhoneVerificationOtp indicates an expected call of SendPhoneVerificationOtp.
func (mr *MockUserServiceMockRecorder) SendPhoneVerificationOtp(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPhoneVerificationOtp", reflect.TypeOf((*MockUserService)(nil).SendPhoneVerificationOtp), ctx, userID)
}

// VerifyPhoneNumber mocks base method.
func (m *MockUserService) VerifyPhoneNumber(ctx context.Context, userID, otp string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPhoneNumber", ctx, userID, otp)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyPhoneNumber indicates an expected call of VerifyPhoneNumber.
func (mr *MockUserServiceMockRecorder) VerifyPhoneNumber(ctx, userID, otp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPhoneNumber", reflect.TypeOf((*MockUserService)(nil).VerifyPhoneNumber), ctx, userID, otp)
}

// MockTwoFactorService is a mock of TwoFactorService interface.
type MockTwoFactorService struct {
	ctrl     *gomock.Controller
	recorder *MockTwoFactorServiceMockRecorder
	isgomock struct{}
}

// MockTwoFactorServiceMockRecorder is the mock recorder for MockTwoFactorService.
type MockTwoFactorServiceMockRecorder struct {
	mock *MockTwoFactorService
}

// NewMockTwoFactorService creates a new mock instance.
func NewMockTwoFactorService(ctrl *gomock.Controller) *MockTwoFactorService {
	mock := &MockTwoFactorService{ctrl: ctrl}
	mock.recorder = &MockTwoFactorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTwoFactorService) EXPECT() *MockTwoFactorServiceMockRecorder {
	return m.recorder
}

// Disable2FA mocks base method.
func (m *MockTwoFactorService) Disable2FA(ctx context.Context, userID, passwordOr2FaCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable2FA", ctx, userID, passwordOr2FaCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disable2FA indicates an expected call of Disable2FA.
func (mr *MockTwoFactorServiceMockRecorder) Disable2FA(ctx, userID, passwordOr2FaCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable2FA", reflect.TypeOf((*MockTwoFactorService)(nil).Disable2FA), ctx, userID, passwordOr2FaCode)
}

// GenerateRecoveryCodes mocks base method.
func (m *MockTwoFactorService) GenerateRecoveryCodes(ctx context.Context, userID, passwordOr2FaCode string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRecoveryCodes", ctx, userID, passwordOr2FaCode)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRecoveryCodes indicates an expected call of GenerateRecoveryCodes.
func (mr *MockTwoFactorServiceMockRecorder) GenerateRecoveryCodes(ctx, userID, passwordOr2FaCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRecoveryCodes", reflect.TypeOf((*MockTwoFactorService)(nil).GenerateRecoveryCodes), ctx, userID, passwordOr2FaCode)
}

// GetPushChallengeStatus mocks base method.
func (m *MockTwoFactorService) GetPushChallengeStatus(ctx context.Context, userID, challengeID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPushChallengeStatus", ctx, userID, challengeID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPushChallengeStatus indicates an expected call of GetPushChallengeStatus.
func (mr *MockTwoFactorServiceMockRecorder) GetPushChallengeStatus(ctx, userID, challengeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPushChallengeStatus", reflect.TypeOf((*MockTwoFactorService)(nil).GetPushChallengeStatus), ctx, userID, challengeID)
}

// InitiateEmailMFASetup mocks base method.
func (m *MockTwoFactorService) InitiateEmailMFASetup(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateEmailMFASetup", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitiateEmailMFASetup indicates an expected call of InitiateEmailMFASetup.
func (mr *MockTwoFactorServiceMockRecorder) InitiateEmailMFASetup(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateEmailMFASetup", reflect.TypeOf((*MockTwoFactorService)(nil).InitiateEmailMFASetup), ctx, userID)
}

// InitiateHOTPSetup mocks base method.
func (m *MockTwoFactorService) InitiateHOTPSetup(ctx context.Context, userID string) (string, string, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateHOTPSetup", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(uint64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// InitiateHOTPSetup indicates an expected call of InitiateHOTPSetup.
func (mr *MockTwoFactorServiceMockRecorder) InitiateHOTPSetup(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateHOTPSetup", reflect.TypeOf((*MockTwoFactorService)(nil).InitiateHOTPSetup), ctx, userID)
}

// InitiatePushMFASetup mocks base method.
func (m *MockTwoFactorService) InitiatePushMFASetup(ctx context.Context, userID, deviceToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiatePushMFASetup", ctx, userID, deviceToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitiatePushMFASetup indicates an expected call of InitiatePushMFASetup.
func (mr *MockTwoFactorServiceMockRecorder) InitiatePushMFASetup(ctx, userID, deviceToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiatePushMFASetup", reflect.TypeOf((*MockTwoFactorService)(nil).InitiatePushMFASetup), ctx, userID, deviceToken)
}

// InitiateTOTPSetup mocks base method.
func (m *MockTwoFactorService) InitiateTOTPSetup(ctx context.Context, userID string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateTOTPSetup", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InitiateTOTPSetup indicates an expected call of InitiateTOTPSetup.
func (mr *MockTwoFactorServiceMockRecorder) InitiateTOTPSetup(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateTOTPSetup", reflect.TypeOf((*MockTwoFactorService)(nil).InitiateTOTPSetup), ctx, userID)
}

// RegisterPushDevice mocks base method.
func (m *MockTwoFactorService) RegisterPushDevice(ctx context.Context, userID, deviceToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterPushDevice", ctx, userID, deviceToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterPushDevice indicates an expected call of RegisterPushDevice.
func (mr *MockTwoFactorServiceMockRecorder) RegisterPushDevice(ctx, userID, deviceToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterPushDevice", reflect.TypeOf((*MockTwoFactorService)(nil).RegisterPushDevice), ctx, userID, deviceToken)
}

// RespondToPushChallenge mocks base method.
func (m *MockTwoFactorService) RespondToPushChallenge(ctx context.Context, userID, challengeID, response string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RespondToPushChallenge", ctx, userID, challengeID, response)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RespondToPushChallenge indicates an expected call of RespondToPushChallenge.
func (mr *MockTwoFactorServiceMockRecorder) RespondToPushChallenge(ctx, userID, challengeID, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RespondToPushChallenge", reflect.TypeOf((*MockTwoFactorService)(nil).RespondToPushChallenge), ctx, userID, challengeID, response)
}

// SendMFAChallenge mocks base method.
func (m *MockTwoFactorService) SendMFAChallenge(ctx context.Context, userID string) (string, uint64, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMFAChallenge", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// SendMFAChallenge indicates an expected call of SendMFAChallenge.
func (mr *MockTwoFactorServiceMockRecorder) SendMFAChallenge(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMFAChallenge", reflect.TypeOf((*MockTwoFactorService)(nil).SendMFAChallenge), ctx, userID)
}

// UnregisterPushDevice mocks base method.
func (m *MockTwoFactorService) UnregisterPushDevice(ctx context.Context, userID, deviceToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterPushDevice", ctx, userID, deviceToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterPushDevice indicates an expected call of UnregisterPushDevice.
func (mr *MockTwoFactorServiceMockRecorder) UnregisterPushDevice(ctx, userID, deviceToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterPushDevice", reflect.TypeOf((*MockTwoFactorService)(nil).UnregisterPushDevice), ctx, userID, deviceToken)
}

// VerifyAndEnableEmailMFA mocks base method.
func (m *MockTwoFactorService) VerifyAndEnableEmailMFA(ctx context.Context, userID, emailOtp string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAndEnableEmailMFA", ctx, userID, emailOtp)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAndEnableEmailMFA indicates an expected call of VerifyAndEnableEmailMFA.
func (mr *MockTwoFactorServiceMockRecorder) VerifyAndEnableEmailMFA(ctx, userID, emailOtp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAndEnableEmailMFA", reflect.TypeOf((*MockTwoFactorService)(nil).VerifyAndEnableEmailMFA), ctx, userID, emailOtp)
}

// VerifyAndEnableHOTP mocks base method.
func (m *MockTwoFactorService) VerifyAndEnableHOTP(ctx context.Context, userID, hotpCode string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAndEnableHOTP", ctx, userID, hotpCode)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAndEnableHOTP indicates an expected call of VerifyAndEnableHOTP.
func (mr *MockTwoFactorServiceMockRecorder) VerifyAndEnableHOTP(ctx, userID, hotpCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAndEnableHOTP", reflect.TypeOf((*MockTwoFactorService)(nil).VerifyAndEnableHOTP), ctx, userID, hotpCode)
}

// VerifyAndEnablePushMFA mocks base method.
func (m *MockTwoFactorService) VerifyAndEnablePushMFA(ctx context.Context, userID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAndEnablePushMFA", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAndEnablePushMFA indicates an expected call of VerifyAndEnablePushMFA.
func (mr *MockTwoFactorServiceMockRecorder) VerifyAndEnablePushMFA(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAndEnablePushMFA", reflect.TypeOf((*MockTwoFactorService)(nil).VerifyAndEnablePushMFA), ctx, userID)
}

// VerifyAndEnableTOTP mocks base method.
func (m *MockTwoFactorService) VerifyAndEnableTOTP(ctx context.Context, userID, totpCode string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAndEnableTOTP", ctx, userID, totpCode)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAndEnableTOTP indicates an expected call of VerifyAndEnableTOTP.
func (mr *MockTwoFactorServiceMockRecorder) VerifyAndEnableTOTP(ctx, userID, totpCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAndEnableTOTP", reflect.TypeOf((*MockTwoFactorService)(nil).VerifyAndEnableTOTP), ctx, userID, totpCode)
}

// VerifyMFAChallenge mocks base method.
func (m *MockTwoFactorService) VerifyMFAChallenge(ctx context.Context, userID, code string, counter uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyMFAChallenge", ctx, userID, code, counter)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyMFAChallenge indicates an expected call of VerifyMFAChallenge.
func (mr *MockTwoFactorServiceMockRecorder) VerifyMFAChallenge(ctx, userID, code, counter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyMFAChallenge", reflect.TypeOf((*MockTwoFactorService)(nil).VerifyMFAChallenge), ctx, userID, code, counter)
}

// MockFederationService is a mock of FederationService interface.
type MockFederationService struct {
	ctrl     *gomock.Controller
	recorder *MockFederationServiceMockRecorder
	isgomock struct{}
}

// MockFederationServiceMockRecorder is the mock recorder for MockFederationService.
type MockFederationServiceMockRecorder struct {
	mock *MockFederationService
}

// NewMockFederationService creates a new mock instance.
func NewMockFederationService(ctrl *gomock.Controller) *MockFederationService {
	mock := &MockFederationService{ctrl: ctrl}
	mock.recorder = &MockFederationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFederationService) EXPECT() *MockFederationServiceMockRecorder {
	return m.recorder
}

// AuthenticateDirect mocks base method.
func (m *MockFederationService) AuthenticateDirect(ctx context.Context, providerName, username, password string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateDirect", ctx, providerName, username, password)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateDirect indicates an expected call of AuthenticateDirect.
func (mr *MockFederationServiceMockRecorder) AuthenticateDirect(ctx, providerName, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateDirect", reflect.TypeOf((*MockFederationService)(nil).AuthenticateDirect), ctx, providerName, username, password)
}

// ConfirmMergeFederatedAccount mocks base method.
func (m *MockFederationService) ConfirmMergeFederatedAccount(ctx context.Context, continuationToken string) (*services.FederationCallbackResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmMergeFederatedAccount", ctx, continuationToken)
	ret0, _ := ret[0].(*services.FederationCallbackResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmMergeFederatedAccount indicates an expected call of ConfirmMergeFederatedAccount.
func (mr *MockFederationServiceMockRecorder) ConfirmMergeFederatedAccount(ctx, continuationToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmMergeFederatedAccount", reflect.TypeOf((*MockFederationService)(nil).ConfirmMergeFederatedAccount), ctx, continuationToken)
}

// GenerateAuthState mocks base method.
func (m *MockFederationService) GenerateAuthState() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAuthState")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAuthState indicates an expected call of GenerateAuthState.
func (mr *MockFederationServiceMockRecorder) GenerateAuthState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAuthState", reflect.TypeOf((*MockFederationService)(nil).GenerateAuthState))
}

// GetAuthorizationURL mocks base method.
func (m *MockFederationService) GetAuthorizationURL(ctx context.Context, providerName, state string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationURL", ctx, providerName, state)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorizationURL indicates an expected call of GetAuthorizationURL.
func (mr *MockFederationServiceMockRecorder) GetAuthorizationURL(ctx, providerName, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationURL", reflect.TypeOf((*MockFederationService)(nil).GetAuthorizationURL), ctx, providerName, state)
}

// HandleFederatedCallback mocks base method.
func (m *MockFederationService) HandleFederatedCallback(ctx context.Context, providerName, state, sessionState, code string) (*services.FederationCallbackResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleFederatedCallback", ctx, providerName, state, sessionState, code)
	ret0, _ := ret[0].(*services.FederationCallbackResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleFederatedCallback indicates an expected call of HandleFederatedCallback.
func (mr *MockFederationServiceMockRecorder) HandleFederatedCallback(ctx, providerName, state, sessionState, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleFederatedCallback", reflect.TypeOf((*MockFederationService)(nil).HandleFederatedCallback), ctx, providerName, state, sessionState, code)
}

// InitiateFederatedLogin mocks base method.
func (m *MockFederationService) InitiateFederatedLogin(ctx context.Context, providerName string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateFederatedLogin", ctx, providerName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InitiateFederatedLogin indicates an expected call of InitiateFederatedLogin.
func (mr *MockFederationServiceMockRecorder) InitiateFederatedLogin(ctx, providerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateFederatedLogin", reflect.TypeOf((*MockFederationService)(nil).InitiateFederatedLogin), ctx, providerName)
}

// ListUserFederatedIdentities mocks base method.
func (m *MockFederationService) ListUserFederatedIdentities(ctx context.Context, userID string) ([]*domain.UserFederatedIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserFederatedIdentities", ctx, userID)
	ret0, _ := ret[0].([]*domain.UserFederatedIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserFederatedIdentities indicates an expected call of ListUserFederatedIdentities.
func (mr *MockFederationServiceMockRecorder) ListUserFederatedIdentities(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserFederatedIdentities", reflect.TypeOf((*MockFederationService)(nil).ListUserFederatedIdentities), ctx, userID)
}

// PromptMergeFederatedAccount mocks base method.
func (m *MockFederationService) PromptMergeFederatedAccount(ctx context.Context, continuationToken string) (*services.MergePromptResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptMergeFederatedAccount", ctx, continuationToken)
	ret0, _ := ret[0].(*services.MergePromptResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromptMergeFederatedAccount indicates an expected call of PromptMergeFederatedAccount.
func (mr *MockFederationServiceMockRecorder) PromptMergeFederatedAccount(ctx, continuationToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptMergeFederatedAccount", reflect.TypeOf((*MockFederationService)(nil).PromptMergeFederatedAccount), ctx, continuationToken)
}

// RemoveUserFederatedIdentity mocks base method.
func (m *MockFederationService) RemoveUserFederatedIdentity(ctx context.Context, userID, providerName, providerUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFederatedIdentity", ctx, userID, providerName, providerUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFederatedIdentity indicates an expected call of RemoveUserFederatedIdentity.
func (mr *MockFederationServiceMockRecorder) RemoveUserFederatedIdentity(ctx, userID, providerName, providerUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFederatedIdentity", reflect.TypeOf((*MockFederationService)(nil).RemoveUserFederatedIdentity), ctx, userID, providerName, providerUserID)
}

// Stop mocks base method.
func (m *MockFederationService) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockFederationServiceMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockFederationService)(nil).Stop))
}

// MockIDPManagementService is a mock of IDPManagementService interface.
type MockIDPManagementService struct {
	ctrl     *gomock.Controller
	recorder *MockIDPManagementServiceMockRecorder
	isgomock struct{}
}

// MockIDPManagementServiceMockRecorder is the mock recorder for MockIDPManagementService.
type MockIDPManagementServiceMockRecorder struct {
	mock *MockIDPManagementService
}

// NewMockIDPManagementService creates a new mock instance.
func NewMockIDPManagementService(ctrl *gomock.Controller) *MockIDPManagementService {
	mock := &MockIDPManagementService{ctrl: ctrl}
	mock.recorder = &MockIDPManagementServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDPManagementService) EXPECT() *MockIDPManagementServiceMockRecorder {
	return m.recorder
}

// AddIdP mocks base method.
func (m *MockIDPManagementService) AddIdP(ctx context.Context, idp *domain.IdentityProvider) (*domain.IdentityProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddIdP", ctx, idp)
	ret0, _ := ret[0].(*domain.IdentityProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddIdP indicates an expected call of AddIdP.
func (mr *MockIDPManagementServiceMockRecorder) AddIdP(ctx, idp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIdP", reflect.TypeOf((*MockIDPManagementService)(nil).AddIdP), ctx, idp)
}

// DeleteIdP mocks base method.
func (m *MockIDPManagementService) DeleteIdP(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIdP", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIdP indicates an expected call of DeleteIdP.
func (mr *MockIDPManagementServiceMockRecorder) DeleteIdP(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIdP", reflect.TypeOf((*MockIDPManagementService)(nil).DeleteIdP), ctx, id)
}

// GetIdP mocks base method.
func (m *MockIDPManagementService) GetIdP(ctx context.Context, id string) (*domain.IdentityProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdP", ctx, id)
	ret0, _ := ret[0].(*domain.IdentityProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdP indicates an expected call of GetIdP.
func (mr *MockIDPManagementServiceMockRecorder) GetIdP(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdP", reflect.TypeOf((*MockIDPManagementService)(nil).GetIdP), ctx, id)
}

// ListIdPs mocks base method.
func (m *MockIDPManagementService) ListIdPs(ctx context.Context, onlyEnabled bool) ([]*domain.IdentityProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIdPs", ctx, onlyEnabled)
	ret0, _ := ret[0].([]*domain.IdentityProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIdPs indicates an expected call of ListIdPs.
func (mr *MockIDPManagementServiceMockRecorder) ListIdPs(ctx, onlyEnabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIdPs", reflect.TypeOf((*MockIDPManagementService)(nil).ListIdPs), ctx, onlyEnabled)
}

// UpdateIdP mocks base method.
func (m *MockIDPManagementService) UpdateIdP(ctx context.Context, idp *domain.IdentityProvider) (*domain.IdentityProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIdP", ctx, idp)
	ret0, _ := ret[0].(*domain.IdentityProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateIdP indicates an expected call of UpdateIdP.
func (mr *MockIDPManagementServiceMockRecorder) UpdateIdP(ctx, idp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIdP", reflect.TypeOf((*MockIDPManagementService)(nil).UpdateIdP), ctx, idp)
}

// MockClientManagementService is a mock of ClientManagementService interface.
type MockClientManagementService struct {
	ctrl     *gomock.Controller
	recorder *MockClientManagementServiceMockRecorder
	isgomock struct{}
}

// MockClientManagementServiceMockRecorder is the mock recorder for MockClientManagementService.
type MockClientManagementServiceMockRecorder struct {
	mock *MockClientManagementService
}

// NewMockClientManagementService creates a new mock instance.
func NewMockClientManagementService(ctrl *gomock.Controller) *MockClientManagementService {
	mock := &MockClientManagementService{ctrl: ctrl}
	mock.recorder = &MockClientManagementServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientManagementService) EXPECT() *MockClientManagementServiceMockRecorder {
	return m.recorder
}

// DeleteClient mocks base method.
func (m *MockClientManagementService) DeleteClient(ctx context.Context, clientID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClient", ctx, clientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClient indicates an expected call of DeleteClient.
func (mr *MockClientManagementServiceMockRecorder) DeleteClient(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClient", reflect.TypeOf((*MockClientManagementService)(nil).DeleteClient), ctx, clientID)
}

// GetClient mocks base method.
func (m *MockClientManagementService) GetClient(ctx context.Context, clientID string) (*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", ctx, clientID)
	ret0, _ := ret[0].(*domain.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockClientManagementServiceMockRecorder) GetClient(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockClientManagementService)(nil).GetClient), ctx, clientID)
}

// ListClients mocks base method.
func (m *MockClientManagementService) ListClients(ctx context.Context, filter domain.ClientFilter) ([]*domain.Client, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClients", ctx, filter)
	ret0, _ := ret[0].([]*domain.Client)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListClients indicates an expected call of ListClients.
func (mr *MockClientManagementServiceMockRecorder) ListClients(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClients", reflect.TypeOf((*MockClientManagementService)(nil).ListClients), ctx, filter)
}

// RegisterClient mocks base method.
func (m *MockClientManagementService) RegisterClient(ctx context.Context, client *domain.Client) (*domain.Client, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterClient", ctx, client)
	ret0, _ := ret[0].(*domain.Client)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RegisterClient indicates an expected call of RegisterClient.
func (mr *MockClientManagementServiceMockRecorder) RegisterClient(ctx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterClient", reflect.TypeOf((*MockClientManagementService)(nil).RegisterClient), ctx, client)
}

// UpdateClient mocks base method.
func (m *MockClientManagementService) UpdateClient(ctx context.Context, client *domain.Client) (*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClient", ctx, client)
	ret0, _ := ret[0].(*domain.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateClient indicates an expected call of UpdateClient.
func (mr *MockClientManagementServiceMockRecorder) UpdateClient(ctx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClient", reflect.TypeOf((*MockClientManagementService)(nil).UpdateClient), ctx, client)
}

// MockServiceAccountService is a mock of ServiceAccountService interface.
type MockServiceAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceAccountServiceMockRecorder
	isgomock struct{}
}

// MockServiceAccountServiceMockRecorder is the mock recorder for MockServiceAccountService.
type MockServiceAccountServiceMockRecorder struct {
	mock *MockServiceAccountService
}

// NewMockServiceAccountService creates a new mock instance.
func NewMockServiceAccountService(ctrl *gomock.Controller) *MockServiceAccountService {
	mock := &MockServiceAccountService{ctrl: ctrl}
	mock.recorder = &MockServiceAccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceAccountService) EXPECT() *MockServiceAccountServiceMockRecorder {
	return m.recorder
}

// CreateServiceAccountKey mocks base method.
func (m *MockServiceAccountService) CreateServiceAccountKey(ctx context.Context, projectID, clientEmail, displayName string) (*domain.ServiceAccount, *domain.ServiceAccountKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServiceAccountKey", ctx, projectID, clientEmail, displayName)
	ret0, _ := ret[0].(*domain.ServiceAccount)
	ret1, _ := ret[1].(*domain.ServiceAccountKey)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateServiceAccountKey indicates an expected call of CreateServiceAccountKey.
func (mr *MockServiceAccountServiceMockRecorder) CreateServiceAccountKey(ctx, projectID, clientEmail, displayName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServiceAccountKey", reflect.TypeOf((*MockServiceAccountService)(nil).CreateServiceAccountKey), ctx, projectID, clientEmail, displayName)
}

// DeleteServiceAccountKey mocks base method.
func (m *MockServiceAccountService) DeleteServiceAccountKey(ctx context.Context, serviceAccountID, keyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceAccountKey", ctx, serviceAccountID, keyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceAccountKey indicates an expected call of DeleteServiceAccountKey.
func (mr *MockServiceAccountServiceMockRecorder) DeleteServiceAccountKey(ctx, serviceAccountID, keyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceAccountKey", reflect.TypeOf((*MockServiceAccountService)(nil).DeleteServiceAccountKey), ctx, serviceAccountID, keyID)
}

// ListServiceAccountKeys mocks base method.
func (m *MockServiceAccountService) ListServiceAccountKeys(ctx context.Context, serviceAccountID string) ([]*domain.PublicKeyInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServiceAccountKeys", ctx, serviceAccountID)
	ret0, _ := ret[0].([]*domain.PublicKeyInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServiceAccountKeys indicates an expected call of ListServiceAccountKeys.
func (mr *MockServiceAccountServiceMockRecorder) ListServiceAccountKeys(ctx, serviceAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServiceAccountKeys", reflect.TypeOf((*MockServiceAccountService)(nil).ListServiceAccountKeys), ctx, serviceAccountID)
}

// MockConfigurationService is a mock of ConfigurationService interface.
type MockConfigurationService struct {
	ctrl     *gomock.Controller
	recorder *MockConfigurationServiceMockRecorder
	isgomock struct{}
}

// MockConfigurationServiceMockRecorder is the mock recorder for MockConfigurationService.
type MockConfigurationServiceMockRecorder struct {
	mock *MockConfigurationService
}

// NewMockConfigurationService creates a new mock instance.
func NewMockConfigurationService(ctrl *gomock.Controller) *MockConfigurationService {
	mock := &MockConfigurationService{ctrl: ctrl}
	mock.recorder = &MockConfigurationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigurationService) EXPECT() *MockConfigurationServiceMockRecorder {
	return m.recorder
}

// BootstrapDefaultConfigs mocks base method.
func (m *MockConfigurationService) BootstrapDefaultConfigs(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BootstrapDefaultConfigs", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// BootstrapDefaultConfigs indicates an expected call of BootstrapDefaultConfigs.
func (mr *MockConfigurationServiceMockRecorder) BootstrapDefaultConfigs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BootstrapDefaultConfigs", reflect.TypeOf((*MockConfigurationService)(nil).BootstrapDefaultConfigs), ctx)
}

// GetAllByType mocks base method.
func (m *MockConfigurationService) GetAllByType(ctx context.Context, configType domain.ConfigurationType) ([]*domain.Configuration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByType", ctx, configType)
	ret0, _ := ret[0].([]*domain.Configuration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByType indicates an expected call of GetAllByType.
func (mr *MockConfigurationServiceMockRecorder) GetAllByType(ctx, configType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByType", reflect.TypeOf((*MockConfigurationService)(nil).GetAllByType), ctx, configType)
}

// GetBool mocks base method.
func (m *MockConfigurationService) GetBool(ctx context.Context, configType domain.ConfigurationType, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBool", ctx, configType, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBool indicates an expected call of GetBool.
func (mr *MockConfigurationServiceMockRecorder) GetBool(ctx, configType, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBool", reflect.TypeOf((*MockConfigurationService)(nil).GetBool), ctx, configType, key)
}

// GetBoolWithDefault mocks base method.
func (m *MockConfigurationService) GetBoolWithDefault(ctx context.Context, configType domain.ConfigurationType, key string, defaultValue bool) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoolWithDefault", ctx, configType, key, defaultValue)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetBoolWithDefault indicates an expected call of GetBoolWithDefault.
func (mr *MockConfigurationServiceMockRecorder) GetBoolWithDefault(ctx, configType, key, defaultValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoolWithDefault", reflect.TypeOf((*MockConfigurationService)(nil).GetBoolWithDefault), ctx, configType, key, defaultValue)
}

// GetString mocks base method.
func (m *MockConfigurationService) GetString(ctx context.Context, configType domain.ConfigurationType, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetString", ctx, configType, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetString indicates an expected call of GetString.
func (mr *MockConfigurationServiceMockRecorder) GetString(ctx, configType, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetString", reflect.TypeOf((*MockConfigurationService)(nil).GetString), ctx, configType, key)
}

// GetStringWithDefault mocks base method.
func (m *MockConfigurationService) GetStringWithDefault(ctx context.Context, configType domain.ConfigurationType, key, defaultValue string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStringWithDefault", ctx, configType, key, defaultValue)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetStringWithDefault indicates an expected call of GetStringWithDefault.
func (mr *MockConfigurationServiceMockRecorder) GetStringWithDefault(ctx, configType, key, defaultValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStringWithDefault", reflect.TypeOf((*MockConfigurationService)(nil).GetStringWithDefault), ctx, configType, key, defaultValue)
}

// RefreshCache mocks base method.
func (m *MockConfigurationService) RefreshCache(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshCache", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshCache indicates an expected call of RefreshCache.
func (mr *MockConfigurationServiceMockRecorder) RefreshCache(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshCache", reflect.TypeOf((*MockConfigurationService)(nil).RefreshCache), ctx)
}

// SetString mocks base method.
func (m *MockConfigurationService) SetString(ctx context.Context, configType domain.ConfigurationType, key, value string, encrypt bool, description, updatedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetString", ctx, configType, key, value, encrypt, description, updatedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetString indicates an expected call of SetString.
func (mr *MockConfigurationServiceMockRecorder) SetString(ctx, configType, key, value, encrypt, description, updatedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetString", reflect.TypeOf((*MockConfigurationService)(nil).SetString), ctx, configType, key, value, encrypt, description, updatedBy)
}

// MockPhoneVerificationService is a mock of PhoneVerificationService interface.
type MockPhoneVerificationService struct {
	ctrl     *gomock.Controller
	recorder *MockPhoneVerificationServiceMockRecorder
	isgomock struct{}
}

// MockPhoneVerificationServiceMockRecorder is the mock recorder for MockPhoneVerificationService.
type MockPhoneVerificationServiceMockRecorder struct {
	mock *MockPhoneVerificationService
}

// NewMockPhoneVerificationService creates a new mock instance.
func NewMockPhoneVerificationService(ctrl *gomock.Controller) *MockPhoneVerificationService {
	mock := &MockPhoneVerificationService{ctrl: ctrl}
	mock.recorder = &MockPhoneVerificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhoneVerificationService) EXPECT() *MockPhoneVerificationServiceMockRecorder {
	return m.recorder
}

// SendVerificationOTP mocks base method.
func (m *MockPhoneVerificationService) SendVerificationOTP(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationOTP", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendVerificationOTP indicates an expected call of SendVerificationOTP.
func (mr *MockPhoneVerificationServiceMockRecorder) SendVerificationOTP(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationOTP", reflect.TypeOf((*MockPhoneVerificationService)(nil).SendVerificationOTP), ctx, userID)
}

// VerifyPhoneNumber mocks base method.
func (m *MockPhoneVerificationService) VerifyPhoneNumber(ctx context.Context, userID, otp string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPhoneNumber", ctx, userID, otp)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyPhoneNumber indicates an expected call of VerifyPhoneNumber.
func (mr *MockPhoneVerificationServiceMockRecorder) VerifyPhoneNumber(ctx, userID, otp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPhoneNumber", reflect.TypeOf((*MockPhoneVerificationService)(nil).VerifyPhoneNumber), ctx, userID, otp)
}

// MockMFAService is a mock of MFAService interface.
type MockMFAService struct {
	ctrl     *gomock.Controller
	recorder *MockMFAServiceMockRecorder
	isgomock struct{}
}

// MockMFAServiceMockRecorder is the mock recorder for MockMFAService.
type MockMFAServiceMockRecorder struct {
	mock *MockMFAService
}

// NewMockMFAService creates a new mock instance.
func NewMockMFAService(ctrl *gomock.Controller) *MockMFAService {
	mock := &MockMFAService{ctrl: ctrl}
	mock.recorder = &MockMFAServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMFAService) EXPECT() *MockMFAServiceMockRecorder {
	return m.recorder
}

// DisableEmailMFA mocks base method.
func (m *MockMFAService) DisableEmailMFA(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableEmailMFA", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableEmailMFA indicates an expected call of DisableEmailMFA.
func (mr *MockMFAServiceMockRecorder) DisableEmailMFA(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableEmailMFA", reflect.TypeOf((*MockMFAService)(nil).DisableEmailMFA), ctx, userID)
}

// InitiateEmailMFASetup mocks base method.
func (m *MockMFAService) InitiateEmailMFASetup(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateEmailMFASetup", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitiateEmailMFASetup indicates an expected call of InitiateEmailMFASetup.
func (mr *MockMFAServiceMockRecorder) InitiateEmailMFASetup(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateEmailMFASetup", reflect.TypeOf((*MockMFAService)(nil).InitiateEmailMFASetup), ctx, userID)
}

// SendMFAChallenge mocks base method.
func (m *MockMFAService) SendMFAChallenge(ctx context.Context, userID string) (string, uint64, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMFAChallenge", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// SendMFAChallenge indicates an expected call of SendMFAChallenge.
func (mr *MockMFAServiceMockRecorder) SendMFAChallenge(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMFAChallenge", reflect.TypeOf((*MockMFAService)(nil).SendMFAChallenge), ctx, userID)
}

// VerifyAndEnableEmailMFA mocks base method.
func (m *MockMFAService) VerifyAndEnableEmailMFA(ctx context.Context, userID, otp string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAndEnableEmailMFA", ctx, userID, otp)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyAndEnableEmailMFA indicates an expected call of VerifyAndEnableEmailMFA.
func (mr *MockMFAServiceMockRecorder) VerifyAndEnableEmailMFA(ctx, userID, otp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAndEnableEmailMFA", reflect.TypeOf((*MockMFAService)(nil).VerifyAndEnableEmailMFA), ctx, userID, otp)
}

// VerifyMFAChallenge mocks base method.
func (m *MockMFAService) VerifyMFAChallenge(ctx context.Context, userID, code string, counter uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyMFAChallenge", ctx, userID, code, counter)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyMFAChallenge indicates an expected call of VerifyMFAChallenge.
func (mr *MockMFAServiceMockRecorder) VerifyMFAChallenge(ctx, userID, code, counter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyMFAChallenge", reflect.TypeOf((*MockMFAService)(nil).VerifyMFAChallenge), ctx, userID, code, counter)
}

// VerifyMFAChallengeWithChallengeID mocks base method.
func (m *MockMFAService) VerifyMFAChallengeWithChallengeID(ctx context.Context, userID, challengeID, code string, counter uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyMFAChallengeWithChallengeID", ctx, userID, challengeID, code, counter)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyMFAChallengeWithChallengeID indicates an expected call of VerifyMFAChallengeWithChallengeID.
func (mr *MockMFAServiceMockRecorder) VerifyMFAChallengeWithChallengeID(ctx, userID, challengeID, code, counter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyMFAChallengeWithChallengeID", reflect.TypeOf((*MockMFAService)(nil).VerifyMFAChallengeWithChallengeID), ctx, userID, challengeID, code, counter)
}

// MockPushMFAService is a mock of PushMFAService interface.
type MockPushMFAService struct {
	ctrl     *gomock.Controller
	recorder *MockPushMFAServiceMockRecorder
	isgomock struct{}
}

// MockPushMFAServiceMockRecorder is the mock recorder for MockPushMFAService.
type MockPushMFAServiceMockRecorder struct {
	mock *MockPushMFAService
}

// NewMockPushMFAService creates a new mock instance.
func NewMockPushMFAService(ctrl *gomock.Controller) *MockPushMFAService {
	mock := &MockPushMFAService{ctrl: ctrl}
	mock.recorder = &MockPushMFAServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushMFAService) EXPECT() *MockPushMFAServiceMockRecorder {
	return m.recorder
}

// CreatePushMFAChallenge mocks base method.
func (m *MockPushMFAService) CreatePushMFAChallenge(ctx context.Context, user *domain.User, ipAddress, userAgent string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePushMFAChallenge", ctx, user, ipAddress, userAgent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePushMFAChallenge indicates an expected call of CreatePushMFAChallenge.
func (mr *MockPushMFAServiceMockRecorder) CreatePushMFAChallenge(ctx, user, ipAddress, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePushMFAChallenge", reflect.TypeOf((*MockPushMFAService)(nil).CreatePushMFAChallenge), ctx, user, ipAddress, userAgent)
}

// DisablePushMFA mocks base method.
func (m *MockPushMFAService) DisablePushMFA(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisablePushMFA", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisablePushMFA indicates an expected call of DisablePushMFA.
func (mr *MockPushMFAServiceMockRecorder) DisablePushMFA(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisablePushMFA", reflect.TypeOf((*MockPushMFAService)(nil).DisablePushMFA), ctx, userID)
}

// EnablePushMFA mocks base method.
func (m *MockPushMFAService) EnablePushMFA(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnablePushMFA", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnablePushMFA indicates an expected call of EnablePushMFA.
func (mr *MockPushMFAServiceMockRecorder) EnablePushMFA(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnablePushMFA", reflect.TypeOf((*MockPushMFAService)(nil).EnablePushMFA), ctx, userID)
}

// GetPushMFAChallengeStatus mocks base method.
func (m *MockPushMFAService) GetPushMFAChallengeStatus(ctx context.Context, userID, challengeID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPushMFAChallengeStatus", ctx, userID, challengeID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPushMFAChallengeStatus indicates an expected call of GetPushMFAChallengeStatus.
func (mr *MockPushMFAServiceMockRecorder) GetPushMFAChallengeStatus(ctx, userID, challengeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPushMFAChallengeStatus", reflect.TypeOf((*MockPushMFAService)(nil).GetPushMFAChallengeStatus), ctx, userID, challengeID)
}

// RegisterDeviceToken mocks base method.
func (m *MockPushMFAService) RegisterDeviceToken(ctx context.Context, userID, deviceToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterDeviceToken", ctx, userID, deviceToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterDeviceToken indicates an expected call of RegisterDeviceToken.
func (mr *MockPushMFAServiceMockRecorder) RegisterDeviceToken(ctx, userID, deviceToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterDeviceToken", reflect.TypeOf((*MockPushMFAService)(nil).RegisterDeviceToken), ctx, userID, deviceToken)
}

// UnregisterDeviceToken mocks base method.
func (m *MockPushMFAService) UnregisterDeviceToken(ctx context.Context, userID, deviceToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterDeviceToken", ctx, userID, deviceToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterDeviceToken indicates an expected call of UnregisterDeviceToken.
func (mr *MockPushMFAServiceMockRecorder) UnregisterDeviceToken(ctx, userID, deviceToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterDeviceToken", reflect.TypeOf((*MockPushMFAService)(nil).UnregisterDeviceToken), ctx, userID, deviceToken)
}

// VerifyPushMFAChallenge mocks base method.
func (m *MockPushMFAService) VerifyPushMFAChallenge(ctx context.Context, userID, challengeID string, approved bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPushMFAChallenge", ctx, userID, challengeID, approved)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyPushMFAChallenge indicates an expected call of VerifyPushMFAChallenge.
func (mr *MockPushMFAServiceMockRecorder) VerifyPushMFAChallenge(ctx, userID, challengeID, approved any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPushMFAChallenge", reflect.TypeOf((*MockPushMFAService)(nil).VerifyPushMFAChallenge), ctx, userID, challengeID, approved)
}

// MockFederationServiceInterface is a mock of FederationServiceInterface interface.
type MockFederationServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFederationServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockFederationServiceInterfaceMockRecorder is the mock recorder for MockFederationServiceInterface.
type MockFederationServiceInterfaceMockRecorder struct {
	mock *MockFederationServiceInterface
}

// NewMockFederationServiceInterface creates a new mock instance.
func NewMockFederationServiceInterface(ctrl *gomock.Controller) *MockFederationServiceInterface {
	mock := &MockFederationServiceInterface{ctrl: ctrl}
	mock.recorder = &MockFederationServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFederationServiceInterface) EXPECT() *MockFederationServiceInterfaceMockRecorder {
	return m.recorder
}

// GenerateAuthState mocks base method.
func (m *MockFederationServiceInterface) GenerateAuthState() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAuthState")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAuthState indicates an expected call of GenerateAuthState.
func (mr *MockFederationServiceInterfaceMockRecorder) GenerateAuthState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAuthState", reflect.TypeOf((*MockFederationServiceInterface)(nil).GenerateAuthState))
}

// GetAuthorizationURL mocks base method.
func (m *MockFederationServiceInterface) GetAuthorizationURL(ctx context.Context, providerName, state string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationURL", ctx, providerName, state)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorizationURL indicates an expected call of GetAuthorizationURL.
func (mr *MockFederationServiceInterfaceMockRecorder) GetAuthorizationURL(ctx, providerName, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationURL", reflect.TypeOf((*MockFederationServiceInterface)(nil).GetAuthorizationURL), ctx, providerName, state)
}

// HandleCallback mocks base method.
func (m *MockFederationServiceInterface) HandleCallback(ctx context.Context, providerName, queryState, sessionState, code string) (any, any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCallback", ctx, providerName, queryState, sessionState, code)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// HandleCallback indicates an expected call of HandleCallback.
func (mr *MockFederationServiceInterfaceMockRecorder) HandleCallback(ctx, providerName, queryState, sessionState, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCallback", reflect.TypeOf((*MockFederationServiceInterface)(nil).HandleCallback), ctx, providerName, queryState, sessionState, code)
}
