// Code generated by MockGen. DO NOT EDIT.
// Source: pkce_service.go
//
// Generated by this command:
//
//	mockgen -source=pkce_service.go -destination=mocks/mock_pkce_service.go -package=mock_services
//

// Package mock_services is a generated GoMock package.
package mock_services
