// Code generated by MockGen. DO NOT EDIT.
// Source: oauth_service.go
//
// Generated by this command:
//
//	mockgen -source=oauth_service.go -destination=mocks/mock_oauth_service.go -package=mock_services
//

// Package mock_services is a generated GoMock package.
package mock_services
